//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace BAGPS.BAGPS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="gisSoap", Namespace="http://tempuri.org/")]
    public partial class gis : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private GSAuthenticationHeader gSAuthenticationHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetAddressByGeoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAddressByGeo2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGeoByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGeoByName2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGeoByName3OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGeoByNameHaNoiOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGeoByPOIOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGeoByPOIDistanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckRegionByGeoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegionByGeoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSpeedAlarmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSpeedAlarm2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public gis() {
            this.Url = global::BAGPS.Properties.Settings.Default.BAGPS_BAGPS_gis;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public GSAuthenticationHeader GSAuthenticationHeaderValue {
            get {
                return this.gSAuthenticationHeaderValueField;
            }
            set {
                this.gSAuthenticationHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAddressByGeoCompletedEventHandler GetAddressByGeoCompleted;
        
        /// <remarks/>
        public event GetAddressByGeo2CompletedEventHandler GetAddressByGeo2Completed;
        
        /// <remarks/>
        public event GetGeoByNameCompletedEventHandler GetGeoByNameCompleted;
        
        /// <remarks/>
        public event GetGeoByName2CompletedEventHandler GetGeoByName2Completed;
        
        /// <remarks/>
        public event GetGeoByName3CompletedEventHandler GetGeoByName3Completed;
        
        /// <remarks/>
        public event GetGeoByNameHaNoiCompletedEventHandler GetGeoByNameHaNoiCompleted;
        
        /// <remarks/>
        public event GetGeoByPOICompletedEventHandler GetGeoByPOICompleted;
        
        /// <remarks/>
        public event GetGeoByPOIDistanceCompletedEventHandler GetGeoByPOIDistanceCompleted;
        
        /// <remarks/>
        public event CheckRegionByGeoCompletedEventHandler CheckRegionByGeoCompleted;
        
        /// <remarks/>
        public event GetRegionByGeoCompletedEventHandler GetRegionByGeoCompleted;
        
        /// <remarks/>
        public event GetSpeedAlarmCompletedEventHandler GetSpeedAlarmCompleted;
        
        /// <remarks/>
        public event GetSpeedAlarm2CompletedEventHandler GetSpeedAlarm2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GSAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAddressByGeo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GSAddressResult GetAddressByGeo(float lng, float lat, string lan) {
            object[] results = this.Invoke("GetAddressByGeo", new object[] {
                        lng,
                        lat,
                        lan});
            return ((GSAddressResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetAddressByGeoAsync(float lng, float lat, string lan) {
            this.GetAddressByGeoAsync(lng, lat, lan, null);
        }
        
        /// <remarks/>
        public void GetAddressByGeoAsync(float lng, float lat, string lan, object userState) {
            if ((this.GetAddressByGeoOperationCompleted == null)) {
                this.GetAddressByGeoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAddressByGeoOperationCompleted);
            }
            this.InvokeAsync("GetAddressByGeo", new object[] {
                        lng,
                        lat,
                        lan}, this.GetAddressByGeoOperationCompleted, userState);
        }
        
        private void OnGetAddressByGeoOperationCompleted(object arg) {
            if ((this.GetAddressByGeoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAddressByGeoCompleted(this, new GetAddressByGeoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GSAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAddressByGeo2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GSAddressResult[] GetAddressByGeo2(string slng, string slat, string lan) {
            object[] results = this.Invoke("GetAddressByGeo2", new object[] {
                        slng,
                        slat,
                        lan});
            return ((GSAddressResult[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAddressByGeo2Async(string slng, string slat, string lan) {
            this.GetAddressByGeo2Async(slng, slat, lan, null);
        }
        
        /// <remarks/>
        public void GetAddressByGeo2Async(string slng, string slat, string lan, object userState) {
            if ((this.GetAddressByGeo2OperationCompleted == null)) {
                this.GetAddressByGeo2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAddressByGeo2OperationCompleted);
            }
            this.InvokeAsync("GetAddressByGeo2", new object[] {
                        slng,
                        slat,
                        lan}, this.GetAddressByGeo2OperationCompleted, userState);
        }
        
        private void OnGetAddressByGeo2OperationCompleted(object arg) {
            if ((this.GetAddressByGeo2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAddressByGeo2Completed(this, new GetAddressByGeo2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GSAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGeoByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GSAddressResult GetGeoByName(int prv, string key, string lan) {
            object[] results = this.Invoke("GetGeoByName", new object[] {
                        prv,
                        key,
                        lan});
            return ((GSAddressResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetGeoByNameAsync(int prv, string key, string lan) {
            this.GetGeoByNameAsync(prv, key, lan, null);
        }
        
        /// <remarks/>
        public void GetGeoByNameAsync(int prv, string key, string lan, object userState) {
            if ((this.GetGeoByNameOperationCompleted == null)) {
                this.GetGeoByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGeoByNameOperationCompleted);
            }
            this.InvokeAsync("GetGeoByName", new object[] {
                        prv,
                        key,
                        lan}, this.GetGeoByNameOperationCompleted, userState);
        }
        
        private void OnGetGeoByNameOperationCompleted(object arg) {
            if ((this.GetGeoByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGeoByNameCompleted(this, new GetGeoByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GSAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGeoByName2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GSAddressResult GetGeoByName2(string key, string lan) {
            object[] results = this.Invoke("GetGeoByName2", new object[] {
                        key,
                        lan});
            return ((GSAddressResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetGeoByName2Async(string key, string lan) {
            this.GetGeoByName2Async(key, lan, null);
        }
        
        /// <remarks/>
        public void GetGeoByName2Async(string key, string lan, object userState) {
            if ((this.GetGeoByName2OperationCompleted == null)) {
                this.GetGeoByName2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGeoByName2OperationCompleted);
            }
            this.InvokeAsync("GetGeoByName2", new object[] {
                        key,
                        lan}, this.GetGeoByName2OperationCompleted, userState);
        }
        
        private void OnGetGeoByName2OperationCompleted(object arg) {
            if ((this.GetGeoByName2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGeoByName2Completed(this, new GetGeoByName2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GSAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGeoByName3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GSAddressResult GetGeoByName3(string key, string lan) {
            object[] results = this.Invoke("GetGeoByName3", new object[] {
                        key,
                        lan});
            return ((GSAddressResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetGeoByName3Async(string key, string lan) {
            this.GetGeoByName3Async(key, lan, null);
        }
        
        /// <remarks/>
        public void GetGeoByName3Async(string key, string lan, object userState) {
            if ((this.GetGeoByName3OperationCompleted == null)) {
                this.GetGeoByName3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGeoByName3OperationCompleted);
            }
            this.InvokeAsync("GetGeoByName3", new object[] {
                        key,
                        lan}, this.GetGeoByName3OperationCompleted, userState);
        }
        
        private void OnGetGeoByName3OperationCompleted(object arg) {
            if ((this.GetGeoByName3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGeoByName3Completed(this, new GetGeoByName3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GSAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGeoByNameHaNoi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GSAddressResult GetGeoByNameHaNoi(string key, string lan) {
            object[] results = this.Invoke("GetGeoByNameHaNoi", new object[] {
                        key,
                        lan});
            return ((GSAddressResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetGeoByNameHaNoiAsync(string key, string lan) {
            this.GetGeoByNameHaNoiAsync(key, lan, null);
        }
        
        /// <remarks/>
        public void GetGeoByNameHaNoiAsync(string key, string lan, object userState) {
            if ((this.GetGeoByNameHaNoiOperationCompleted == null)) {
                this.GetGeoByNameHaNoiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGeoByNameHaNoiOperationCompleted);
            }
            this.InvokeAsync("GetGeoByNameHaNoi", new object[] {
                        key,
                        lan}, this.GetGeoByNameHaNoiOperationCompleted, userState);
        }
        
        private void OnGetGeoByNameHaNoiOperationCompleted(object arg) {
            if ((this.GetGeoByNameHaNoiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGeoByNameHaNoiCompleted(this, new GetGeoByNameHaNoiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GSAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGeoByPOI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GSPOIResult GetGeoByPOI(string key, string lan) {
            object[] results = this.Invoke("GetGeoByPOI", new object[] {
                        key,
                        lan});
            return ((GSPOIResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetGeoByPOIAsync(string key, string lan) {
            this.GetGeoByPOIAsync(key, lan, null);
        }
        
        /// <remarks/>
        public void GetGeoByPOIAsync(string key, string lan, object userState) {
            if ((this.GetGeoByPOIOperationCompleted == null)) {
                this.GetGeoByPOIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGeoByPOIOperationCompleted);
            }
            this.InvokeAsync("GetGeoByPOI", new object[] {
                        key,
                        lan}, this.GetGeoByPOIOperationCompleted, userState);
        }
        
        private void OnGetGeoByPOIOperationCompleted(object arg) {
            if ((this.GetGeoByPOICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGeoByPOICompleted(this, new GetGeoByPOICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GSAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGeoByPOIDistance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GSPOIResult GetGeoByPOIDistance(string key, float lng, float lat, int dis, string lan) {
            object[] results = this.Invoke("GetGeoByPOIDistance", new object[] {
                        key,
                        lng,
                        lat,
                        dis,
                        lan});
            return ((GSPOIResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetGeoByPOIDistanceAsync(string key, float lng, float lat, int dis, string lan) {
            this.GetGeoByPOIDistanceAsync(key, lng, lat, dis, lan, null);
        }
        
        /// <remarks/>
        public void GetGeoByPOIDistanceAsync(string key, float lng, float lat, int dis, string lan, object userState) {
            if ((this.GetGeoByPOIDistanceOperationCompleted == null)) {
                this.GetGeoByPOIDistanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGeoByPOIDistanceOperationCompleted);
            }
            this.InvokeAsync("GetGeoByPOIDistance", new object[] {
                        key,
                        lng,
                        lat,
                        dis,
                        lan}, this.GetGeoByPOIDistanceOperationCompleted, userState);
        }
        
        private void OnGetGeoByPOIDistanceOperationCompleted(object arg) {
            if ((this.GetGeoByPOIDistanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGeoByPOIDistanceCompleted(this, new GetGeoByPOIDistanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GSAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckRegionByGeo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckRegionByGeo(float lng, float lat) {
            object[] results = this.Invoke("CheckRegionByGeo", new object[] {
                        lng,
                        lat});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckRegionByGeoAsync(float lng, float lat) {
            this.CheckRegionByGeoAsync(lng, lat, null);
        }
        
        /// <remarks/>
        public void CheckRegionByGeoAsync(float lng, float lat, object userState) {
            if ((this.CheckRegionByGeoOperationCompleted == null)) {
                this.CheckRegionByGeoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckRegionByGeoOperationCompleted);
            }
            this.InvokeAsync("CheckRegionByGeo", new object[] {
                        lng,
                        lat}, this.CheckRegionByGeoOperationCompleted, userState);
        }
        
        private void OnCheckRegionByGeoOperationCompleted(object arg) {
            if ((this.CheckRegionByGeoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckRegionByGeoCompleted(this, new CheckRegionByGeoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GSAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRegionByGeo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GSRegionResult GetRegionByGeo(float lng, float lat, string lan) {
            object[] results = this.Invoke("GetRegionByGeo", new object[] {
                        lng,
                        lat,
                        lan});
            return ((GSRegionResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetRegionByGeoAsync(float lng, float lat, string lan) {
            this.GetRegionByGeoAsync(lng, lat, lan, null);
        }
        
        /// <remarks/>
        public void GetRegionByGeoAsync(float lng, float lat, string lan, object userState) {
            if ((this.GetRegionByGeoOperationCompleted == null)) {
                this.GetRegionByGeoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegionByGeoOperationCompleted);
            }
            this.InvokeAsync("GetRegionByGeo", new object[] {
                        lng,
                        lat,
                        lan}, this.GetRegionByGeoOperationCompleted, userState);
        }
        
        private void OnGetRegionByGeoOperationCompleted(object arg) {
            if ((this.GetRegionByGeoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegionByGeoCompleted(this, new GetRegionByGeoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GSAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSpeedAlarm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GSSpeedResult GetSpeedAlarm(float lng, float lat, byte typ, string lan) {
            object[] results = this.Invoke("GetSpeedAlarm", new object[] {
                        lng,
                        lat,
                        typ,
                        lan});
            return ((GSSpeedResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetSpeedAlarmAsync(float lng, float lat, byte typ, string lan) {
            this.GetSpeedAlarmAsync(lng, lat, typ, lan, null);
        }
        
        /// <remarks/>
        public void GetSpeedAlarmAsync(float lng, float lat, byte typ, string lan, object userState) {
            if ((this.GetSpeedAlarmOperationCompleted == null)) {
                this.GetSpeedAlarmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSpeedAlarmOperationCompleted);
            }
            this.InvokeAsync("GetSpeedAlarm", new object[] {
                        lng,
                        lat,
                        typ,
                        lan}, this.GetSpeedAlarmOperationCompleted, userState);
        }
        
        private void OnGetSpeedAlarmOperationCompleted(object arg) {
            if ((this.GetSpeedAlarmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSpeedAlarmCompleted(this, new GetSpeedAlarmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GSAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSpeedAlarm2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GSSpeedResult[] GetSpeedAlarm2(string slng, string slat, byte typ, string lan) {
            object[] results = this.Invoke("GetSpeedAlarm2", new object[] {
                        slng,
                        slat,
                        typ,
                        lan});
            return ((GSSpeedResult[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSpeedAlarm2Async(string slng, string slat, byte typ, string lan) {
            this.GetSpeedAlarm2Async(slng, slat, typ, lan, null);
        }
        
        /// <remarks/>
        public void GetSpeedAlarm2Async(string slng, string slat, byte typ, string lan, object userState) {
            if ((this.GetSpeedAlarm2OperationCompleted == null)) {
                this.GetSpeedAlarm2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSpeedAlarm2OperationCompleted);
            }
            this.InvokeAsync("GetSpeedAlarm2", new object[] {
                        slng,
                        slat,
                        typ,
                        lan}, this.GetSpeedAlarm2OperationCompleted, userState);
        }
        
        private void OnGetSpeedAlarm2OperationCompleted(object arg) {
            if ((this.GetSpeedAlarm2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSpeedAlarm2Completed(this, new GetSpeedAlarm2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class GSAuthenticationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GSSpeedResult {
        
        private short districtIDField;
        
        private byte minSpeedField;
        
        private byte maxSpeedField;
        
        private short lyTrinhField;
        
        /// <remarks/>
        public short DistrictID {
            get {
                return this.districtIDField;
            }
            set {
                this.districtIDField = value;
            }
        }
        
        /// <remarks/>
        public byte MinSpeed {
            get {
                return this.minSpeedField;
            }
            set {
                this.minSpeedField = value;
            }
        }
        
        /// <remarks/>
        public byte MaxSpeed {
            get {
                return this.maxSpeedField;
            }
            set {
                this.maxSpeedField = value;
            }
        }
        
        /// <remarks/>
        public short LyTrinh {
            get {
                return this.lyTrinhField;
            }
            set {
                this.lyTrinhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GSRegionResult {
        
        private string communeNameField;
        
        private string districtNameField;
        
        private short provinceIDField;
        
        private string provinceNameField;
        
        /// <remarks/>
        public string CommuneName {
            get {
                return this.communeNameField;
            }
            set {
                this.communeNameField = value;
            }
        }
        
        /// <remarks/>
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
            }
        }
        
        /// <remarks/>
        public short ProvinceID {
            get {
                return this.provinceIDField;
            }
            set {
                this.provinceIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProvinceName {
            get {
                return this.provinceNameField;
            }
            set {
                this.provinceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GSPOIResult {
        
        private float lngField;
        
        private float latField;
        
        private string nameField;
        
        private string infoField;
        
        /// <remarks/>
        public float Lng {
            get {
                return this.lngField;
            }
            set {
                this.lngField = value;
            }
        }
        
        /// <remarks/>
        public float Lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GSAddressResult {
        
        private float lngField;
        
        private float latField;
        
        private short buildingField;
        
        private string roadField;
        
        private string communeField;
        
        private string districtField;
        
        private string provinceField;
        
        /// <remarks/>
        public float Lng {
            get {
                return this.lngField;
            }
            set {
                this.lngField = value;
            }
        }
        
        /// <remarks/>
        public float Lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        public short Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        public string Road {
            get {
                return this.roadField;
            }
            set {
                this.roadField = value;
            }
        }
        
        /// <remarks/>
        public string Commune {
            get {
                return this.communeField;
            }
            set {
                this.communeField = value;
            }
        }
        
        /// <remarks/>
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAddressByGeoCompletedEventHandler(object sender, GetAddressByGeoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAddressByGeoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAddressByGeoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GSAddressResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GSAddressResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAddressByGeo2CompletedEventHandler(object sender, GetAddressByGeo2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAddressByGeo2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAddressByGeo2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GSAddressResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GSAddressResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGeoByNameCompletedEventHandler(object sender, GetGeoByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGeoByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGeoByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GSAddressResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GSAddressResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGeoByName2CompletedEventHandler(object sender, GetGeoByName2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGeoByName2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGeoByName2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GSAddressResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GSAddressResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGeoByName3CompletedEventHandler(object sender, GetGeoByName3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGeoByName3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGeoByName3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GSAddressResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GSAddressResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGeoByNameHaNoiCompletedEventHandler(object sender, GetGeoByNameHaNoiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGeoByNameHaNoiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGeoByNameHaNoiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GSAddressResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GSAddressResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGeoByPOICompletedEventHandler(object sender, GetGeoByPOICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGeoByPOICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGeoByPOICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GSPOIResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GSPOIResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGeoByPOIDistanceCompletedEventHandler(object sender, GetGeoByPOIDistanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGeoByPOIDistanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGeoByPOIDistanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GSPOIResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GSPOIResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CheckRegionByGeoCompletedEventHandler(object sender, CheckRegionByGeoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckRegionByGeoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckRegionByGeoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRegionByGeoCompletedEventHandler(object sender, GetRegionByGeoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegionByGeoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegionByGeoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GSRegionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GSRegionResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSpeedAlarmCompletedEventHandler(object sender, GetSpeedAlarmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSpeedAlarmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSpeedAlarmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GSSpeedResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GSSpeedResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSpeedAlarm2CompletedEventHandler(object sender, GetSpeedAlarm2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSpeedAlarm2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSpeedAlarm2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GSSpeedResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GSSpeedResult[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591