using Staxi.Utils.Attributes;

namespace OneTaxi.Utils.Enums
{
    public enum EnumKeys:int
    {
        [FieldInfo(Name ="None")]
        None = 0,
        [FieldInfo(Name ="0")]
        D0 = 48,
        [FieldInfo(Name ="1")]
        D1 = 49,
        [FieldInfo(Name ="2")]
        D2 = 50,
        [FieldInfo(Name ="3")]
        D3 = 51,
        [FieldInfo(Name ="4")]
        D4 = 52,
        [FieldInfo(Name ="5")]
        D5 = 53,
        [FieldInfo(Name ="6")]
        D6 = 54,
        [FieldInfo(Name ="7")]
        D7 = 55,
        [FieldInfo(Name ="8")]
        D8 = 56,
        [FieldInfo(Name ="9")]
        D9 = 57,
        [FieldInfo(Name ="A")]
        A = 65,
        [FieldInfo(Name ="B")]
        B = 66,
        [FieldInfo(Name ="C")]
        C = 67,
        [FieldInfo(Name ="D")]
        D = 68,
        [FieldInfo(Name ="E")]
        E = 69,
        [FieldInfo(Name ="F")]
        F = 70,
        [FieldInfo(Name ="G")]
        G = 71,
        [FieldInfo(Name ="H")]
        H = 72,
        [FieldInfo(Name ="I")]
        I = 73,
        [FieldInfo(Name ="J")]
        J = 74,
        [FieldInfo(Name ="K")]
        K = 75,
        [FieldInfo(Name ="L")]
        L = 76,
        [FieldInfo(Name ="M")]
        M = 77,
        [FieldInfo(Name ="N")]
        N = 78,
        [FieldInfo(Name ="O")]
        O = 79,
        [FieldInfo(Name ="P")]
        P = 80,
        [FieldInfo(Name ="Q")]
        Q = 81,
        [FieldInfo(Name ="R")]
        R = 82,
        [FieldInfo(Name ="S")]
        S = 83,
        [FieldInfo(Name ="T")]
        T = 84,
        [FieldInfo(Name ="U")]
        U = 85,
        [FieldInfo(Name ="V")]
        V = 86,
        [FieldInfo(Name ="W")]
        W = 87,
        [FieldInfo(Name ="X")]
        X = 88,
        [FieldInfo(Name ="Y")]
        Y = 89,
        [FieldInfo(Name ="Z")]
        Z = 90,
        [FieldInfo(Name ="[-]")]
        Multiply = 106,
        [FieldInfo(Name ="[+]")]
        Add = 107,
        [FieldInfo(Name ="[,]")]
        Separator = 108,
        [FieldInfo(Name ="[*]")]
        Subtract = 109,
        [FieldInfo(Name ="[.]")]
        Decimal = 110,
        [FieldInfo(Name ="[/]")]
        Divide = 111,
        [FieldInfo(Name ="F1")]
        F1 = 112,
        [FieldInfo(Name ="F1")]
        F2 = 113,
        [FieldInfo(Name ="F3")]
        F3 = 114,
        [FieldInfo(Name ="F4")]
        F4 = 115,
        [FieldInfo(Name ="F5")]
        F5 = 116,
        [FieldInfo(Name ="F6")]
        F6 = 117,
        [FieldInfo(Name ="F7")]
        F7 = 118,
        [FieldInfo(Name ="F8")]
        F8 = 119,
        [FieldInfo(Name ="F9")]
        F9 = 120,
        [FieldInfo(Name ="F10")]
        F10 = 121,
        [FieldInfo(Name ="F11")]
        F11 = 122,
        [FieldInfo(Name ="F12")]
        F12 = 123,
        [FieldInfo(Name ="Backspace")]
        Backspace = 8,
        [FieldInfo(Name ="Delete")]
        Delete = 46
    }
}
