//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi.Services.BAGIS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BAGIS.gisSoap")]
    public interface gisSoap {
        
        // CODEGEN: Generating message contract since message GetAddressByGeoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddressByGeo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetAddressByGeoResponse GetAddressByGeo(Taxi.Services.BAGIS.GetAddressByGeoRequest request);
        
        // CODEGEN: Generating message contract since message GetAddressByGeo2Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddressByGeo2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetAddressByGeo2Response GetAddressByGeo2(Taxi.Services.BAGIS.GetAddressByGeo2Request request);
        
        // CODEGEN: Generating message contract since message GetAddressByGeo3Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddressByGeo3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetAddressByGeo3Response GetAddressByGeo3(Taxi.Services.BAGIS.GetAddressByGeo3Request request);
        
        // CODEGEN: Generating message contract since message GetGeoByPOIVinhomeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGeoByPOIVinhome", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetGeoByPOIVinhomeResponse GetGeoByPOIVinhome(Taxi.Services.BAGIS.GetGeoByPOIVinhomeRequest request);
        
        // CODEGEN: Generating message contract since message GetGeoByNameRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGeoByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetGeoByNameResponse GetGeoByName(Taxi.Services.BAGIS.GetGeoByNameRequest request);
        
        // CODEGEN: Generating message contract since message GetGeoByName2Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGeoByName2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetGeoByName2Response GetGeoByName2(Taxi.Services.BAGIS.GetGeoByName2Request request);
        
        // CODEGEN: Generating message contract since message GetGeoByName3Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGeoByName3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetGeoByName3Response GetGeoByName3(Taxi.Services.BAGIS.GetGeoByName3Request request);
        
        // CODEGEN: Generating message contract since message GetGeoByNameHaNoiRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGeoByNameHaNoi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetGeoByNameHaNoiResponse GetGeoByNameHaNoi(Taxi.Services.BAGIS.GetGeoByNameHaNoiRequest request);
        
        // CODEGEN: Generating message contract since message GetGeoByPOIRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGeoByPOI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetGeoByPOIResponse GetGeoByPOI(Taxi.Services.BAGIS.GetGeoByPOIRequest request);
        
        // CODEGEN: Generating message contract since message GetGeoByPOIDistanceRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGeoByPOIDistance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetGeoByPOIDistanceResponse GetGeoByPOIDistance(Taxi.Services.BAGIS.GetGeoByPOIDistanceRequest request);
        
        // CODEGEN: Generating message contract since message CheckRegionByGeoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckRegionByGeo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.CheckRegionByGeoResponse CheckRegionByGeo(Taxi.Services.BAGIS.CheckRegionByGeoRequest request);
        
        // CODEGEN: Generating message contract since message GetRegionByGeoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRegionByGeo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetRegionByGeoResponse GetRegionByGeo(Taxi.Services.BAGIS.GetRegionByGeoRequest request);
        
        // CODEGEN: Generating message contract since message GetSpeedAlarmRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpeedAlarm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetSpeedAlarmResponse GetSpeedAlarm(Taxi.Services.BAGIS.GetSpeedAlarmRequest request);
        
        // CODEGEN: Generating message contract since message GetSpeedAlarm2Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpeedAlarm2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Taxi.Services.BAGIS.GetSpeedAlarm2Response GetSpeedAlarm2(Taxi.Services.BAGIS.GetSpeedAlarm2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GSAuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GSSpeedResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short districtIDField;
        
        private byte minSpeedField;
        
        private byte maxSpeedField;
        
        private short lyTrinhField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short DistrictID {
            get {
                return this.districtIDField;
            }
            set {
                this.districtIDField = value;
                this.RaisePropertyChanged("DistrictID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public byte MinSpeed {
            get {
                return this.minSpeedField;
            }
            set {
                this.minSpeedField = value;
                this.RaisePropertyChanged("MinSpeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public byte MaxSpeed {
            get {
                return this.maxSpeedField;
            }
            set {
                this.maxSpeedField = value;
                this.RaisePropertyChanged("MaxSpeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short LyTrinh {
            get {
                return this.lyTrinhField;
            }
            set {
                this.lyTrinhField = value;
                this.RaisePropertyChanged("LyTrinh");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GSRegionResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string communeNameField;
        
        private string districtNameField;
        
        private short provinceIDField;
        
        private string provinceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CommuneName {
            get {
                return this.communeNameField;
            }
            set {
                this.communeNameField = value;
                this.RaisePropertyChanged("CommuneName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
                this.RaisePropertyChanged("DistrictName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public short ProvinceID {
            get {
                return this.provinceIDField;
            }
            set {
                this.provinceIDField = value;
                this.RaisePropertyChanged("ProvinceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ProvinceName {
            get {
                return this.provinceNameField;
            }
            set {
                this.provinceNameField = value;
                this.RaisePropertyChanged("ProvinceName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GSPOIResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float lngField;
        
        private float latField;
        
        private string nameField;
        
        private string infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float Lng {
            get {
                return this.lngField;
            }
            set {
                this.lngField = value;
                this.RaisePropertyChanged("Lng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
                this.RaisePropertyChanged("Lat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("Info");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GSAddressResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float lngField;
        
        private float latField;
        
        private short buildingField;
        
        private string roadField;
        
        private string communeField;
        
        private string districtField;
        
        private string provinceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float Lng {
            get {
                return this.lngField;
            }
            set {
                this.lngField = value;
                this.RaisePropertyChanged("Lng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
                this.RaisePropertyChanged("Lat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public short Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
                this.RaisePropertyChanged("Building");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Road {
            get {
                return this.roadField;
            }
            set {
                this.roadField = value;
                this.RaisePropertyChanged("Road");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Commune {
            get {
                return this.communeField;
            }
            set {
                this.communeField = value;
                this.RaisePropertyChanged("Commune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("District");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("Province");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddressByGeo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAddressByGeoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public float lng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public float lat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string lan;
        
        public GetAddressByGeoRequest() {
        }
        
        public GetAddressByGeoRequest(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, float lng, float lat, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.lng = lng;
            this.lat = lat;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddressByGeoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAddressByGeoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSAddressResult GetAddressByGeoResult;
        
        public GetAddressByGeoResponse() {
        }
        
        public GetAddressByGeoResponse(Taxi.Services.BAGIS.GSAddressResult GetAddressByGeoResult) {
            this.GetAddressByGeoResult = GetAddressByGeoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddressByGeo2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAddressByGeo2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string slng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string slat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string lan;
        
        public GetAddressByGeo2Request() {
        }
        
        public GetAddressByGeo2Request(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string slng, string slat, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.slng = slng;
            this.slat = slat;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddressByGeo2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAddressByGeo2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSAddressResult[] GetAddressByGeo2Result;
        
        public GetAddressByGeo2Response() {
        }
        
        public GetAddressByGeo2Response(Taxi.Services.BAGIS.GSAddressResult[] GetAddressByGeo2Result) {
            this.GetAddressByGeo2Result = GetAddressByGeo2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddressByGeo3", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAddressByGeo3Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public float lng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public float lat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string lan;
        
        public GetAddressByGeo3Request() {
        }
        
        public GetAddressByGeo3Request(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, float lng, float lat, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.lng = lng;
            this.lat = lat;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddressByGeo3Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAddressByGeo3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSAddressResult GetAddressByGeo3Result;
        
        public GetAddressByGeo3Response() {
        }
        
        public GetAddressByGeo3Response(Taxi.Services.BAGIS.GSAddressResult GetAddressByGeo3Result) {
            this.GetAddressByGeo3Result = GetAddressByGeo3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByPOIVinhome", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByPOIVinhomeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public float lng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public float lat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string lan;
        
        public GetGeoByPOIVinhomeRequest() {
        }
        
        public GetGeoByPOIVinhomeRequest(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, float lng, float lat, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.lng = lng;
            this.lat = lat;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByPOIVinhomeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByPOIVinhomeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSPOIResult GetGeoByPOIVinhomeResult;
        
        public GetGeoByPOIVinhomeResponse() {
        }
        
        public GetGeoByPOIVinhomeResponse(Taxi.Services.BAGIS.GSPOIResult GetGeoByPOIVinhomeResult) {
            this.GetGeoByPOIVinhomeResult = GetGeoByPOIVinhomeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByNameRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int prv;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string lan;
        
        public GetGeoByNameRequest() {
        }
        
        public GetGeoByNameRequest(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, int prv, string key, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.prv = prv;
            this.key = key;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSAddressResult GetGeoByNameResult;
        
        public GetGeoByNameResponse() {
        }
        
        public GetGeoByNameResponse(Taxi.Services.BAGIS.GSAddressResult GetGeoByNameResult) {
            this.GetGeoByNameResult = GetGeoByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByName2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByName2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lan;
        
        public GetGeoByName2Request() {
        }
        
        public GetGeoByName2Request(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string key, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.key = key;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByName2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByName2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSAddressResult GetGeoByName2Result;
        
        public GetGeoByName2Response() {
        }
        
        public GetGeoByName2Response(Taxi.Services.BAGIS.GSAddressResult GetGeoByName2Result) {
            this.GetGeoByName2Result = GetGeoByName2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByName3", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByName3Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lan;
        
        public GetGeoByName3Request() {
        }
        
        public GetGeoByName3Request(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string key, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.key = key;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByName3Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByName3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSAddressResult GetGeoByName3Result;
        
        public GetGeoByName3Response() {
        }
        
        public GetGeoByName3Response(Taxi.Services.BAGIS.GSAddressResult GetGeoByName3Result) {
            this.GetGeoByName3Result = GetGeoByName3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByNameHaNoi", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByNameHaNoiRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lan;
        
        public GetGeoByNameHaNoiRequest() {
        }
        
        public GetGeoByNameHaNoiRequest(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string key, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.key = key;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByNameHaNoiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByNameHaNoiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSAddressResult GetGeoByNameHaNoiResult;
        
        public GetGeoByNameHaNoiResponse() {
        }
        
        public GetGeoByNameHaNoiResponse(Taxi.Services.BAGIS.GSAddressResult GetGeoByNameHaNoiResult) {
            this.GetGeoByNameHaNoiResult = GetGeoByNameHaNoiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByPOI", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByPOIRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lan;
        
        public GetGeoByPOIRequest() {
        }
        
        public GetGeoByPOIRequest(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string key, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.key = key;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByPOIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByPOIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSPOIResult GetGeoByPOIResult;
        
        public GetGeoByPOIResponse() {
        }
        
        public GetGeoByPOIResponse(Taxi.Services.BAGIS.GSPOIResult GetGeoByPOIResult) {
            this.GetGeoByPOIResult = GetGeoByPOIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByPOIDistance", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByPOIDistanceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public float lng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public float lat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int dis;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string lan;
        
        public GetGeoByPOIDistanceRequest() {
        }
        
        public GetGeoByPOIDistanceRequest(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string key, float lng, float lat, int dis, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.key = key;
            this.lng = lng;
            this.lat = lat;
            this.dis = dis;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeoByPOIDistanceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGeoByPOIDistanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSPOIResult GetGeoByPOIDistanceResult;
        
        public GetGeoByPOIDistanceResponse() {
        }
        
        public GetGeoByPOIDistanceResponse(Taxi.Services.BAGIS.GSPOIResult GetGeoByPOIDistanceResult) {
            this.GetGeoByPOIDistanceResult = GetGeoByPOIDistanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRegionByGeo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckRegionByGeoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public float lng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public float lat;
        
        public CheckRegionByGeoRequest() {
        }
        
        public CheckRegionByGeoRequest(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, float lng, float lat) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.lng = lng;
            this.lat = lat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRegionByGeoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckRegionByGeoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CheckRegionByGeoResult;
        
        public CheckRegionByGeoResponse() {
        }
        
        public CheckRegionByGeoResponse(bool CheckRegionByGeoResult) {
            this.CheckRegionByGeoResult = CheckRegionByGeoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRegionByGeo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRegionByGeoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public float lng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public float lat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string lan;
        
        public GetRegionByGeoRequest() {
        }
        
        public GetRegionByGeoRequest(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, float lng, float lat, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.lng = lng;
            this.lat = lat;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRegionByGeoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRegionByGeoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSRegionResult GetRegionByGeoResult;
        
        public GetRegionByGeoResponse() {
        }
        
        public GetRegionByGeoResponse(Taxi.Services.BAGIS.GSRegionResult GetRegionByGeoResult) {
            this.GetRegionByGeoResult = GetRegionByGeoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSpeedAlarm", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSpeedAlarmRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public float lng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public float lat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte typ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string lan;
        
        public GetSpeedAlarmRequest() {
        }
        
        public GetSpeedAlarmRequest(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, float lng, float lat, byte typ, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.lng = lng;
            this.lat = lat;
            this.typ = typ;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSpeedAlarmResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSpeedAlarmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSSpeedResult GetSpeedAlarmResult;
        
        public GetSpeedAlarmResponse() {
        }
        
        public GetSpeedAlarmResponse(Taxi.Services.BAGIS.GSSpeedResult GetSpeedAlarmResult) {
            this.GetSpeedAlarmResult = GetSpeedAlarmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSpeedAlarm2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSpeedAlarm2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string slng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string slat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte typ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string lan;
        
        public GetSpeedAlarm2Request() {
        }
        
        public GetSpeedAlarm2Request(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string slng, string slat, byte typ, string lan) {
            this.GSAuthenticationHeader = GSAuthenticationHeader;
            this.slng = slng;
            this.slat = slat;
            this.typ = typ;
            this.lan = lan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSpeedAlarm2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSpeedAlarm2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Taxi.Services.BAGIS.GSSpeedResult[] GetSpeedAlarm2Result;
        
        public GetSpeedAlarm2Response() {
        }
        
        public GetSpeedAlarm2Response(Taxi.Services.BAGIS.GSSpeedResult[] GetSpeedAlarm2Result) {
            this.GetSpeedAlarm2Result = GetSpeedAlarm2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface gisSoapChannel : Taxi.Services.BAGIS.gisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class gisSoapClient : System.ServiceModel.ClientBase<Taxi.Services.BAGIS.gisSoap>, Taxi.Services.BAGIS.gisSoap {
        
        public gisSoapClient() {
        }
        
        public gisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public gisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public gisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public gisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetAddressByGeoResponse Taxi.Services.BAGIS.gisSoap.GetAddressByGeo(Taxi.Services.BAGIS.GetAddressByGeoRequest request) {
            return base.Channel.GetAddressByGeo(request);
        }
        
        public Taxi.Services.BAGIS.GSAddressResult GetAddressByGeo(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, float lng, float lat, string lan) {
            Taxi.Services.BAGIS.GetAddressByGeoRequest inValue = new Taxi.Services.BAGIS.GetAddressByGeoRequest();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.lng = lng;
            inValue.lat = lat;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetAddressByGeoResponse retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetAddressByGeo(inValue);
            return retVal.GetAddressByGeoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetAddressByGeo2Response Taxi.Services.BAGIS.gisSoap.GetAddressByGeo2(Taxi.Services.BAGIS.GetAddressByGeo2Request request) {
            return base.Channel.GetAddressByGeo2(request);
        }
        
        public Taxi.Services.BAGIS.GSAddressResult[] GetAddressByGeo2(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string slng, string slat, string lan) {
            Taxi.Services.BAGIS.GetAddressByGeo2Request inValue = new Taxi.Services.BAGIS.GetAddressByGeo2Request();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.slng = slng;
            inValue.slat = slat;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetAddressByGeo2Response retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetAddressByGeo2(inValue);
            return retVal.GetAddressByGeo2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetAddressByGeo3Response Taxi.Services.BAGIS.gisSoap.GetAddressByGeo3(Taxi.Services.BAGIS.GetAddressByGeo3Request request) {
            return base.Channel.GetAddressByGeo3(request);
        }
        
        public Taxi.Services.BAGIS.GSAddressResult GetAddressByGeo3(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, float lng, float lat, string lan) {
            Taxi.Services.BAGIS.GetAddressByGeo3Request inValue = new Taxi.Services.BAGIS.GetAddressByGeo3Request();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.lng = lng;
            inValue.lat = lat;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetAddressByGeo3Response retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetAddressByGeo3(inValue);
            return retVal.GetAddressByGeo3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetGeoByPOIVinhomeResponse Taxi.Services.BAGIS.gisSoap.GetGeoByPOIVinhome(Taxi.Services.BAGIS.GetGeoByPOIVinhomeRequest request) {
            return base.Channel.GetGeoByPOIVinhome(request);
        }
        
        public Taxi.Services.BAGIS.GSPOIResult GetGeoByPOIVinhome(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, float lng, float lat, string lan) {
            Taxi.Services.BAGIS.GetGeoByPOIVinhomeRequest inValue = new Taxi.Services.BAGIS.GetGeoByPOIVinhomeRequest();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.lng = lng;
            inValue.lat = lat;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetGeoByPOIVinhomeResponse retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetGeoByPOIVinhome(inValue);
            return retVal.GetGeoByPOIVinhomeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetGeoByNameResponse Taxi.Services.BAGIS.gisSoap.GetGeoByName(Taxi.Services.BAGIS.GetGeoByNameRequest request) {
            return base.Channel.GetGeoByName(request);
        }
        
        public Taxi.Services.BAGIS.GSAddressResult GetGeoByName(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, int prv, string key, string lan) {
            Taxi.Services.BAGIS.GetGeoByNameRequest inValue = new Taxi.Services.BAGIS.GetGeoByNameRequest();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.prv = prv;
            inValue.key = key;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetGeoByNameResponse retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetGeoByName(inValue);
            return retVal.GetGeoByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetGeoByName2Response Taxi.Services.BAGIS.gisSoap.GetGeoByName2(Taxi.Services.BAGIS.GetGeoByName2Request request) {
            return base.Channel.GetGeoByName2(request);
        }
        
        public Taxi.Services.BAGIS.GSAddressResult GetGeoByName2(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string key, string lan) {
            Taxi.Services.BAGIS.GetGeoByName2Request inValue = new Taxi.Services.BAGIS.GetGeoByName2Request();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.key = key;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetGeoByName2Response retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetGeoByName2(inValue);
            return retVal.GetGeoByName2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetGeoByName3Response Taxi.Services.BAGIS.gisSoap.GetGeoByName3(Taxi.Services.BAGIS.GetGeoByName3Request request) {
            return base.Channel.GetGeoByName3(request);
        }
        
        public Taxi.Services.BAGIS.GSAddressResult GetGeoByName3(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string key, string lan) {
            Taxi.Services.BAGIS.GetGeoByName3Request inValue = new Taxi.Services.BAGIS.GetGeoByName3Request();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.key = key;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetGeoByName3Response retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetGeoByName3(inValue);
            return retVal.GetGeoByName3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetGeoByNameHaNoiResponse Taxi.Services.BAGIS.gisSoap.GetGeoByNameHaNoi(Taxi.Services.BAGIS.GetGeoByNameHaNoiRequest request) {
            return base.Channel.GetGeoByNameHaNoi(request);
        }
        
        public Taxi.Services.BAGIS.GSAddressResult GetGeoByNameHaNoi(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string key, string lan) {
            Taxi.Services.BAGIS.GetGeoByNameHaNoiRequest inValue = new Taxi.Services.BAGIS.GetGeoByNameHaNoiRequest();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.key = key;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetGeoByNameHaNoiResponse retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetGeoByNameHaNoi(inValue);
            return retVal.GetGeoByNameHaNoiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetGeoByPOIResponse Taxi.Services.BAGIS.gisSoap.GetGeoByPOI(Taxi.Services.BAGIS.GetGeoByPOIRequest request) {
            return base.Channel.GetGeoByPOI(request);
        }
        
        public Taxi.Services.BAGIS.GSPOIResult GetGeoByPOI(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string key, string lan) {
            Taxi.Services.BAGIS.GetGeoByPOIRequest inValue = new Taxi.Services.BAGIS.GetGeoByPOIRequest();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.key = key;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetGeoByPOIResponse retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetGeoByPOI(inValue);
            return retVal.GetGeoByPOIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetGeoByPOIDistanceResponse Taxi.Services.BAGIS.gisSoap.GetGeoByPOIDistance(Taxi.Services.BAGIS.GetGeoByPOIDistanceRequest request) {
            return base.Channel.GetGeoByPOIDistance(request);
        }
        
        public Taxi.Services.BAGIS.GSPOIResult GetGeoByPOIDistance(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string key, float lng, float lat, int dis, string lan) {
            Taxi.Services.BAGIS.GetGeoByPOIDistanceRequest inValue = new Taxi.Services.BAGIS.GetGeoByPOIDistanceRequest();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.key = key;
            inValue.lng = lng;
            inValue.lat = lat;
            inValue.dis = dis;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetGeoByPOIDistanceResponse retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetGeoByPOIDistance(inValue);
            return retVal.GetGeoByPOIDistanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.CheckRegionByGeoResponse Taxi.Services.BAGIS.gisSoap.CheckRegionByGeo(Taxi.Services.BAGIS.CheckRegionByGeoRequest request) {
            return base.Channel.CheckRegionByGeo(request);
        }
        
        public bool CheckRegionByGeo(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, float lng, float lat) {
            Taxi.Services.BAGIS.CheckRegionByGeoRequest inValue = new Taxi.Services.BAGIS.CheckRegionByGeoRequest();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.lng = lng;
            inValue.lat = lat;
            Taxi.Services.BAGIS.CheckRegionByGeoResponse retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).CheckRegionByGeo(inValue);
            return retVal.CheckRegionByGeoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetRegionByGeoResponse Taxi.Services.BAGIS.gisSoap.GetRegionByGeo(Taxi.Services.BAGIS.GetRegionByGeoRequest request) {
            return base.Channel.GetRegionByGeo(request);
        }
        
        public Taxi.Services.BAGIS.GSRegionResult GetRegionByGeo(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, float lng, float lat, string lan) {
            Taxi.Services.BAGIS.GetRegionByGeoRequest inValue = new Taxi.Services.BAGIS.GetRegionByGeoRequest();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.lng = lng;
            inValue.lat = lat;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetRegionByGeoResponse retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetRegionByGeo(inValue);
            return retVal.GetRegionByGeoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetSpeedAlarmResponse Taxi.Services.BAGIS.gisSoap.GetSpeedAlarm(Taxi.Services.BAGIS.GetSpeedAlarmRequest request) {
            return base.Channel.GetSpeedAlarm(request);
        }
        
        public Taxi.Services.BAGIS.GSSpeedResult GetSpeedAlarm(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, float lng, float lat, byte typ, string lan) {
            Taxi.Services.BAGIS.GetSpeedAlarmRequest inValue = new Taxi.Services.BAGIS.GetSpeedAlarmRequest();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.lng = lng;
            inValue.lat = lat;
            inValue.typ = typ;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetSpeedAlarmResponse retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetSpeedAlarm(inValue);
            return retVal.GetSpeedAlarmResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Taxi.Services.BAGIS.GetSpeedAlarm2Response Taxi.Services.BAGIS.gisSoap.GetSpeedAlarm2(Taxi.Services.BAGIS.GetSpeedAlarm2Request request) {
            return base.Channel.GetSpeedAlarm2(request);
        }
        
        public Taxi.Services.BAGIS.GSSpeedResult[] GetSpeedAlarm2(Taxi.Services.BAGIS.GSAuthenticationHeader GSAuthenticationHeader, string slng, string slat, byte typ, string lan) {
            Taxi.Services.BAGIS.GetSpeedAlarm2Request inValue = new Taxi.Services.BAGIS.GetSpeedAlarm2Request();
            inValue.GSAuthenticationHeader = GSAuthenticationHeader;
            inValue.slng = slng;
            inValue.slat = slat;
            inValue.typ = typ;
            inValue.lan = lan;
            Taxi.Services.BAGIS.GetSpeedAlarm2Response retVal = ((Taxi.Services.BAGIS.gisSoap)(this)).GetSpeedAlarm2(inValue);
            return retVal.GetSpeedAlarm2Result;
        }
    }
}
