using System;
using System.Collections.Generic;
using System.Threading;
using Taxi.Business;
using Taxi.Controls.Base;
using Taxi.Controls.Base.Common;
using Taxi.Data.FastTaxi;
using Taxi.Utils;

namespace Taxi.Controls.FastTaxis.TaxiDieuXe
{
    public partial class frmTestThemMoi : FormBase
    {
        public frmTestThemMoi()
        {
            InitializeComponent();
        }

        private AutoCompleteAddress _diachi = new AutoCompleteAddress();
        private void btnLuu_Click(object sender, EventArgs e)
        {
            var m = new Booking();
            m.PK_BooID = this.GenerateRandomNumber(int.MaxValue);
            m.FromTime = deStart.DateTime;
            m.ToTime = deEnd.DateTime;
            m.Mobile = txtSoDT.Text;
            m.ToAdress = txtDiaChiTra.Text;
            m.ToName = txtDiemTra.Text;
            m.FromAddress = txtDiaChiDon.Text;
            m.FromName = txtDiemDon.Text;
            m.CreatedDate = DieuHanhTaxi.GetTimeServer();
            m.OpAcceptedTime = DieuHanhTaxi.GetTimeServer();
            m.OpAcceptedUser = ThongTinDangNhap.USER_ID;
            m.OpStatus = 0;
            m.Description = txtGhiChu.Text;
            m.Save();
            for (int i = 0; i < 4; i++)// Khởi tạo nhẫu nhiên 3 cuốc
            {
                var id = this.GenerateRandomNumber(0, 99);
                var id2 = this.GenerateRandomNumber(0, 8);
                var dateStart = DateTime.Now.AddMinutes(id);
                var dateEnd = dateStart.AddHours(id2).AddMinutes(id2).AddSeconds(id).AddSeconds(id2);
                XeDiDuongDai xedi = new XeDiDuongDai();
                xedi.ThoiDiemDi = dateStart;
                xedi.ThoiDiemVe = dateEnd;
                xedi.TGDuKien = dateEnd;
                xedi.Line = 1;
                {
                    do
                    {
                        xedi.SoDienThoai = RandomMobi();

                    } while (xedi.CheckSoDienThoai(xedi.SoDienThoai));

                }
                {
                    
                    xedi.DiaDiemDen = RanDomDiaChi();
                    _diachi.Text = xedi.DiaDiemDen;
                    _diachi.ReSearch();
                    xedi.FK_QuanHuyenDenID = _diachi.HuyenId;
                    xedi.FK_TinhThanhDenID = _diachi.TinhId;
                }

                {
                    xedi.DiaDiemDi = RanDomDiaChi();
                    _diachi.Text = xedi.DiaDiemDi;
                    _diachi.ReSearch();
                    xedi.FK_QuanHuyenDiID = _diachi.HuyenId;
                    xedi.FK_TinhThanhDiID = _diachi.TinhId;}
                {
                    do
                    {
                        var xe=RanDomLaiXe();
                        xedi.FK_SoHieuXe = xe.Key;
                        xedi.BienSoXe = xe.Value;
                    } while (xedi.CheckXeChuaKetThucDuongDai(xedi.FK_SoHieuXe));

                }
                xedi.TrangThai =(int)Taxi.Utils.Enums.Enum_XeBaoDiDuongDai_TrangThai.ChoGhepKhach;
                xedi.TenLaiXe = RanDomTen();
                xedi.CreatedDate = DieuHanhTaxi.GetTimeServer();
                xedi.CreatedByUser = ThongTinDangNhap.USER_ID;
                xedi.Insert();
                BookingsDetail de = new BookingsDetail();
                de.FK_BookID = m.PK_BooID;
                de.TripID = xedi.ID;
                de.DateUpdated = DateTime.Now;
                de.CompanyID = ThongTinCauHinh.CompanyID;
                de.Insert();
                //Taxi.Controls.FastTaxis.TaxiChieuVe.TaxiReturn_Process.AddTripProcess(xedi);
                //System.Threading.Thread.Sleep(10);
            }
            this.Close();
        }

        private void frmTestThemMoi_Load(object sender, System.EventArgs e)
        {

            deStart.EditValue = DieuHanhTaxi.GetTimeServer();
            deEnd.EditValue = DieuHanhTaxi.GetTimeServer().AddMinutes(new Random().Next(10, 100));
            txtSoDT.Text = RandomMobi();
            txtDiaChiTra.Text = RanDomDiaChi();
            txtDiemTra.Text = "Điểm 1," + txtDiaChiTra.Text;
            txtDiaChiDon.Text = RanDomDiaChi();
            txtDiemDon.Text = "Điểm 2," + txtDiaChiDon.Text;
        }


        #region Test Xe đi chiều về
        /// <summary>
        /// Khởi tạo ngẫu nhiên số điện thoại
        /// </summary>
        /// <returns></returns>
        private string RandomMobi()
        {
            return "0164" + this.GenerateRandomNumber(10, 99).ToString() + this.GenerateRandomNumber(10, 99).ToString() + this.GenerateRandomNumber(10, 99).ToString() + this.GenerateRandomNumber(0, 9).ToString();
        }
        /// <summary>
        /// khởi tạo số xe trong danh sách lái xe.
        /// để tạo ra luôn có số xe trong hệ thống.
        /// </summary>
        /// <returns></returns>
        private KeyValuePair<string,string> RanDomLaiXe()
        {
            if (laixe == null)
            {
                laixe = new List<KeyValuePair<string, string>>();
                #region Lái Xe
                laixe.Add(new KeyValuePair<string, string>("01", "29A74940"));
                laixe.Add(new KeyValuePair<string, string>("02", "30A43784"));
                laixe.Add(new KeyValuePair<string, string>("03", "30A19790"));
                laixe.Add(new KeyValuePair<string, string>("04", "30L5708"));
                laixe.Add(new KeyValuePair<string, string>("05", "30A16273"));
                laixe.Add(new KeyValuePair<string, string>("06", "29A20402"));
                laixe.Add(new KeyValuePair<string, string>("07", "29A18733"));
                laixe.Add(new KeyValuePair<string, string>("08", "30A26378"));
                laixe.Add(new KeyValuePair<string, string>("09", "29A20401"));
                laixe.Add(new KeyValuePair<string, string>("10", "29A21612"));
                laixe.Add(new KeyValuePair<string, string>("100", "30A43768"));
                laixe.Add(new KeyValuePair<string, string>("101", "30A30091"));
                laixe.Add(new KeyValuePair<string, string>("102", "29A56186"));
                laixe.Add(new KeyValuePair<string, string>("103", "30V0202"));
                laixe.Add(new KeyValuePair<string, string>("104", "30V0677"));
                laixe.Add(new KeyValuePair<string, string>("105", "30A43930"));
                laixe.Add(new KeyValuePair<string, string>("106", "30V0938"));
                laixe.Add(new KeyValuePair<string, string>("108", "30A09541"));
                laixe.Add(new KeyValuePair<string, string>("109", "29A26512"));
                laixe.Add(new KeyValuePair<string, string>("11", "30A61695"));
                laixe.Add(new KeyValuePair<string, string>("110", "31F0063"));
                laixe.Add(new KeyValuePair<string, string>("112", "30A40213"));
                laixe.Add(new KeyValuePair<string, string>("113", "29A24533"));
                laixe.Add(new KeyValuePair<string, string>("114", "30Z7520"));
                laixe.Add(new KeyValuePair<string, string>("116", "29A90561"));
                laixe.Add(new KeyValuePair<string, string>("117", "30Z7038"));
                laixe.Add(new KeyValuePair<string, string>("118", "30A16255"));
                laixe.Add(new KeyValuePair<string, string>("119", "30Z7722"));
                laixe.Add(new KeyValuePair<string, string>("12", "30A16256"));
                laixe.Add(new KeyValuePair<string, string>("120", "30A16792"));
                laixe.Add(new KeyValuePair<string, string>("121", "30T2574"));
                laixe.Add(new KeyValuePair<string, string>("122", "30A61668"));
                laixe.Add(new KeyValuePair<string, string>("123.", "30A09603"));
                laixe.Add(new KeyValuePair<string, string>("124", "30Y2345"));
                laixe.Add(new KeyValuePair<string, string>("125", "29A54129"));
                laixe.Add(new KeyValuePair<string, string>("126", "29A77618"));
                laixe.Add(new KeyValuePair<string, string>("127", "29A10455"));
                laixe.Add(new KeyValuePair<string, string>("128", "30L5858"));
                laixe.Add(new KeyValuePair<string, string>("129", "30T2155"));
                laixe.Add(new KeyValuePair<string, string>("130", "29A22354"));
                laixe.Add(new KeyValuePair<string, string>("131", "30Z7491"));
                laixe.Add(new KeyValuePair<string, string>("132", "30A43792"));
                laixe.Add(new KeyValuePair<string, string>("133", "30A46590"));
                laixe.Add(new KeyValuePair<string, string>("135", "30A26307"));
                laixe.Add(new KeyValuePair<string, string>("136", "29A95724"));
                laixe.Add(new KeyValuePair<string, string>("137", "30Z7410"));
                laixe.Add(new KeyValuePair<string, string>("138", "30L5591"));
                laixe.Add(new KeyValuePair<string, string>("139", "29A74269"));
                laixe.Add(new KeyValuePair<string, string>("14", "30L5577"));
                laixe.Add(new KeyValuePair<string, string>("140", "31F0483"));
                laixe.Add(new KeyValuePair<string, string>("141", "31F0724"));
                laixe.Add(new KeyValuePair<string, string>("142", "29A82019"));
                laixe.Add(new KeyValuePair<string, string>("144", "30A19078"));
                laixe.Add(new KeyValuePair<string, string>("148", "29A43453"));
                laixe.Add(new KeyValuePair<string, string>("149", "29A54183"));
                laixe.Add(new KeyValuePair<string, string>("15", "29A77608"));
                laixe.Add(new KeyValuePair<string, string>("150", "29A54030"));
                laixe.Add(new KeyValuePair<string, string>("151", "31F0044"));
                laixe.Add(new KeyValuePair<string, string>("152", "31F0480"));
                laixe.Add(new KeyValuePair<string, string>("153", "31F0681"));
                laixe.Add(new KeyValuePair<string, string>("155", "30A26412"));
                laixe.Add(new KeyValuePair<string, string>("156", "30M0534"));
                laixe.Add(new KeyValuePair<string, string>("157", "30M4020"));
                laixe.Add(new KeyValuePair<string, string>("158", "30Z7148"));
                laixe.Add(new KeyValuePair<string, string>("16", "29A61748"));
                laixe.Add(new KeyValuePair<string, string>("160", "30Z7532"));
                laixe.Add(new KeyValuePair<string, string>("161", "29A26400"));
                laixe.Add(new KeyValuePair<string, string>("162", "29A56137"));
                laixe.Add(new KeyValuePair<string, string>("163", "31F0466"));
                laixe.Add(new KeyValuePair<string, string>("164", "30M0688"));
                laixe.Add(new KeyValuePair<string, string>("165", "31F0322"));
                laixe.Add(new KeyValuePair<string, string>("166", "29A86169"));
                laixe.Add(new KeyValuePair<string, string>("167", "30L5691"));
                laixe.Add(new KeyValuePair<string, string>("168", "30M0583"));
                laixe.Add(new KeyValuePair<string, string>("169", "30A26716"));
                laixe.Add(new KeyValuePair<string, string>("17", "29A69442"));
                laixe.Add(new KeyValuePair<string, string>("170", "30A19805"));
                laixe.Add(new KeyValuePair<string, string>("171", "31F0566"));
                laixe.Add(new KeyValuePair<string, string>("173", "30Z7333"));
                laixe.Add(new KeyValuePair<string, string>("174", "29A68077"));
                laixe.Add(new KeyValuePair<string, string>("175", "30V1382"));
                laixe.Add(new KeyValuePair<string, string>("177", "31F0849"));
                laixe.Add(new KeyValuePair<string, string>("179", "29A22163"));
                laixe.Add(new KeyValuePair<string, string>("18", "29A54991"));
                laixe.Add(new KeyValuePair<string, string>("180", "30A26418"));
                laixe.Add(new KeyValuePair<string, string>("181", "31F0340"));
                laixe.Add(new KeyValuePair<string, string>("182", "29A78459"));
                laixe.Add(new KeyValuePair<string, string>("183", "30A19041"));
                laixe.Add(new KeyValuePair<string, string>("184", "29A77538"));
                laixe.Add(new KeyValuePair<string, string>("185", "30L5916"));
                laixe.Add(new KeyValuePair<string, string>("186", "30A16793"));
                laixe.Add(new KeyValuePair<string, string>("187", "29A78146"));
                laixe.Add(new KeyValuePair<string, string>("188", "29A67976"));
                laixe.Add(new KeyValuePair<string, string>("189", "29A74286"));
                laixe.Add(new KeyValuePair<string, string>("19", "30A53343"));
                laixe.Add(new KeyValuePair<string, string>("191", "29A54092"));
                laixe.Add(new KeyValuePair<string, string>("192", "30Z7948"));
                laixe.Add(new KeyValuePair<string, string>("193", "31F0668"));
                laixe.Add(new KeyValuePair<string, string>("194", "31F0197"));
                laixe.Add(new KeyValuePair<string, string>("195", "30Z7335"));
                laixe.Add(new KeyValuePair<string, string>("196", "29A22353"));
                laixe.Add(new KeyValuePair<string, string>("198", "30A16287"));
                laixe.Add(new KeyValuePair<string, string>("199", "30Z6160"));
                laixe.Add(new KeyValuePair<string, string>("20", "29A85661"));
                laixe.Add(new KeyValuePair<string, string>("201", "30A16184"));
                laixe.Add(new KeyValuePair<string, string>("202", "30V0601"));
                laixe.Add(new KeyValuePair<string, string>("203", "30A61579"));
                laixe.Add(new KeyValuePair<string, string>("204", "29A81980"));
                laixe.Add(new KeyValuePair<string, string>("205", "30A46543"));
                laixe.Add(new KeyValuePair<string, string>("206", "30M0213"));
                laixe.Add(new KeyValuePair<string, string>("207", "29A18731"));
                laixe.Add(new KeyValuePair<string, string>("208", "30L5353"));
                laixe.Add(new KeyValuePair<string, string>("209", "29A25774"));
                laixe.Add(new KeyValuePair<string, string>("21", "29A27532"));
                laixe.Add(new KeyValuePair<string, string>("210", "30A53342"));
                laixe.Add(new KeyValuePair<string, string>("211", "30U4103"));
                laixe.Add(new KeyValuePair<string, string>("212", "29A96093"));
                laixe.Add(new KeyValuePair<string, string>("213", "30U4288"));
                laixe.Add(new KeyValuePair<string, string>("214", "30U4490"));
                laixe.Add(new KeyValuePair<string, string>("215", "30A53575"));
                laixe.Add(new KeyValuePair<string, string>("217", "30U4577"));
                laixe.Add(new KeyValuePair<string, string>("218", "30U4809"));
                laixe.Add(new KeyValuePair<string, string>("22", "30A06130"));
                laixe.Add(new KeyValuePair<string, string>("220", "30U4650"));
                laixe.Add(new KeyValuePair<string, string>("221", "30U4169"));
                laixe.Add(new KeyValuePair<string, string>("222", "30M0619"));
                laixe.Add(new KeyValuePair<string, string>("223", "30U4045"));
                laixe.Add(new KeyValuePair<string, string>("224", "30A43867"));
                laixe.Add(new KeyValuePair<string, string>("225", "30U4353"));
                laixe.Add(new KeyValuePair<string, string>("226", "30U4679"));
                laixe.Add(new KeyValuePair<string, string>("227", "30U4571"));
                laixe.Add(new KeyValuePair<string, string>("228", "30A16586"));
                laixe.Add(new KeyValuePair<string, string>("229", "30U4972"));
                laixe.Add(new KeyValuePair<string, string>("23", "30M0939"));
                laixe.Add(new KeyValuePair<string, string>("230", "30A19786"));
                laixe.Add(new KeyValuePair<string, string>("232", "30U4513"));
                laixe.Add(new KeyValuePair<string, string>("233", "30U4915"));
                laixe.Add(new KeyValuePair<string, string>("234", "30U4290"));
                laixe.Add(new KeyValuePair<string, string>("235", "30U4491"));
                laixe.Add(new KeyValuePair<string, string>("236", "30U4996"));
                laixe.Add(new KeyValuePair<string, string>("237", "30U4092"));
                laixe.Add(new KeyValuePair<string, string>("238", "30U4040"));
                laixe.Add(new KeyValuePair<string, string>("239", "30U4001"));
                laixe.Add(new KeyValuePair<string, string>("24", "30L5596"));
                laixe.Add(new KeyValuePair<string, string>("240", "30U4500"));
                laixe.Add(new KeyValuePair<string, string>("241", "30U4454"));
                laixe.Add(new KeyValuePair<string, string>("242", "30A43797"));
                laixe.Add(new KeyValuePair<string, string>("243", "29A86167"));
                laixe.Add(new KeyValuePair<string, string>("244", "30L5709"));
                laixe.Add(new KeyValuePair<string, string>("245", "30U4997"));
                laixe.Add(new KeyValuePair<string, string>("246", "30N0603"));
                laixe.Add(new KeyValuePair<string, string>("247", "30U4095"));
                laixe.Add(new KeyValuePair<string, string>("248", "29A77900"));
                laixe.Add(new KeyValuePair<string, string>("249", "30U4609"));
                laixe.Add(new KeyValuePair<string, string>("25", "29A61760"));
                laixe.Add(new KeyValuePair<string, string>("251", "30U4270"));
                laixe.Add(new KeyValuePair<string, string>("252", "29A54054"));
                laixe.Add(new KeyValuePair<string, string>("254", "30A16707"));
                laixe.Add(new KeyValuePair<string, string>("255", "29A64125"));
                laixe.Add(new KeyValuePair<string, string>("256", "30U4268"));
                laixe.Add(new KeyValuePair<string, string>("257", "30U4623"));
                laixe.Add(new KeyValuePair<string, string>("258", "30U4202"));
                laixe.Add(new KeyValuePair<string, string>("259", "30L5640"));
                laixe.Add(new KeyValuePair<string, string>("26", "29A67955"));
                laixe.Add(new KeyValuePair<string, string>("260", "30U4011"));
                laixe.Add(new KeyValuePair<string, string>("261", "30N0153"));
                laixe.Add(new KeyValuePair<string, string>("262", "29A56118"));
                laixe.Add(new KeyValuePair<string, string>("263", "29A61867"));
                laixe.Add(new KeyValuePair<string, string>("264", "30A56407"));
                laixe.Add(new KeyValuePair<string, string>("265", "30U4023"));
                laixe.Add(new KeyValuePair<string, string>("266", "29A67736"));
                laixe.Add(new KeyValuePair<string, string>("267", "30U4170"));
                laixe.Add(new KeyValuePair<string, string>("268", "30A16131"));
                laixe.Add(new KeyValuePair<string, string>("27", "29A81948"));
                laixe.Add(new KeyValuePair<string, string>("270", "30U4042"));
                laixe.Add(new KeyValuePair<string, string>("271", "30U4442"));
                laixe.Add(new KeyValuePair<string, string>("272", "30U4511"));
                laixe.Add(new KeyValuePair<string, string>("273", "30U4178"));
                laixe.Add(new KeyValuePair<string, string>("274", "30U4438"));
                laixe.Add(new KeyValuePair<string, string>("275", "30U4409"));
                laixe.Add(new KeyValuePair<string, string>("276", "30U4841"));
                laixe.Add(new KeyValuePair<string, string>("277", "30U4510"));
                laixe.Add(new KeyValuePair<string, string>("278", "30U4622"));
                laixe.Add(new KeyValuePair<string, string>("28", "29A78346"));
                laixe.Add(new KeyValuePair<string, string>("280", "29A18538"));
                laixe.Add(new KeyValuePair<string, string>("281", "29A20403"));
                laixe.Add(new KeyValuePair<string, string>("282", "29A74780"));
                laixe.Add(new KeyValuePair<string, string>("283", "30U4440"));
                laixe.Add(new KeyValuePair<string, string>("284", "29A29717"));
                laixe.Add(new KeyValuePair<string, string>("285", "30L5068"));
                laixe.Add(new KeyValuePair<string, string>("286", "30M0830"));
                laixe.Add(new KeyValuePair<string, string>("287", "30U4060"));
                laixe.Add(new KeyValuePair<string, string>("288", "30A53057"));
                laixe.Add(new KeyValuePair<string, string>("289", "29A64385"));
                laixe.Add(new KeyValuePair<string, string>("29", "30A06123"));
                laixe.Add(new KeyValuePair<string, string>("290", "30U4472"));
                laixe.Add(new KeyValuePair<string, string>("291", "30U4880"));
                laixe.Add(new KeyValuePair<string, string>("292", "30U4697"));
                laixe.Add(new KeyValuePair<string, string>("293", "30A16782"));
                laixe.Add(new KeyValuePair<string, string>("294", "30A02622"));
                laixe.Add(new KeyValuePair<string, string>("295", "30A16021"));
                laixe.Add(new KeyValuePair<string, string>("296", "30L5671"));
                laixe.Add(new KeyValuePair<string, string>("298", "30U4421"));
                laixe.Add(new KeyValuePair<string, string>("299", "30A19588"));
                laixe.Add(new KeyValuePair<string, string>("30", "30A02924"));
                laixe.Add(new KeyValuePair<string, string>("300", "29A40704"));
                laixe.Add(new KeyValuePair<string, string>("301", "30L5381"));
                laixe.Add(new KeyValuePair<string, string>("302", "30A53594"));
                laixe.Add(new KeyValuePair<string, string>("303", "30A53584"));
                laixe.Add(new KeyValuePair<string, string>("304", "30P9631"));
                laixe.Add(new KeyValuePair<string, string>("305", "30P9887"));
                laixe.Add(new KeyValuePair<string, string>("308", "30A61573"));
                laixe.Add(new KeyValuePair<string, string>("309", "30A53613"));
                laixe.Add(new KeyValuePair<string, string>("31", "29A55750"));
                laixe.Add(new KeyValuePair<string, string>("310", "30S7462"));
                laixe.Add(new KeyValuePair<string, string>("311", "30S7467"));
                laixe.Add(new KeyValuePair<string, string>("312", "30S7537"));
                laixe.Add(new KeyValuePair<string, string>("313", "30A02422"));
                laixe.Add(new KeyValuePair<string, string>("314", "30S7314"));
                laixe.Add(new KeyValuePair<string, string>("315", "30N0967"));
                laixe.Add(new KeyValuePair<string, string>("316", "30S7980"));
                laixe.Add(new KeyValuePair<string, string>("317", "30S7650"));
                laixe.Add(new KeyValuePair<string, string>("318", "30S7418"));
                laixe.Add(new KeyValuePair<string, string>("319", "30A53800"));
                laixe.Add(new KeyValuePair<string, string>("32", "29A90419"));
                laixe.Add(new KeyValuePair<string, string>("321", "30S7583"));
                laixe.Add(new KeyValuePair<string, string>("322", "30S7477"));
                laixe.Add(new KeyValuePair<string, string>("323", "30S7042"));
                laixe.Add(new KeyValuePair<string, string>("324", "30S7799"));
                laixe.Add(new KeyValuePair<string, string>("325", "30S7108"));
                laixe.Add(new KeyValuePair<string, string>("326", "30S7264"));
                laixe.Add(new KeyValuePair<string, string>("327", "30S7767"));
                laixe.Add(new KeyValuePair<string, string>("328", "30S7542"));
                laixe.Add(new KeyValuePair<string, string>("329", "30S7738"));
                laixe.Add(new KeyValuePair<string, string>("330", "30S7660"));
                laixe.Add(new KeyValuePair<string, string>("331", "29A17548"));
                laixe.Add(new KeyValuePair<string, string>("332", "30S7334"));
                laixe.Add(new KeyValuePair<string, string>("333", "30M0676"));
                laixe.Add(new KeyValuePair<string, string>("334", "30T2702"));
                laixe.Add(new KeyValuePair<string, string>("335", "30T2503"));
                laixe.Add(new KeyValuePair<string, string>("336", "30S7472"));
                laixe.Add(new KeyValuePair<string, string>("337", "30T2973"));
                laixe.Add(new KeyValuePair<string, string>("338", "30S7659"));
                laixe.Add(new KeyValuePair<string, string>("339", "30T2927"));
                laixe.Add(new KeyValuePair<string, string>("340", "30S7482"));
                laixe.Add(new KeyValuePair<string, string>("341", "30T2478"));
                laixe.Add(new KeyValuePair<string, string>("342", "29A81844"));
                laixe.Add(new KeyValuePair<string, string>("343", "30L5586"));
                laixe.Add(new KeyValuePair<string, string>("344", "30T2910"));
                laixe.Add(new KeyValuePair<string, string>("345", "30S7580"));
                laixe.Add(new KeyValuePair<string, string>("346", "30S7994"));
                laixe.Add(new KeyValuePair<string, string>("347", "30T2364"));
                laixe.Add(new KeyValuePair<string, string>("348", "30S7024"));
                laixe.Add(new KeyValuePair<string, string>("349", "29A05289"));
                laixe.Add(new KeyValuePair<string, string>("35", "29A60042"));
                laixe.Add(new KeyValuePair<string, string>("350", "30T2783"));
                laixe.Add(new KeyValuePair<string, string>("351", "30T2701"));
                laixe.Add(new KeyValuePair<string, string>("352", "30A16085"));
                laixe.Add(new KeyValuePair<string, string>("353", "29A37734"));
                laixe.Add(new KeyValuePair<string, string>("354", "30A53349"));
                laixe.Add(new KeyValuePair<string, string>("355", "30T2538"));
                laixe.Add(new KeyValuePair<string, string>("356", "30A19160"));
                laixe.Add(new KeyValuePair<string, string>("357", "30T2728"));
                laixe.Add(new KeyValuePair<string, string>("359", "30S7995"));
                laixe.Add(new KeyValuePair<string, string>("36", "29A54863"));
                laixe.Add(new KeyValuePair<string, string>("360", "30A46394"));
                laixe.Add(new KeyValuePair<string, string>("361", "30T2550"));
                laixe.Add(new KeyValuePair<string, string>("362", "30T2126"));
                laixe.Add(new KeyValuePair<string, string>("363", "30T2419"));
                laixe.Add(new KeyValuePair<string, string>("364", "30T2084"));
                laixe.Add(new KeyValuePair<string, string>("365", "30T2583"));
                laixe.Add(new KeyValuePair<string, string>("366", "30T2737"));
                laixe.Add(new KeyValuePair<string, string>("367", "29A37733"));
                laixe.Add(new KeyValuePair<string, string>("368", "30A53274"));
                laixe.Add(new KeyValuePair<string, string>("369", "30T2012"));
                laixe.Add(new KeyValuePair<string, string>("37", "29A49747"));
                laixe.Add(new KeyValuePair<string, string>("370", "30T2413"));
                laixe.Add(new KeyValuePair<string, string>("371", "30T2426"));
                laixe.Add(new KeyValuePair<string, string>("372", "30T2607"));
                laixe.Add(new KeyValuePair<string, string>("373", "30U4425"));
                laixe.Add(new KeyValuePair<string, string>("374", "30U4561"));
                laixe.Add(new KeyValuePair<string, string>("375", "30U4664"));
                laixe.Add(new KeyValuePair<string, string>("376", "30U4806"));
                laixe.Add(new KeyValuePair<string, string>("377", "30U4342"));
                laixe.Add(new KeyValuePair<string, string>("378", "30U4720"));
                laixe.Add(new KeyValuePair<string, string>("379", "30U4877"));
                laixe.Add(new KeyValuePair<string, string>("38", "30L5886"));
                laixe.Add(new KeyValuePair<string, string>("380", "30U4418"));
                laixe.Add(new KeyValuePair<string, string>("381", "30U4789"));
                laixe.Add(new KeyValuePair<string, string>("382", "30A53299"));
                laixe.Add(new KeyValuePair<string, string>("383", "30A53307"));
                laixe.Add(new KeyValuePair<string, string>("384", "30U4812"));
                laixe.Add(new KeyValuePair<string, string>("385", "30U4395"));
                laixe.Add(new KeyValuePair<string, string>("386", "30A53625"));
                laixe.Add(new KeyValuePair<string, string>("387", "30A53368"));
                laixe.Add(new KeyValuePair<string, string>("388", "30A53353"));
                laixe.Add(new KeyValuePair<string, string>("389", "29A40707"));
                laixe.Add(new KeyValuePair<string, string>("39", "30L5121"));
                laixe.Add(new KeyValuePair<string, string>("390", "30V0642"));
                laixe.Add(new KeyValuePair<string, string>("391", "30V0303"));
                laixe.Add(new KeyValuePair<string, string>("392", "30V0585"));
                laixe.Add(new KeyValuePair<string, string>("393", "30A53339"));
                laixe.Add(new KeyValuePair<string, string>("394", "30U5377"));
                laixe.Add(new KeyValuePair<string, string>("395", "30V0444"));
                laixe.Add(new KeyValuePair<string, string>("396", "30N0912"));
                laixe.Add(new KeyValuePair<string, string>("398", "30A46512"));
                laixe.Add(new KeyValuePair<string, string>("399", "30V0575"));
                laixe.Add(new KeyValuePair<string, string>("40", "30A16239"));
                laixe.Add(new KeyValuePair<string, string>("400", "29A68057"));
                laixe.Add(new KeyValuePair<string, string>("401", "31F1031"));
                laixe.Add(new KeyValuePair<string, string>("402", "31F1123"));
                laixe.Add(new KeyValuePair<string, string>("403", "31F1769"));
                laixe.Add(new KeyValuePair<string, string>("404", "30A46638"));
                laixe.Add(new KeyValuePair<string, string>("405", "29A00162"));
                laixe.Add(new KeyValuePair<string, string>("406", "30U5271"));
                laixe.Add(new KeyValuePair<string, string>("407", "29A00160"));
                laixe.Add(new KeyValuePair<string, string>("408", "31F7219"));
                laixe.Add(new KeyValuePair<string, string>("409", "30A61530"));
                laixe.Add(new KeyValuePair<string, string>("41", "29A49745"));
                laixe.Add(new KeyValuePair<string, string>("410", "29A22357"));
                laixe.Add(new KeyValuePair<string, string>("411", "29A55699"));
                laixe.Add(new KeyValuePair<string, string>("412", "29A01405"));
                laixe.Add(new KeyValuePair<string, string>("414", "29A01412"));
                laixe.Add(new KeyValuePair<string, string>("415", "29A01408"));
                laixe.Add(new KeyValuePair<string, string>("416", "29A01411"));
                laixe.Add(new KeyValuePair<string, string>("417", "29A01409"));
                laixe.Add(new KeyValuePair<string, string>("418", "29A01419"));
                laixe.Add(new KeyValuePair<string, string>("419", "30A09382"));
                laixe.Add(new KeyValuePair<string, string>("42", "29A61958"));
                laixe.Add(new KeyValuePair<string, string>("420", "29A01413"));
                laixe.Add(new KeyValuePair<string, string>("421", "29A01415"));
                laixe.Add(new KeyValuePair<string, string>("422", "29A01414"));
                laixe.Add(new KeyValuePair<string, string>("423", "29A01417"));
                laixe.Add(new KeyValuePair<string, string>("424", "29A01410"));
                laixe.Add(new KeyValuePair<string, string>("425", "29A01407"));
                laixe.Add(new KeyValuePair<string, string>("426", "29A01418"));
                laixe.Add(new KeyValuePair<string, string>("427", "29A01406"));
                laixe.Add(new KeyValuePair<string, string>("428", "29A00085"));
                laixe.Add(new KeyValuePair<string, string>("429", "29A00086"));
                laixe.Add(new KeyValuePair<string, string>("430", "29A00087"));
                laixe.Add(new KeyValuePair<string, string>("431", "31F7289"));
                laixe.Add(new KeyValuePair<string, string>("432", "31F7160"));
                laixe.Add(new KeyValuePair<string, string>("433", "30A43938"));
                laixe.Add(new KeyValuePair<string, string>("434", "29A01378"));
                laixe.Add(new KeyValuePair<string, string>("437", "29A02652"));
                laixe.Add(new KeyValuePair<string, string>("438", "29A02655"));
                laixe.Add(new KeyValuePair<string, string>("439", "29A02659"));
                laixe.Add(new KeyValuePair<string, string>("44", "30L5466"));
                laixe.Add(new KeyValuePair<string, string>("440", "29A37731"));
                laixe.Add(new KeyValuePair<string, string>("441", "30A53629"));
                laixe.Add(new KeyValuePair<string, string>("443", "29A10496"));
                laixe.Add(new KeyValuePair<string, string>("444", "29A36112"));
                laixe.Add(new KeyValuePair<string, string>("446", "29A04240"));
                laixe.Add(new KeyValuePair<string, string>("447", "29A04241"));
                laixe.Add(new KeyValuePair<string, string>("448", "29A04242"));
                laixe.Add(new KeyValuePair<string, string>("449", "29A10160"));
                laixe.Add(new KeyValuePair<string, string>("45", "29A35993"));
                laixe.Add(new KeyValuePair<string, string>("450", "29A06164"));
                laixe.Add(new KeyValuePair<string, string>("451", "29A10469"));
                laixe.Add(new KeyValuePair<string, string>("455", "29A11165"));
                laixe.Add(new KeyValuePair<string, string>("456", "30M0292"));
                laixe.Add(new KeyValuePair<string, string>("457", "29A10001"));
                laixe.Add(new KeyValuePair<string, string>("458", "29A05284"));
                laixe.Add(new KeyValuePair<string, string>("459", "29A10801"));
                laixe.Add(new KeyValuePair<string, string>("46", "30M0328"));
                laixe.Add(new KeyValuePair<string, string>("461", "29A10503"));
                laixe.Add(new KeyValuePair<string, string>("462", "29A10802"));
                laixe.Add(new KeyValuePair<string, string>("463", "29A05192"));
                laixe.Add(new KeyValuePair<string, string>("464", "29A10439"));
                laixe.Add(new KeyValuePair<string, string>("465", "29A10438"));
                laixe.Add(new KeyValuePair<string, string>("466", "29A03856"));
                laixe.Add(new KeyValuePair<string, string>("467", "30A46475"));
                laixe.Add(new KeyValuePair<string, string>("468", "30L5194"));
                laixe.Add(new KeyValuePair<string, string>("469", "30A19764"));
                laixe.Add(new KeyValuePair<string, string>("47", "29A74250"));
                laixe.Add(new KeyValuePair<string, string>("471", "29A10804"));
                laixe.Add(new KeyValuePair<string, string>("472", "29A37720"));
                laixe.Add(new KeyValuePair<string, string>("474", "29A37724"));
                laixe.Add(new KeyValuePair<string, string>("475", "29A12792"));
                laixe.Add(new KeyValuePair<string, string>("476", "29A14435"));
                laixe.Add(new KeyValuePair<string, string>("477", "29A67928"));
                laixe.Add(new KeyValuePair<string, string>("478", "29A10161"));
                laixe.Add(new KeyValuePair<string, string>("479", "30A46508"));
                laixe.Add(new KeyValuePair<string, string>("48", "29A26511"));
                laixe.Add(new KeyValuePair<string, string>("480", "30A19605"));
                laixe.Add(new KeyValuePair<string, string>("481", "29A08747"));
                laixe.Add(new KeyValuePair<string, string>("483", "29A12791"));
                laixe.Add(new KeyValuePair<string, string>("485", "29A13811"));
                laixe.Add(new KeyValuePair<string, string>("486", "29A86141"));
                laixe.Add(new KeyValuePair<string, string>("487", "29A13812"));
                laixe.Add(new KeyValuePair<string, string>("488", "29A14810"));
                laixe.Add(new KeyValuePair<string, string>("489", "31F0637"));
                laixe.Add(new KeyValuePair<string, string>("490", "29A82008"));
                laixe.Add(new KeyValuePair<string, string>("491", "29A14429"));
                laixe.Add(new KeyValuePair<string, string>("492", "29A14430"));
                laixe.Add(new KeyValuePair<string, string>("493", "29A14431"));
                laixe.Add(new KeyValuePair<string, string>("494", "29A14432"));
                laixe.Add(new KeyValuePair<string, string>("495", "29A14433"));
                laixe.Add(new KeyValuePair<string, string>("497", "29A14434"));
                laixe.Add(new KeyValuePair<string, string>("498", "29A21611"));
                laixe.Add(new KeyValuePair<string, string>("499", "29A15420"));
                laixe.Add(new KeyValuePair<string, string>("50", "29A35994"));
                laixe.Add(new KeyValuePair<string, string>("500", "29A56101"));
                laixe.Add(new KeyValuePair<string, string>("501", "30A19850"));
                laixe.Add(new KeyValuePair<string, string>("502", "30A61679"));
                laixe.Add(new KeyValuePair<string, string>("504", "29A15421"));
                laixe.Add(new KeyValuePair<string, string>("505", "29A15422"));
                laixe.Add(new KeyValuePair<string, string>("507", "29A15424"));
                laixe.Add(new KeyValuePair<string, string>("510", "29A02658"));
                laixe.Add(new KeyValuePair<string, string>("512", "29A15942"));
                laixe.Add(new KeyValuePair<string, string>("513", "30N0839"));
                laixe.Add(new KeyValuePair<string, string>("514", "29A17517"));
                laixe.Add(new KeyValuePair<string, string>("515", "29A21545"));
                laixe.Add(new KeyValuePair<string, string>("516", "29A21546"));
                laixe.Add(new KeyValuePair<string, string>("517", "29A17549"));
                laixe.Add(new KeyValuePair<string, string>("518", "29A17652"));
                laixe.Add(new KeyValuePair<string, string>("519", "29A17653"));
                laixe.Add(new KeyValuePair<string, string>("52", "29A61869"));
                laixe.Add(new KeyValuePair<string, string>("520", "29A17654"));
                laixe.Add(new KeyValuePair<string, string>("521", "30A12764"));
                laixe.Add(new KeyValuePair<string, string>("522", "29A17518"));
                laixe.Add(new KeyValuePair<string, string>("523", "29A27531"));
                laixe.Add(new KeyValuePair<string, string>("525", "29A27537"));
                laixe.Add(new KeyValuePair<string, string>("526", "29A10499"));
                laixe.Add(new KeyValuePair<string, string>("527", "30A09493"));
                laixe.Add(new KeyValuePair<string, string>("529", "29A51262"));
                laixe.Add(new KeyValuePair<string, string>("530", "29A28825"));
                laixe.Add(new KeyValuePair<string, string>("531", "29A23701"));
                laixe.Add(new KeyValuePair<string, string>("532", "29A24532"));
                laixe.Add(new KeyValuePair<string, string>("533", "29A28830"));
                laixe.Add(new KeyValuePair<string, string>("534", "29A28831"));
                laixe.Add(new KeyValuePair<string, string>("535", "29A28832"));
                laixe.Add(new KeyValuePair<string, string>("536", "29A27535"));
                laixe.Add(new KeyValuePair<string, string>("537", "29A28834"));
                laixe.Add(new KeyValuePair<string, string>("538", "30A53619"));
                laixe.Add(new KeyValuePair<string, string>("539", "29A37960"));
                laixe.Add(new KeyValuePair<string, string>("54", "30L5627"));
                laixe.Add(new KeyValuePair<string, string>("540", "29A26321"));
                laixe.Add(new KeyValuePair<string, string>("541", "29A26324"));
                laixe.Add(new KeyValuePair<string, string>("543", "29A26330"));
                laixe.Add(new KeyValuePair<string, string>("545", "29A26334"));
                laixe.Add(new KeyValuePair<string, string>("546", "29A26337"));
                laixe.Add(new KeyValuePair<string, string>("547", "29A26340"));
                laixe.Add(new KeyValuePair<string, string>("548", "29A26341"));
                laixe.Add(new KeyValuePair<string, string>("549", "29A26342"));
                laixe.Add(new KeyValuePair<string, string>("55", "30A19778"));
                laixe.Add(new KeyValuePair<string, string>("551", "29A27200"));
                laixe.Add(new KeyValuePair<string, string>("552", "29A27201"));
                laixe.Add(new KeyValuePair<string, string>("553", "29A27202"));
                laixe.Add(new KeyValuePair<string, string>("554", "29A27264"));
                laixe.Add(new KeyValuePair<string, string>("555", "30A26376"));
                laixe.Add(new KeyValuePair<string, string>("556", "30Z7921"));
                laixe.Add(new KeyValuePair<string, string>("557", "29A27265"));
                laixe.Add(new KeyValuePair<string, string>("558", "30N3720"));
                laixe.Add(new KeyValuePair<string, string>("559", "29A10398"));
                laixe.Add(new KeyValuePair<string, string>("56", "29A81921"));
                laixe.Add(new KeyValuePair<string, string>("560.", "30A09547"));
                laixe.Add(new KeyValuePair<string, string>("561", "29A29110"));
                laixe.Add(new KeyValuePair<string, string>("562", "29A29708"));
                laixe.Add(new KeyValuePair<string, string>("563", "29A29112"));
                laixe.Add(new KeyValuePair<string, string>("564", "29A29111"));
                laixe.Add(new KeyValuePair<string, string>("565", "29A29114"));
                laixe.Add(new KeyValuePair<string, string>("566", "30A26389"));
                laixe.Add(new KeyValuePair<string, string>("567", "29A06343"));
                laixe.Add(new KeyValuePair<string, string>("568", "30A19601"));
                laixe.Add(new KeyValuePair<string, string>("569", "30A40187"));
                laixe.Add(new KeyValuePair<string, string>("57", "29A77907"));
                laixe.Add(new KeyValuePair<string, string>("572", "29A30735"));
                laixe.Add(new KeyValuePair<string, string>("573", "29A30810"));
                laixe.Add(new KeyValuePair<string, string>("574", "29A30802"));
                laixe.Add(new KeyValuePair<string, string>("575", "29A30801"));
                laixe.Add(new KeyValuePair<string, string>("576", "29A31622"));
                laixe.Add(new KeyValuePair<string, string>("577", "29A32846"));
                laixe.Add(new KeyValuePair<string, string>("578", "30A26432"));
                laixe.Add(new KeyValuePair<string, string>("579", "29A31630"));
                laixe.Add(new KeyValuePair<string, string>("58", "29A49744"));
                laixe.Add(new KeyValuePair<string, string>("580", "29A31782"));
                laixe.Add(new KeyValuePair<string, string>("581", "29A32847"));
                laixe.Add(new KeyValuePair<string, string>("582", "29A32848"));
                laixe.Add(new KeyValuePair<string, string>("583", "29A32849"));
                laixe.Add(new KeyValuePair<string, string>("584", "29A25773"));
                laixe.Add(new KeyValuePair<string, string>("585", "29A35370"));
                laixe.Add(new KeyValuePair<string, string>("586", "29A22167"));
                laixe.Add(new KeyValuePair<string, string>("587", "29A37965"));
                laixe.Add(new KeyValuePair<string, string>("588", "29A20400"));
                laixe.Add(new KeyValuePair<string, string>("589", "30Y3544"));
                laixe.Add(new KeyValuePair<string, string>("59", "30A19555"));
                laixe.Add(new KeyValuePair<string, string>("590", "29A32850"));
                laixe.Add(new KeyValuePair<string, string>("591", "29A44137"));
                laixe.Add(new KeyValuePair<string, string>("593", "29A32853"));
                laixe.Add(new KeyValuePair<string, string>("595", "29A32851"));
                laixe.Add(new KeyValuePair<string, string>("596", "29A34751"));
                laixe.Add(new KeyValuePair<string, string>("597", "29A34750"));
                laixe.Add(new KeyValuePair<string, string>("598", "29A34745"));
                laixe.Add(new KeyValuePair<string, string>("599", "29A32839"));
                laixe.Add(new KeyValuePair<string, string>("600", "29A77502"));
                laixe.Add(new KeyValuePair<string, string>("601", "29A35361"));
                laixe.Add(new KeyValuePair<string, string>("602", "29A35352"));
                laixe.Add(new KeyValuePair<string, string>("603", "29A35364"));
                laixe.Add(new KeyValuePair<string, string>("604", "29A34749"));
                laixe.Add(new KeyValuePair<string, string>("605", "29A36111"));
                laixe.Add(new KeyValuePair<string, string>("606", "29A34748"));
                laixe.Add(new KeyValuePair<string, string>("607", "29A34753"));
                laixe.Add(new KeyValuePair<string, string>("608", "29A34752"));
                laixe.Add(new KeyValuePair<string, string>("609", "29A37730"));
                laixe.Add(new KeyValuePair<string, string>("61", "29A44147"));
                laixe.Add(new KeyValuePair<string, string>("610", "29A34746"));
                laixe.Add(new KeyValuePair<string, string>("611", "29A34754"));
                laixe.Add(new KeyValuePair<string, string>("612", "29A34747"));
                laixe.Add(new KeyValuePair<string, string>("613", "29A37961"));
                laixe.Add(new KeyValuePair<string, string>("614", "29A18570"));
                laixe.Add(new KeyValuePair<string, string>("615", "29A37962"));
                laixe.Add(new KeyValuePair<string, string>("617", "29A37964"));
                laixe.Add(new KeyValuePair<string, string>("618", "29A36315"));
                laixe.Add(new KeyValuePair<string, string>("62", "29A68058"));
                laixe.Add(new KeyValuePair<string, string>("620", "29A37035"));
                laixe.Add(new KeyValuePair<string, string>("621", "29A37721"));
                laixe.Add(new KeyValuePair<string, string>("622", "29A37722"));
                laixe.Add(new KeyValuePair<string, string>("623", "29A37723"));
                laixe.Add(new KeyValuePair<string, string>("624", "29A41047"));
                laixe.Add(new KeyValuePair<string, string>("625", "29A37967"));
                laixe.Add(new KeyValuePair<string, string>("626", "29A29113"));
                laixe.Add(new KeyValuePair<string, string>("628", "29A37952"));
                laixe.Add(new KeyValuePair<string, string>("629", "29A37032"));
                laixe.Add(new KeyValuePair<string, string>("63", "30A16429"));
                laixe.Add(new KeyValuePair<string, string>("630", "29A37027"));
                laixe.Add(new KeyValuePair<string, string>("631", "29A40706"));
                laixe.Add(new KeyValuePair<string, string>("632", "29A41044"));
                laixe.Add(new KeyValuePair<string, string>("633", "29A40014"));
                laixe.Add(new KeyValuePair<string, string>("635", "30A43777"));
                laixe.Add(new KeyValuePair<string, string>("636", "30A43752"));
                laixe.Add(new KeyValuePair<string, string>("637", "29A40705"));
                laixe.Add(new KeyValuePair<string, string>("638", "29A40012"));
                laixe.Add(new KeyValuePair<string, string>("639", "29A40016"));
                laixe.Add(new KeyValuePair<string, string>("64", "30M0653"));
                laixe.Add(new KeyValuePair<string, string>("640", "29A40015"));
                laixe.Add(new KeyValuePair<string, string>("642", "30A53553"));
                laixe.Add(new KeyValuePair<string, string>("643", "29A54896"));
                laixe.Add(new KeyValuePair<string, string>("644", "29A41795"));
                laixe.Add(new KeyValuePair<string, string>("645", "29A41801"));
                laixe.Add(new KeyValuePair<string, string>("646", "29A41803"));
                laixe.Add(new KeyValuePair<string, string>("647", "29A41802"));
                laixe.Add(new KeyValuePair<string, string>("648", "30U4075"));
                laixe.Add(new KeyValuePair<string, string>("649", "29A51264"));
                laixe.Add(new KeyValuePair<string, string>("65", "29A55682"));
                laixe.Add(new KeyValuePair<string, string>("650", "30U5160"));
                laixe.Add(new KeyValuePair<string, string>("655", "29A01416"));
                laixe.Add(new KeyValuePair<string, string>("656", "30A26675"));
                laixe.Add(new KeyValuePair<string, string>("658", "29A25762"));
                laixe.Add(new KeyValuePair<string, string>("659", "30A16115"));
                laixe.Add(new KeyValuePair<string, string>("66", "30A56435"));
                laixe.Add(new KeyValuePair<string, string>("660", "30A32681"));
                laixe.Add(new KeyValuePair<string, string>("661", "29A96416"));
                laixe.Add(new KeyValuePair<string, string>("662", "29A26331"));
                laixe.Add(new KeyValuePair<string, string>("665", "29A60160"));
                laixe.Add(new KeyValuePair<string, string>("666", "30M0477"));
                laixe.Add(new KeyValuePair<string, string>("668", "30A16763"));
                laixe.Add(new KeyValuePair<string, string>("669", "30U4965"));
                laixe.Add(new KeyValuePair<string, string>("67", "29A51210"));
                laixe.Add(new KeyValuePair<string, string>("675", "29A52060"));
                laixe.Add(new KeyValuePair<string, string>("676", "29A37957"));
                laixe.Add(new KeyValuePair<string, string>("677", "30A61607"));
                laixe.Add(new KeyValuePair<string, string>("678", "29A15941"));
                laixe.Add(new KeyValuePair<string, string>("679", "29A54150"));
                laixe.Add(new KeyValuePair<string, string>("68", "30L5272"));
                laixe.Add(new KeyValuePair<string, string>("680", "30T2957"));
                laixe.Add(new KeyValuePair<string, string>("681", "30A16724"));
                laixe.Add(new KeyValuePair<string, string>("682", "29A51844"));
                laixe.Add(new KeyValuePair<string, string>("685", "30A43794"));
                laixe.Add(new KeyValuePair<string, string>("686", "30M4460"));
                laixe.Add(new KeyValuePair<string, string>("688", "29A44148"));
                laixe.Add(new KeyValuePair<string, string>("689", "29A44149"));
                laixe.Add(new KeyValuePair<string, string>("69", "30A53611"));
                laixe.Add(new KeyValuePair<string, string>("690", "29A82431"));
                laixe.Add(new KeyValuePair<string, string>("695", "29A51215"));
                laixe.Add(new KeyValuePair<string, string>("696", "29A37945"));
                laixe.Add(new KeyValuePair<string, string>("699", "29A44151"));
                laixe.Add(new KeyValuePair<string, string>("70", "29A90434"));
                laixe.Add(new KeyValuePair<string, string>("700", "30A61683"));
                laixe.Add(new KeyValuePair<string, string>("701", "29A62792"));
                laixe.Add(new KeyValuePair<string, string>("702", "30A12521"));
                laixe.Add(new KeyValuePair<string, string>("703", "30A61650"));
                laixe.Add(new KeyValuePair<string, string>("706", "30Z6181"));
                laixe.Add(new KeyValuePair<string, string>("709", "29A18565"));
                laixe.Add(new KeyValuePair<string, string>("71", "30A50763"));
                laixe.Add(new KeyValuePair<string, string>("712", "30Z6672"));
                laixe.Add(new KeyValuePair<string, string>("718", "29A32854"));
                laixe.Add(new KeyValuePair<string, string>("72", "30A61582"));
                laixe.Add(new KeyValuePair<string, string>("727", "29A54990"));
                laixe.Add(new KeyValuePair<string, string>("728", "29A15423"));
                laixe.Add(new KeyValuePair<string, string>("73", "31F0861"));
                laixe.Add(new KeyValuePair<string, string>("734", "30A26407"));
                laixe.Add(new KeyValuePair<string, string>("739", "29A55753"));
                laixe.Add(new KeyValuePair<string, string>("75", "29A31629"));
                laixe.Add(new KeyValuePair<string, string>("755", "29A78026"));
                laixe.Add(new KeyValuePair<string, string>("756", "29A77664"));
                laixe.Add(new KeyValuePair<string, string>("76", "29A82042"));
                laixe.Add(new KeyValuePair<string, string>("766", "30S7712"));
                laixe.Add(new KeyValuePair<string, string>("767", "29A55675"));
                laixe.Add(new KeyValuePair<string, string>("768", "29A10011"));
                laixe.Add(new KeyValuePair<string, string>("775", "29A37954"));
                laixe.Add(new KeyValuePair<string, string>("779", "29A54102"));
                laixe.Add(new KeyValuePair<string, string>("782", "30A26471"));
                laixe.Add(new KeyValuePair<string, string>("789", "30L5724"));
                laixe.Add(new KeyValuePair<string, string>("79", "30A16934"));
                laixe.Add(new KeyValuePair<string, string>("791", "30N0791"));
                laixe.Add(new KeyValuePair<string, string>("794", "29A26327"));
                laixe.Add(new KeyValuePair<string, string>("80", "29A54888"));
                laixe.Add(new KeyValuePair<string, string>("800", "29A18732"));
                laixe.Add(new KeyValuePair<string, string>("802", "29A22161"));
                laixe.Add(new KeyValuePair<string, string>("804", "30K7804"));
                laixe.Add(new KeyValuePair<string, string>("81", "30A02245"));
                laixe.Add(new KeyValuePair<string, string>("815", "30A23513"));
                laixe.Add(new KeyValuePair<string, string>("816", "30A12357"));
                laixe.Add(new KeyValuePair<string, string>("818", "30U4461"));
                laixe.Add(new KeyValuePair<string, string>("819", "29A95561"));
                laixe.Add(new KeyValuePair<string, string>("82", "29A54122"));
                laixe.Add(new KeyValuePair<string, string>("824", "30A61540"));
                laixe.Add(new KeyValuePair<string, string>("825", "29A67816"));
                laixe.Add(new KeyValuePair<string, string>("828", "30N0745"));
                laixe.Add(new KeyValuePair<string, string>("83", "29A41804"));
                laixe.Add(new KeyValuePair<string, string>("835", "30Z6800"));
                laixe.Add(new KeyValuePair<string, string>("838", "30A23632"));
                laixe.Add(new KeyValuePair<string, string>("839", "29A30811"));
                laixe.Add(new KeyValuePair<string, string>("84", "29A51843"));
                laixe.Add(new KeyValuePair<string, string>("85", "30N0326"));
                laixe.Add(new KeyValuePair<string, string>("855", "29A78107"));
                laixe.Add(new KeyValuePair<string, string>("856", "29A37732"));
                laixe.Add(new KeyValuePair<string, string>("858", "30A53808"));
                laixe.Add(new KeyValuePair<string, string>("86", "29A54979"));
                laixe.Add(new KeyValuePair<string, string>("860", "29A32852"));
                laixe.Add(new KeyValuePair<string, string>("861", "29A55743"));
                laixe.Add(new KeyValuePair<string, string>("862", "29A10498"));
                laixe.Add(new KeyValuePair<string, string>("863", "29A55630"));
                laixe.Add(new KeyValuePair<string, string>("866", "30A32558"));
                laixe.Add(new KeyValuePair<string, string>("868", "30A19818"));
                laixe.Add(new KeyValuePair<string, string>("88", "30A56309"));
                laixe.Add(new KeyValuePair<string, string>("880", "29A20404"));
                laixe.Add(new KeyValuePair<string, string>("882", "30A16771"));
                laixe.Add(new KeyValuePair<string, string>("883", "31F0449"));
                laixe.Add(new KeyValuePair<string, string>("885", "29A13804"));
                laixe.Add(new KeyValuePair<string, string>("886", "29A03855"));
                laixe.Add(new KeyValuePair<string, string>("888", "30M4454"));
                laixe.Add(new KeyValuePair<string, string>("889", "30A46012"));
                laixe.Add(new KeyValuePair<string, string>("89", "30A19122"));
                laixe.Add(new KeyValuePair<string, string>("896", "30S7625"));
                laixe.Add(new KeyValuePair<string, string>("898", "29A02654"));
                laixe.Add(new KeyValuePair<string, string>("899", "30Y0283"));
                laixe.Add(new KeyValuePair<string, string>("90", "30A61041"));
                laixe.Add(new KeyValuePair<string, string>("900", "30A26413"));
                laixe.Add(new KeyValuePair<string, string>("902", "30A16305"));
                laixe.Add(new KeyValuePair<string, string>("903", "29A54973"));
                laixe.Add(new KeyValuePair<string, string>("91", "30A16213"));
                laixe.Add(new KeyValuePair<string, string>("912", "29A90515"));
                laixe.Add(new KeyValuePair<string, string>("915", "29A09741"));
                laixe.Add(new KeyValuePair<string, string>("916", "29A90437"));
                laixe.Add(new KeyValuePair<string, string>("919", "30A46372"));
                laixe.Add(new KeyValuePair<string, string>("92", "30A26337"));
                laixe.Add(new KeyValuePair<string, string>("927", "29A54037"));
                laixe.Add(new KeyValuePair<string, string>("928", "29A10803"));
                laixe.Add(new KeyValuePair<string, string>("929", "30A61614"));
                laixe.Add(new KeyValuePair<string, string>("93", "30A06162"));
                laixe.Add(new KeyValuePair<string, string>("935", "29A23702"));
                laixe.Add(new KeyValuePair<string, string>("939", "30M4978"));
                laixe.Add(new KeyValuePair<string, string>("95", "31F0009"));
                laixe.Add(new KeyValuePair<string, string>("955", "29A81762"));
                laixe.Add(new KeyValuePair<string, string>("956", "29A41049"));
                laixe.Add(new KeyValuePair<string, string>("957", "30A43783"));
                laixe.Add(new KeyValuePair<string, string>("958", "29A54042"));
                laixe.Add(new KeyValuePair<string, string>("959", "29A85677"));
                laixe.Add(new KeyValuePair<string, string>("96", "30L5216"));
                laixe.Add(new KeyValuePair<string, string>("960", "29A51209"));
                laixe.Add(new KeyValuePair<string, string>("961", "29A15937"));
                laixe.Add(new KeyValuePair<string, string>("966", "29A15935"));
                laixe.Add(new KeyValuePair<string, string>("968", "30S7375"));
                laixe.Add(new KeyValuePair<string, string>("969", "30A40943"));
                laixe.Add(new KeyValuePair<string, string>("97", "29A23700"));
                laixe.Add(new KeyValuePair<string, string>("979", "30A16801"));
                laixe.Add(new KeyValuePair<string, string>("98", "29A61739"));
                laixe.Add(new KeyValuePair<string, string>("981", "30A40051"));
                laixe.Add(new KeyValuePair<string, string>("983", "30A53331"));
                laixe.Add(new KeyValuePair<string, string>("985", "29A55726"));
                laixe.Add(new KeyValuePair<string, string>("986", "29A15940"));
                laixe.Add(new KeyValuePair<string, string>("988", "29A55626"));
                laixe.Add(new KeyValuePair<string, string>("989", "29A37034"));
                laixe.Add(new KeyValuePair<string, string>("99", "29A53844"));
                laixe.Add(new KeyValuePair<string, string>("992", "29A29715"));
                laixe.Add(new KeyValuePair<string, string>("996", "30A40271"));
                laixe.Add(new KeyValuePair<string, string>("998", "30A46628"));
                laixe.Add(new KeyValuePair<string, string>("999", "30M0691"));
                #endregion
            }
            return laixe[this.GenerateRandomNumber(laixe.Count)];
        }
        /// <summary>
        /// khởi tạo ngẫu nhiên
        /// </summary>
        /// <returns></returns>
        public  string RanDomDiaChi()
        {
            if (diachi == null)
            {
                diachi = new List<string>();
                #region List Dia chi
                diachi.Add("Thị xã Lai Châu,Lai Châu");
                diachi.Add("Tam Đường,Lai Châu");
                diachi.Add("Phong Thổ,Lai Châu");
                diachi.Add("Than Uyên,Lai Châu");
                diachi.Add("Sơn La,Sơn La");
                diachi.Add("Quỳnh Nhai,Sơn La");
                diachi.Add("Bắc Yên,Sơn La");
                diachi.Add("Phù Yên,Sơn La");
                diachi.Add("Mộc Châu,Sơn La");
                diachi.Add("Yên Châu,Sơn La");
                diachi.Add("Mai Sơn,Sơn La");
                diachi.Add("Sông Mã,Sơn La");
                diachi.Add("Sốp Cộp,Sơn La");
                diachi.Add("Thành phố Yên Bái,Yên Bái");
                diachi.Add("Nghĩa Lộ,Yên Bái");
                diachi.Add("Lục Yên,Yên Bái");
                diachi.Add("Văn Yên,Yên Bái");
                diachi.Add("Trấn Yên,Yên Bái");
                diachi.Add("Trạm Tấu,Yên Bái");
                diachi.Add("Yên Bình,Yên Bái");
                diachi.Add("Thành phố Lạng Sơn,Lạng Sơn");
                diachi.Add("Tràng Định,Lạng Sơn");
                diachi.Add("Bình Gia,Lạng Sơn");
                diachi.Add("Văn Lãng,Lạng Sơn");
                diachi.Add("Cao Lộc,Lạng Sơn");
                diachi.Add("Văn Quan,Lạng Sơn");
                diachi.Add("Bắc Sơn,Lạng Sơn");
                diachi.Add("Hữu Lũng,Lạng Sơn");
                diachi.Add("Chi Lăng,Lạng Sơn");
                diachi.Add("Lộc Bình,Lạng Sơn");
                diachi.Add("Đình Lập,Lạng Sơn");
                diachi.Add("Thành phố Hạ Long,Quảng Ninh");
                diachi.Add("Móng Cái,Quảng Ninh");
                diachi.Add("Cẩm Phả,Quảng Ninh");
                diachi.Add("Uông Bí,Quảng Ninh");
                diachi.Add("Bình Liêu,Quảng Ninh");
                diachi.Add("Đầm Hà,Quảng Ninh");
                diachi.Add("Hải Hà,Quảng Ninh");
                diachi.Add("Ba Chẽ,Quảng Ninh");
                diachi.Add("Vân Đồn,Quảng Ninh");
                diachi.Add("Hoành Bồ,Quảng Ninh");
                diachi.Add("Đông Triều,Quảng Ninh");
                diachi.Add("Yên Hưng,Quảng Ninh");
                diachi.Add("Cô Tô,Quảng Ninh");
                diachi.Add("Thành phố Việt Trì,Phú Thọ");
                diachi.Add("Phú Thọ,Phú Thọ");
                diachi.Add("Đoan Hùng,Phú Thọ");
                diachi.Add("Hạ Hoà,Phú Thọ");
                diachi.Add("Thanh Ba,Phú Thọ");
                diachi.Add("Phù Ninh,Phú Thọ");
                diachi.Add("Yên Lập,Phú Thọ");
                diachi.Add("Cẩm Khê,Phú Thọ");
                diachi.Add("Tam Nông,Phú Thọ");
                diachi.Add("Lâm Thao,Phú Thọ");
                diachi.Add("Thanh Thuỷ,Phú Thọ");
                diachi.Add("Hà Giang,Hà Giang");
                diachi.Add("Đồng Văn,Hà Giang");
                diachi.Add("Mèo Vạc,Hà Giang");
                diachi.Add("Yên Minh,Hà Giang");
                diachi.Add("Thành phố Hải Dương,Hải Dương");
                diachi.Add("Quản Bạ,Hà Giang");
                diachi.Add("Chí Linh,Hải Dương");
                diachi.Add("Nam Sách,Hải Dương");
                diachi.Add("Kinh Môn,Hải Dương");
                diachi.Add("Kim Thành,Hải Dương");
                diachi.Add("Thanh Hà,Hải Dương");
                diachi.Add("Cẩm Giàng,Hải Dương");
                diachi.Add("Bình Giang,Hải Dương");
                diachi.Add("Gia Lộc,Hải Dương");
                diachi.Add("Tứ Kỳ,Hải Dương");
                diachi.Add("Ninh Giang,Hải Dương");
                diachi.Add("Vị Xuyên,Hà Giang");
                diachi.Add("Thanh Miện,Hải Dương");
                diachi.Add("Bắc Mê,Hà Giang");
                diachi.Add("Hoàng Su Phì,Hà Giang");
                diachi.Add("Xín Mần,Hà Giang");
                diachi.Add("Thái Bình,Thái Bình");
                diachi.Add("Quỳnh Phụ,Thái Bình");
                diachi.Add("Hưng Hà,Thái Bình");
                diachi.Add("Bắc Quang,Hà Giang");
                diachi.Add("Đông Hưng,Thái Bình");
                diachi.Add("Thái Thụy,Thái Bình");
                diachi.Add("Tiền Hải,Thái Bình");
                diachi.Add("Kiến Xương,Thái Bình");
                diachi.Add("Vũ Thư,Thái Bình");
                diachi.Add("Phủ Lý,Hà Nam");
                diachi.Add("Duy Tiên,Hà Nam");
                diachi.Add("Quang Bình,Hà Giang");
                diachi.Add("Kim Bảng,Hà Nam");
                diachi.Add("Thanh Liêm,Hà Nam");
                diachi.Add("Bình Lục,Hà Nam");
                diachi.Add("Lý Nhân,Hà Nam");
                diachi.Add("TP. Nam Định,Nam Định");
                diachi.Add("Mỹ Lộc,Nam Định");
                diachi.Add("Vụ Bản,Nam Định");
                diachi.Add("Ý Yên,Nam Định");
                diachi.Add("Nghĩa Hưng,Nam Định");
                diachi.Add("Nam Trực,Nam Định");
                diachi.Add("Trực Ninh,Nam Định");
                diachi.Add("Xuân Trường,Nam Định");
                diachi.Add("Giao Thủy,Nam Định");
                diachi.Add("Hải Hậu,Nam Định");
                diachi.Add("Ninh Bình,Ninh Bình");
                diachi.Add("Tam Điệp,Ninh Bình");
                diachi.Add("Nho Quan,Ninh Bình");
                diachi.Add("Gia Viễn,Ninh Bình");
                diachi.Add("Hoa Lư,Ninh Bình");
                diachi.Add("Yên Khánh,Ninh Bình");
                diachi.Add("Kim Sơn,Ninh Bình");
                diachi.Add("Yên Mô,Ninh Bình");
                diachi.Add("Thành phố Thanh Hóa,Thanh Hóa");
                diachi.Add("Bỉm Sơn,Thanh Hóa");
                diachi.Add("Sầm Sơn,Thanh Hóa");
                diachi.Add("Mường Lát,Thanh Hóa");
                diachi.Add("Quan Hóa,Thanh Hóa");
                diachi.Add("Bá Thước,Thanh Hóa");
                diachi.Add("Quan Sơn,Thanh Hóa");
                diachi.Add("Lang Chánh,Thanh Hóa");
                diachi.Add("Ngọc Lạc,Thanh Hóa");
                diachi.Add("Cẩm Thủy,Thanh Hóa");
                diachi.Add("Thạch Thành,Thanh Hóa");
                diachi.Add("Hà Trung,Thanh Hóa");
                diachi.Add("Vĩnh Lộc,Thanh Hóa");
                diachi.Add("Yên Định,Thanh Hóa");
                diachi.Add("Thọ Xuân,Thanh Hóa");
                diachi.Add("Thường Xuân,Thanh Hóa");
                diachi.Add("Triệu Sơn,Thanh Hóa");
                diachi.Add("Thiệu Hoá,Thanh Hóa");
                diachi.Add("Hoằng Hóa,Thanh Hóa");
                diachi.Add("Cao Bằng,Cao Bằng");
                diachi.Add("Hậu Lộc,Thanh Hóa");
                diachi.Add("Nga Sơn,Thanh Hóa");
                diachi.Add("Như Xuân,Thanh Hóa");
                diachi.Add("Như Thanh,Thanh Hóa");
                diachi.Add("Nông Cống,Thanh Hóa");
                diachi.Add("Đông Sơn,Thanh Hóa");
                diachi.Add("Quảng Xương,Thanh Hóa");
                diachi.Add("Tĩnh Gia,Thanh Hóa");
                diachi.Add("Thành phố Vinh,Nghệ An");
                diachi.Add("Cửa Lò,Nghệ An");
                diachi.Add("Quế Phong,Nghệ An");
                diachi.Add("Quỳ Châu,Nghệ An");
                diachi.Add("Kỳ Sơn,Nghệ An");
                diachi.Add("Tương Dương,Nghệ An");
                diachi.Add("Nghĩa Đàn,Nghệ An");
                diachi.Add("Bảo Lâm,Cao Bằng");
                diachi.Add("Quỳ Hợp,Nghệ An");
                diachi.Add("Quỳnh Lưu,Nghệ An");
                diachi.Add("Con Cuông,Nghệ An");
                diachi.Add("Tân Kỳ,Nghệ An");
                diachi.Add("Anh Sơn,Nghệ An");
                diachi.Add("Diễn Châu,Nghệ An");
                diachi.Add("Yên Thành,Nghệ An");
                diachi.Add("Đô Lương,Nghệ An");
                diachi.Add("Thanh Chương,Nghệ An");
                diachi.Add("Nghi Lộc,Nghệ An");
                diachi.Add("Bảo Lạc,Cao Bằng");
                diachi.Add("Nam Đàn,Nghệ An");
                diachi.Add("Hưng Nguyên,Nghệ An");
                diachi.Add("Hà Tĩnh,Hà Tĩnh");
                diachi.Add("Hồng Lĩnh,Hà Tĩnh");
                diachi.Add("Hương Sơn,Hà Tĩnh");
                diachi.Add("Thông Nông,Cao Bằng");
                diachi.Add("Đức Thọ,Hà Tĩnh");
                diachi.Add("Vũ Quang,Hà Tĩnh");
                diachi.Add("Nghi Xuân,Hà Tĩnh");
                diachi.Add("Can Lộc,Hà Tĩnh");
                diachi.Add("Hương Khê,Hà Tĩnh");
                diachi.Add("Thạch Hà,Hà Tĩnh");
                diachi.Add("Cẩm Xuyên,Hà Tĩnh");
                diachi.Add("Kỳ Anh,Hà Tĩnh");
                diachi.Add("Hà Quảng,Cao Bằng");
                diachi.Add("Đồng Hới,Quảng Bình");
                diachi.Add("Minh Hóa,Quảng Bình");
                diachi.Add("Quảng Trạch,Quảng Bình");
                diachi.Add("Quảng Ninh,Quảng Bình");
                diachi.Add("Trà Lĩnh,Cao Bằng");
                diachi.Add("Đông Hà,Quảng Trị");
                diachi.Add("Quảng Trị,Quảng Trị");
                diachi.Add("Vĩnh Linh,Quảng Trị");
                diachi.Add("Hướng Hóa,Quảng Trị");
                diachi.Add("Gio Linh,Quảng Trị");
                diachi.Add("Đa Krông,Quảng Trị");
                diachi.Add("Cam Lộ,Quảng Trị");
                diachi.Add("Triệu Phong,Quảng Trị");
                diachi.Add("Trùng Khánh,Cao Bằng");
                diachi.Add("Hải Lăng,Quảng Trị");
                diachi.Add("Thành phố Huế,Thừa Thiên Huế");
                diachi.Add("Quảng Điền,Thừa Thiên Huế");
                diachi.Add("Phú Vang,Thừa Thiên Huế");
                diachi.Add("Hương Thủy,Thừa Thiên Huế");
                diachi.Add("Hạ Lang,Cao Bằng");
                diachi.Add("Hương Trà,Thừa Thiên Huế");
                diachi.Add("A Lưới,Thừa Thiên Huế");
                diachi.Add("Phú Lộc,Thừa Thiên Huế");
                diachi.Add("Nam Đông,Thừa Thiên Huế");
                diachi.Add("Quảng Uyên,Cao Bằng");
                diachi.Add("Phục Hoà,Cao Bằng");
                diachi.Add("Tam Kỳ,Quảng Nam");
                diachi.Add("Hội An,Quảng Nam");
                diachi.Add("Tây Giang,Quảng Nam");
                diachi.Add("Đông Giang,Quảng Nam");
                diachi.Add("Đại Lộc,Quảng Nam");
                diachi.Add("Điện Bàn,Quảng Nam");
                diachi.Add("Duy Xuyên,Quảng Nam");
                diachi.Add("Hoà An,Cao Bằng");
                diachi.Add("Nam Giang,Quảng Nam");
                diachi.Add("Phước Sơn,Quảng Nam");
                diachi.Add("Hiệp Đức,Quảng Nam");
                diachi.Add("Thăng Bình,Quảng Nam");
                diachi.Add("Tiên Phước,Quảng Nam");
                diachi.Add("Nam Trà My,Quảng Nam");
                diachi.Add("Núi Thành,Quảng Nam");
                diachi.Add("Nguyên Bình,Cao Bằng");
                diachi.Add("Quảng Ngãi,Quảng Ngãi");
                diachi.Add("Bình Sơn,Quảng Ngãi");
                diachi.Add("Trà Bồng,Quảng Ngãi");
                diachi.Add("Tây Trà,Quảng Ngãi");
                diachi.Add("Sơn Tịnh,Quảng Ngãi");
                diachi.Add("Tư Nghĩa,Quảng Ngãi");
                diachi.Add("Sơn Hà,Quảng Ngãi");
                diachi.Add("Thạch An,Cao Bằng");
                diachi.Add("Sơn Tây,Quảng Ngãi");
                diachi.Add("Minh Long,Quảng Ngãi");
                diachi.Add("Nghĩa Hành,Quảng Ngãi");
                diachi.Add("Mộ Đức,Quảng Ngãi");
                diachi.Add("Đức Phổ,Quảng Ngãi");
                diachi.Add("Ba Tơ,Quảng Ngãi");
                diachi.Add("Lý Sơn,Quảng Ngãi");
                diachi.Add("Thành phố Qui Nhơn,Bình Định");
                diachi.Add("An Lão,Bình Định");
                diachi.Add("Hoài Nhơn,Bình Định");
                diachi.Add("Hoài Ân,Bình Định");
                diachi.Add("Phù Mỹ,Bình Định");
                diachi.Add("Vĩnh Thạnh,Bình Định");
                diachi.Add("Tây Sơn,Bình Định");
                diachi.Add("Phù Cát,Bình Định");
                diachi.Add("An Nhơn,Bình Định");
                diachi.Add("Tuy Phước,Bình Định");
                diachi.Add("Vân Canh,Bình Định");
                diachi.Add("Tuy Hòa,Phú Yên");
                diachi.Add("Sông Cầu,Phú Yên");
                diachi.Add("Tuy An,Phú Yên");
                diachi.Add("Sông Hinh,Phú Yên");
                diachi.Add("Tuy Hòa,Phú Yên");
                diachi.Add("Phú Hoà,Phú Yên");
                diachi.Add("Thành phố Nha Trang,Khánh Hòa");
                diachi.Add("Cam Ranh,Khánh Hòa");
                diachi.Add("Vạn Ninh,Khánh Hòa");
                diachi.Add("Ninh Hòa,Khánh Hòa");
                diachi.Add("Khánh Vĩnh,Khánh Hòa");
                diachi.Add("Diên Khánh,Khánh Hòa");
                diachi.Add("Khánh Sơn,Khánh Hòa");
                diachi.Add("Bắc Kạn,Bắc Kạn");
                diachi.Add("Phan Rang-Tháp Chàm,Ninh Thuận");
                diachi.Add("Ninh Hải,Ninh Thuận");
                diachi.Add("Ninh Phước,Ninh Thuận");
                diachi.Add("Thành phố Phan Thiết,Bình Thuận");
                diachi.Add("Tuy Phong,Bình Thuận");
                diachi.Add("Hàm Thuận Bắc,Bình Thuận");
                diachi.Add("Hàm Thuận Nam,Bình Thuận");
                diachi.Add("Tánh Linh,Bình Thuận");
                diachi.Add("Pác Nặm,Bắc Kạn");
                diachi.Add("Đức Linh,Bình Thuận");
                diachi.Add("Hàm Tân,Bình Thuận");
                diachi.Add("Kon Tum,Kon Tum");
                diachi.Add("Ba Bể,Bắc Kạn");
                diachi.Add("Đắk Glei,Kon Tum");
                diachi.Add("Ngọc Hồi,Kon Tum");
                diachi.Add("Đắk Tô,Kon Tum");
                diachi.Add("Kon Plông,Kon Tum");
                diachi.Add("Kon Rẫy,Kon Tum");
                diachi.Add("Đắk Hà,Kon Tum");
                diachi.Add("Sa Thầy,Kon Tum");
                diachi.Add("Ngân Sơn,Bắc Kạn");
                diachi.Add("Thành phố Pleiku,Gia Lai");
                diachi.Add("An Khê,Gia Lai");
                diachi.Add("KBang,Gia Lai");
                diachi.Add("Đăk Đoa,Gia Lai");
                diachi.Add("Chư Păh,Gia Lai");
                diachi.Add("Ia Grai,Gia Lai");
                diachi.Add("Mang Yang,Gia Lai");
                diachi.Add("Bạch Thông,Bắc Kạn");
                diachi.Add("Kông Chro,Gia Lai");
                diachi.Add("Đức Cơ,Gia Lai");
                diachi.Add("Chư Prông,Gia Lai");
                diachi.Add("Chư Sê,Gia Lai");
                diachi.Add("Đăk Pơ,Gia Lai");
                diachi.Add("Ia Pa,Gia Lai");
                diachi.Add("Ayun Pa,Gia Lai");
                diachi.Add("Chợ Đồn,Bắc Kạn");
                diachi.Add("Thành phố Buôn Ma Thuột,Đắk Lắk");
                diachi.Add("Ea Súp,Đắk Lắk");
                diachi.Add("Buôn Đôn,Đắk Lắk");
                diachi.Add("Krông Búk,Đắk Lắk");
                diachi.Add("Chợ Mới,Bắc Kạn");
                diachi.Add("Krông Năng,Đắk Lắk");
                diachi.Add("Ea Kar,Đắk Lắk");
                diachi.Add("Krông Bông,Đắk Lắk");
                diachi.Add("Krông Pắc,Đắk Lắk");
                diachi.Add("Krông A Na,Đắk Lắk");
                diachi.Add("Lắk,Đắk Lắk");
                diachi.Add("Na Rì,Bắc Kạn");
                diachi.Add("Đắk Nông,Đắk Nông");
                diachi.Add("Cư Jút,Đắk Nông");
                diachi.Add("Đắk Mil,Đắk Nông");
                diachi.Add("Krông Nô,Đắk Nông");
                diachi.Add("Đắk Song,Đắk Nông");
                diachi.Add("Thành phố Đà Lạt,Lâm Đồng");
                diachi.Add("Bảo Lộc,Lâm Đồng");
                diachi.Add("Lạc Dương,Lâm Đồng");
                diachi.Add("Lâm Hà,Lâm Đồng");
                diachi.Add("Đơn Dương,Lâm Đồng");
                diachi.Add("Đức Trọng,Lâm Đồng");
                diachi.Add("Di Linh,Lâm Đồng");
                diachi.Add("Bảo Lâm,Lâm Đồng");
                diachi.Add("Đạ Huoai,Lâm Đồng");
                diachi.Add("Đạ Tẻh,Lâm Đồng");
                diachi.Add("Cát Tiên,Lâm Đồng");
                diachi.Add("Đồng Xoài,Bình Phước");
                diachi.Add("Phước Long,Bình Phước");
                diachi.Add("Lộc Ninh,Bình Phước");
                diachi.Add("Bù Đốp,Bình Phước");
                diachi.Add("Bình Long,Bình Phước");
                diachi.Add("Đồng Phù,Bình Phước");
                diachi.Add("Bù Đăng,Bình Phước");
                diachi.Add("Chơn Thành,Bình Phước");
                diachi.Add("Tuyên Quang,Tuyên Quang");
                diachi.Add("Nà Hang,Tuyên Quang");
                diachi.Add("Chiêm Hóa,Tuyên Quang");
                diachi.Add("Hàm Yên,Tuyên Quang");
                diachi.Add("Yên Sơn,Tuyên Quang");
                diachi.Add("Sơn Dương,Tuyên Quang");
                diachi.Add("TX.Lào Cai,Lào Cai");
                diachi.Add("Bát Xát,Lào Cai");
                diachi.Add("Bến Tre,Bến Tre");
                diachi.Add("Mường Khương,Lào Cai");
                diachi.Add("Châu Thành,Bến Tre");
                diachi.Add("Chợ Lách,Bến Tre");
                diachi.Add("Mỏ Cày,Bến Tre");
                diachi.Add("Giồng Trôm,Bến Tre");
                diachi.Add("Bình Đại,Bến Tre");
                diachi.Add("Ba Tri,Bến Tre");
                diachi.Add("Thạnh Phú,Bến Tre");
                diachi.Add("Si Ma Cai,Lào Cai");
                diachi.Add("Trà Vinh,Trà Vinh");
                diachi.Add("Càng Long,Trà Vinh");
                diachi.Add("Cầu Kè,Trà Vinh");
                diachi.Add("Tiểu Cần,Trà Vinh");
                diachi.Add("Châu Thành,Trà Vinh");
                diachi.Add("Cầu Ngang,Trà Vinh");
                diachi.Add("Trà Cú,Trà Vinh");
                diachi.Add("Bắc Hà,Lào Cai");
                diachi.Add("Duyên Hải,Trà Vinh");
                diachi.Add("Bảo Thắng,Lào Cai");
                diachi.Add("Bảo Yên,Lào Cai");
                diachi.Add("Sa Pa,Lào Cai");
                diachi.Add("Văn Bàn,Lào Cai");
                diachi.Add("Thành phố Điện Biên Phủ,Điện Biên Phủ");
                diachi.Add("Sóc Trăng,Sóc Trăng");
                diachi.Add("Kế Sách,Sóc Trăng");
                diachi.Add("Mỹ Tú,Sóc Trăng");
                diachi.Add("Cù Lao Dung,Sóc Trăng");
                diachi.Add("Long Phú,Sóc Trăng");
                diachi.Add("Mỹ Xuyên,Sóc Trăng");
                diachi.Add("Ngã Năm,Sóc Trăng");
                diachi.Add("Thạnh Trị,Sóc Trăng");
                diachi.Add("TX. Lai Châu,Điện Biên Phủ");
                diachi.Add("Vĩnh Châu,Sóc Trăng");
                diachi.Add("Bạc Liêu,Bạc Liêu");
                diachi.Add("Hồng Dân,Bạc Liêu");
                diachi.Add("Phước Long,Bạc Liêu");
                diachi.Add("Vĩnh Lợi,Bạc Liêu");
                diachi.Add("Giá Rai,Bạc Liêu");
                diachi.Add("Đông Hải,Bạc Liêu");
                diachi.Add("Thành phố Cà Mau,Cà Mau");
                diachi.Add("U Minh,Cà Mau");
                diachi.Add("Thới Bình,Cà Mau");
                diachi.Add("Trần Văn Thời,Cà Mau");
                diachi.Add("Cái Nước,Cà Mau");
                diachi.Add("Đầm Dơi,Cà Mau");
                diachi.Add("Năm Căn,Cà Mau");
                diachi.Add("Phú Tân,Cà Mau");
                diachi.Add("Ngọc Hiển,Cà Mau");
                diachi.Add("Tủa Chùa,Điện Biên Phủ");
                diachi.Add("Tuần Giáo,Điện Biên Phủ");
                diachi.Add("Tây Ninh,Tây Ninh");
                diachi.Add("Tân Biên,Tây Ninh");
                diachi.Add("Tân Châu,Tây Ninh");
                diachi.Add("Dương Minh Châu,Tây Ninh");
                diachi.Add("Châu Thành,Tây Ninh");
                diachi.Add("Hòa Thành,Tây Ninh");
                diachi.Add("Gò Dầu,Tây Ninh");
                diachi.Add("Bến Cầu,Tây Ninh");
                diachi.Add("Trảng Bàng,Tây Ninh");
                diachi.Add("TX. Thủ Dầu Một,Bình Dương");
                diachi.Add("Dầu Tiếng,Bình Dương");
                diachi.Add("Bến Cát,Bình Dương");
                diachi.Add("Phú Giáo,Bình Dương");
                diachi.Add("Tân Uyên,Bình Dương");
                diachi.Add("Thuận An,Bình Dương");
                diachi.Add("Thành phố Biên Hòa,Đồng Nai");
                diachi.Add("Long Khánh,Đồng Nai");
                diachi.Add("Tân Phú,Đồng Nai");
                diachi.Add("Vĩnh Cửu,Đồng Nai");
                diachi.Add("Định Quán,Đồng Nai");
                diachi.Add("Trảng Bom,Đồng Nai");
                diachi.Add("Thống Nhất,Đồng Nai");
                diachi.Add("Cẩm Mỹ,Đồng Nai");
                diachi.Add("Long Thành,Đồng Nai");
                diachi.Add("Xuân Lộc,Đồng Nai");
                diachi.Add("Thành phố Vũng Tầu,Bà Rịa Vũng Tàu");
                diachi.Add("Bà Rịa,Bà Rịa Vũng Tàu");
                diachi.Add("Châu Đức,Bà Rịa Vũng Tàu");
                diachi.Add("Xuyên Mộc,Bà Rịa Vũng Tàu");
                diachi.Add("Long Điền,Bà Rịa Vũng Tàu");
                diachi.Add("Đất Đỏ,Bà Rịa Vũng Tàu");
                diachi.Add("Tân Thành,Bà Rịa Vũng Tàu");
                diachi.Add("Tân An,Long An");
                diachi.Add("Tân Hưng,Long An");
                diachi.Add("Vĩnh Hưng,Long An");
                diachi.Add("Mộc Hóa,Long An");
                diachi.Add("Tân Thạnh,Long An");
                diachi.Add("Thạnh Hóa,Long An");
                diachi.Add("Đức Huệ,Long An");
                diachi.Add("Đức Hòa,Long An");
                diachi.Add("Bến Lức,Long An");
                diachi.Add("Thủ Thừa,Long An");
                diachi.Add("Tân Trụ,Long An");
                diachi.Add("Cần Đước,Long An");
                diachi.Add("Cần Giuộc,Long An");
                diachi.Add("Châu Thành,Long An");
                diachi.Add("Thành phố Mỹ Tho,Tiền Giang");
                diachi.Add("Gò Công,Tiền Giang");
                diachi.Add("Tân Phước,Tiền Giang");
                diachi.Add("Cái Bè,Tiền Giang");
                diachi.Add("Cai Lậy,Tiền Giang");
                diachi.Add("Châu Thành,Tiền Giang");
                diachi.Add("Chợ Gạo,Tiền Giang");
                diachi.Add("Gò Công Tây,Tiền Giang");
                diachi.Add("Gò Công Đông,Tiền Giang");
                diachi.Add("Nhơn Trạch,Đồng Nai");
                diachi.Add("Dĩ An,Bình Dương");
                diachi.Add("Quận 1,TP. Hồ Chí Minh");
                diachi.Add("Quận 12,TP. Hồ Chí Minh");
                diachi.Add("Quận Thủ Đức,TP. Hồ Chí Minh");
                diachi.Add("Quận 9,TP. Hồ Chí Minh");
                diachi.Add("Quận Gò Vấp,TP. Hồ Chí Minh");
                diachi.Add("Quận Bình Thạnh,TP. Hồ Chí Minh");
                diachi.Add("Quận Tân Bình,TP. Hồ Chí Minh");
                diachi.Add("Quận Tân Phú,TP. Hồ Chí Minh");
                diachi.Add("Quận Phú Nhuận,TP. Hồ Chí Minh");
                diachi.Add("Quận 2,TP. Hồ Chí Minh");
                diachi.Add("Quận 3,TP. Hồ Chí Minh");
                diachi.Add("Quận 10,TP. Hồ Chí Minh");
                diachi.Add("Quận 11,TP. Hồ Chí Minh");
                diachi.Add("Quận 4,TP. Hồ Chí Minh");
                diachi.Add("Quận 5,TP. Hồ Chí Minh");
                diachi.Add("Quận 6,TP. Hồ Chí Minh");
                diachi.Add("Quận 8,TP. Hồ Chí Minh");
                diachi.Add("Quận Bình Tân,TP. Hồ Chí Minh");
                diachi.Add("Quận 7,TP. Hồ Chí Minh");
                diachi.Add("Huyện Củ Chi,TP. Hồ Chí Minh");
                diachi.Add("Huyện Hóc Môn,TP. Hồ Chí Minh");
                diachi.Add("Huyện Bình Chánh,TP. Hồ Chí Minh");
                diachi.Add("Huyện Nhà Bè,TP. Hồ Chí Minh");
                diachi.Add("Huyện Cần Giờ,TP. Hồ Chí Minh");
                diachi.Add("Quận Ba Đình,Hà Nội");
                diachi.Add("Quận Hoàn Kiếm,Hà Nội");
                diachi.Add("Quận Tây Hồ,Hà Nội");
                diachi.Add("Quận Long Biên,Hà Nội");
                diachi.Add("Quận Cầu Giấy,Hà Nội");
                diachi.Add("Quận Đống Đa,Hà Nội");
                diachi.Add("Quận Hai Bà Trưng,Hà Nội");
                diachi.Add("Quận Hoàng Mai,Hà Nội");
                diachi.Add("Quận Thanh Xuân,Hà Nội");
                diachi.Add("Huyện Sóc Sơn,Hà Nội");
                diachi.Add("Huyện Đông Anh,Hà Nội");
                diachi.Add("Huyện Gia Lâm,Hà Nội");
                diachi.Add("Huyện Từ Liêm,Hà Nội");
                diachi.Add("Huyện Thanh Trì,Hà Nội");
                diachi.Add("Thành phố Thái Nguyên,Thái Nguyên");
                diachi.Add("Sông Công,Thái Nguyên");
                diachi.Add("Định Hóa,Thái Nguyên");
                diachi.Add("Phú Lương,Thái Nguyên");
                diachi.Add("Đồng Hỷ,Thái Nguyên");
                diachi.Add("Võ Nhai,Thái Nguyên");
                diachi.Add("Đại Từ,Thái Nguyên");
                diachi.Add("Phổ Yên,Thái Nguyên");
                diachi.Add("Phú Bình,Thái Nguyên");
                diachi.Add("Bắc Giang,Bắc Giang");
                diachi.Add("Yên Thế,Bắc Giang");
                diachi.Add("Tân Yên,Bắc Giang");
                diachi.Add("Lạng Giang,Bắc Giang");
                diachi.Add("Lục Nam,Bắc Giang");
                diachi.Add("Lục Ngạn,Bắc Giang");
                diachi.Add("Sơn Động,Bắc Giang");
                diachi.Add("Yên Dũng,Bắc Giang");
                diachi.Add("Việt Yên,Bắc Giang");
                diachi.Add("Hiệp Hòa,Bắc Giang");
                diachi.Add("Bắc Ninh,Bắc Ninh");
                diachi.Add("Yên Phong,Bắc Ninh");
                diachi.Add("Quế Võ,Bắc Ninh");
                diachi.Add("Tiên Du,Bắc Ninh");
                diachi.Add("Từ Sơn,Bắc Ninh");
                diachi.Add("Thuận Thành,Bắc Ninh");
                diachi.Add("Gia Bình,Bắc Ninh");
                diachi.Add("Lương Tài,Bắc Ninh");
                diachi.Add("Hưng Yên,Hưng Yên");
                diachi.Add("Văn Lâm,Hưng Yên");
                diachi.Add("Văn Giang,Hưng Yên");
                diachi.Add("Yên Mỹ,Hưng Yên");
                diachi.Add("Mỹ Hào,Hưng Yên");
                diachi.Add("Ân Thi,Hưng Yên");
                diachi.Add("Khoái Châu,Hưng Yên");
                diachi.Add("Kim Động,Hưng Yên");
                diachi.Add("Tiên Lữ,Hưng Yên");
                diachi.Add("Phù Cừ,Hưng Yên");
                diachi.Add("Vĩnh Long,Vĩnh Long");
                diachi.Add("Long Hồ,Vĩnh Long");
                diachi.Add("Mang Thít,Vĩnh Long");
                diachi.Add("Vũng Liêm,Vĩnh Long");
                diachi.Add("Tam Bình,Vĩnh Long");
                diachi.Add("Bình Minh,Vĩnh Long");
                diachi.Add("Trà Ôn,Vĩnh Long");
                diachi.Add("Cao Lãnh,Đồng Tháp");
                diachi.Add("Sa Đéc,Đồng Tháp");
                diachi.Add("Tân Hồng,Đồng Tháp");
                diachi.Add("Hồng Ngự,Đồng Tháp");
                diachi.Add("Tam Nông,Đồng Tháp");
                diachi.Add("Tháp Mười,Đồng Tháp");
                diachi.Add("Cao Lãnh,Đồng Tháp");
                diachi.Add("Thanh Bình,Đồng Tháp");
                diachi.Add("Lấp Vò,Đồng Tháp");
                diachi.Add("Lai Vung,Đồng Tháp");
                diachi.Add("Châu Thành,Đồng Tháp");
                diachi.Add("Thành phố Long Xuyên,An Giang");
                diachi.Add("Châu Đốc,An Giang");
                diachi.Add("An Phú,An Giang");
                diachi.Add("Tân Châu,An Giang");
                diachi.Add("Phú Tân,An Giang");
                diachi.Add("Châu Phú,An Giang");
                diachi.Add("Tịnh Biên,An Giang");
                diachi.Add("Tri Tôn,An Giang");
                diachi.Add("Chợ Mới,An Giang");
                diachi.Add("Chợ Mới,An Giang");
                diachi.Add("Thoại Sơn,An Giang");
                diachi.Add("Rạch Giá,Kiên Giang");
                diachi.Add("Hà Tiên,Kiên Giang");
                diachi.Add("Kiên Lương,Kiên Giang");
                diachi.Add("Hòn Đất,Kiên Giang");
                diachi.Add("Tân Hiệp,Kiên Giang");
                diachi.Add("Châu Thành,Kiên Giang");
                diachi.Add("Giồng Giềng,Kiên Giang");
                diachi.Add("Gò Quao,Kiên Giang");
                diachi.Add("An Biên,Kiên Giang");
                diachi.Add("An Minh,Kiên Giang");
                diachi.Add("Vĩnh Thuận,Kiên Giang");
                diachi.Add("Phú Quốc,Kiên Giang");
                diachi.Add("Kiên Hải,Kiên Giang");
                diachi.Add("Ninh Kiều,Cần Thơ");
                diachi.Add("Huyện Ô Môn,Cần Thơ");
                diachi.Add("Bình Thuỷ,Cần Thơ");
                diachi.Add("Châu Thành  A,Cần Thơ");
                diachi.Add("Thốt Nốt,Cần Thơ");
                diachi.Add("Vĩnh Thạnh,Cần Thơ");
                diachi.Add("Cờ Đỏ,Cần Thơ");
                diachi.Add("Phong Điền,Cần Thơ");
                diachi.Add("Vị Thanh,Hậu Giang");
                diachi.Add("Châu Thành  A,Hậu Giang");
                diachi.Add("Châu Thành,Hậu Giang");
                diachi.Add("Phụng Hiệp,Hậu Giang");
                diachi.Add("Vị Thuỷ,Hậu Giang");
                diachi.Add("Long Mỹ,Hậu Giang");
                diachi.Add("Đồ Sơn,Hải Phòng");
                diachi.Add("Thuỷ Nguyên,Hải Phòng");
                diachi.Add("An Lão,Hải Phòng");
                diachi.Add("Tiên Lãng,Hải Phòng");
                diachi.Add("Vĩnh Bảo,Hải Phòng");
                diachi.Add("Cát Hải,Hải Phòng");
                diachi.Add("Hồng Bàng,Hải Phòng");
                diachi.Add("Hải An,Hải Phòng");
                diachi.Add("Liên Chiểu,Đà Nẵng");
                diachi.Add("Thanh Khê,Đà Nẵng");
                diachi.Add("Hải Châu,Đà Nẵng");
                diachi.Add("Sơn Trà,Đà Nẵng");
                diachi.Add("Ngũ Hành Sơn,Đà Nẵng");
                diachi.Add("Cẩm Lệ,Đà Nẵng");
                diachi.Add("Hòa Vang,Đà Nẵng");
                diachi.Add("Vĩnh Yên,Vĩnh Phúc");
                diachi.Add("Phúc Yên,Vĩnh Phúc");
                diachi.Add("Lập Thạch,Vĩnh Phúc");
                diachi.Add("Tam Dương,Vĩnh Phúc");
                diachi.Add("Tam Đảo,Vĩnh Phúc");
                diachi.Add("Bình Xuyên,Vĩnh Phúc");
                diachi.Add("Mê Linh,Hà Nội");
                diachi.Add("Yên Lạc,Vĩnh Phúc");
                diachi.Add("Vĩnh Tường,Vĩnh Phúc");
                diachi.Add("Hà Đông,Hà Nội");
                diachi.Add("Sơn Tây,Hà Nội");
                diachi.Add("Ba Vì,Hà Nội");
                diachi.Add("Phúc Thọ,Hà Nội");
                diachi.Add("Đan Phượng,Hà Nội");
                diachi.Add("Hoài Đức,Hà Nội");
                diachi.Add("Quốc Oai,Hà Nội");
                diachi.Add("Thạch Thất,Hà Nội");
                diachi.Add("Chương Mỹ,Hà Nội");
                diachi.Add("Thanh Oai,Hà Nội");
                diachi.Add("Thường Tín,Hà Nội");
                diachi.Add("Phú Xuyên,Hà Nội");
                diachi.Add("ứng Hòa,Hà Nội");
                diachi.Add("Mỹ Đức,Hà Nội");
                diachi.Add("Hòa Bình,Hòa Bình");
                diachi.Add("Đà Bắc,Hòa Bình");
                diachi.Add("Kỳ Sơn,Hòa Bình");
                diachi.Add("Kim Bôi,Hòa Bình");
                diachi.Add("Cao Phong,Hòa Bình");
                diachi.Add("Tân Lạc,Hòa Bình");
                diachi.Add("Mai Châu,Hòa Bình");
                diachi.Add("Lạc Sơn,Hòa Bình");
                diachi.Add("Yên Thủy,Hòa Bình");
                diachi.Add("Lạc Thủy,Hòa Bình");
                diachi.Add("Lê Chân,Hải Phòng");
                diachi.Add("An Duong,Hải Phòng");
                diachi.Add("Kiến An,Hải Phòng");
                diachi.Add("Ngô Quyền,Hải Phòng");
                diachi.Add("Kiến Thụy,Hải Phòng");
                diachi.Add("Hải An,Hải Phòng");
                diachi.Add("Lương Sơn,Hòa Bình");
                diachi.Add("Côn Đảo,Bà Rịa Vũng Tàu");
                #endregion
            }
            return diachi[1.GenerateRandomNumber(diachi.Count)];
        }

        private string RanDomTen()
        {
            #region Họ ten
            if (Ho == null)
            {
                Ho = new List<string>();
                Ho.Add("Nguyễn");
                Ho.Add("Trần");
                Ho.Add("Vũ");
                Ho.Add("Ngô");
                Ho.Add("Hà");
                Ho.Add("Hồ");
                Ho.Add("thị");
                Ho.Add("văn");
                Ho.Add("Vũ");
                Ho.Add("thanh");
                Ho.Add("Hà");
                Ho.Add("Hồ");
                Ho.Add("thị");
                Ho.Add("văn");
                Ho.Add("Vũ");
                Ho.Add("thanh");
                Ho.Add("Hà");
                Ho.Add("Hồ");
                Ho.Add("An");
                Ho.Add("Lực");
                Ho.Add("Luận");
                Ho.Add("Hải");
                Ho.Add("Hoàn");
            }
            if (TenDem == null)
            {
                TenDem = new List<string>();
                TenDem.Add("Nguyễn");
                TenDem.Add("Trần");
                TenDem.Add("Vũ");
                TenDem.Add("Ngô");
                TenDem.Add("Hà");
                TenDem.Add("Hồ");
                TenDem.Add("thị");
                TenDem.Add("văn");
                TenDem.Add("Vũ");
                TenDem.Add("thanh");
                TenDem.Add("Hà");
                TenDem.Add("Hồ");
                TenDem.Add("thị");
                TenDem.Add("văn");
                TenDem.Add("Vũ");
                TenDem.Add("thanh");
                TenDem.Add("Hà");
                TenDem.Add("Hồ");
                TenDem.Add("An");
                TenDem.Add("Lực");
                TenDem.Add("Luận");
                TenDem.Add("Hải");
                TenDem.Add("Hoàn");
            }
            if (Ten == null)
            {
                Ten = new List<string>();
                Ten.Add("Nguyễn");
                Ten.Add("Trần");
                Ten.Add("Vũ");
                Ten.Add("Ngô");
                Ten.Add("Hà");
                Ten.Add("Hồ");
                Ten.Add("thị");
                Ten.Add("văn");
                Ten.Add("Vũ");
                Ten.Add("thanh");
                Ten.Add("Hà");
                Ten.Add("Hồ");
                Ten.Add("thị");
                Ten.Add("văn");
                Ten.Add("Vũ");
                Ten.Add("thanh");
                Ten.Add("Hà");
                Ten.Add("Hồ");
                Ten.Add("An");
                Ten.Add("Lực");
                Ten.Add("Luận");
                Ten.Add("Hải");
                Ten.Add("Hoàn");
            }

            #endregion
            return string.Format("{0} {1} {2}", Ho[this.GenerateRandomNumber(0, Ho.Count)],
                TenDem[this.GenerateRandomNumber(0, TenDem.Count)], Ten[this.GenerateRandomNumber(0, Ten.Count)]);
        }
        private List<KeyValuePair<string, string>> laixe;
        private  List<string> diachi;
        private List<string> Ho;
        private List<string> TenDem;
        private List<string> Ten;

        private void button1_Click(object sender, EventArgs e)
        {
            new Thread(p =>
            {
                AutoCompleteAddress address = new AutoCompleteAddress();
                address.Bind();
                Taxi.Controls.FastTaxis.TaxiChieuVe.TaxiReturn_Process.IsKetThuc = true;
                List<XeDiDuongDai> ls = new List<XeDiDuongDai>();
                do
                {
                    var id = this.GenerateRandomNumber(0, 99);
                    var id2 = this.GenerateRandomNumber(0, 8);
                    var dateStart = DateTime.Now.AddMinutes(id);
                    var dateEnd = dateStart.AddHours(id2).AddMinutes(id2).AddSeconds(id).AddSeconds(id2);
                    XeDiDuongDai xedi = new XeDiDuongDai();
                    xedi.ThoiDiemDi = dateStart;
                    xedi.ThoiDiemVe = dateEnd;
                    xedi.TGDuKien = dateEnd;
                    do
                    {
                        xedi.SoDienThoai = RandomMobi();

                    } while (xedi.CheckSoDienThoai(xedi.SoDienThoai));


                    xedi.DiaDiemDen = RanDomDiaChi();
                    address.Text = xedi.DiaDiemDen;
                    address.ReSearch();
                    xedi.Den_ViDo = address.Lat;
                    xedi.Den_KinhDo = address.Lng;

                    xedi.DiaDiemDi = RanDomDiaChi();
                    address.Text = xedi.DiaDiemDi;
                    address.ReSearch();
                    xedi.Di_ViDo = address.Lat;
                    xedi.Di_KinhDo = address.Lng;

                    do
                    {
                        var xe = RanDomLaiXe();
                        xedi.FK_SoHieuXe = xe.Key;
                        xedi.BienSoXe = xe.Value;
                    } while (xedi.CheckXeChuaKetThucDuongDai(xedi.FK_SoHieuXe));

                    xedi.TenLaiXe = RanDomTen();

                    var kc = khoangCach(xedi.Di_KinhDo, xedi.Di_ViDo, xedi.Den_KinhDo, xedi.Den_ViDo);
                    #region kiểm tra dữ liệu
                    if (xedi.Den_ViDo > 17.9 && xedi.Di_ViDo > 17.9 && kc > 50 && kc <= 500)
                    {
                        xedi.isChiaSeChuyenDi = true;
                        xedi.TrangThaiDuyet = 1;
                        xedi.Is1Chieu = true;
                        xedi.TrangThai = (int)Taxi.Utils.Enums.Enum_XeBaoDiDuongDai_TrangThai.ChoGhepKhach;
                        xedi.CreatedDate = DieuHanhTaxi.GetTimeServer();
                        xedi.CreatedByUser = ThongTinDangNhap.USER_ID;
                        xedi.Insert();
                        ls.Add(xedi);
                        Taxi.Controls.FastTaxis.TaxiChieuVe.TaxiReturn_Process.AddTripProcess(xedi);
                    }
                    #endregion
                } while (ls.Count < 50);
                new MessageBox.MessageBoxBA().Show("Xong");
                //shGridControl1.DataSource = ls;
            }).Start();
           
        }
        const double R = Math.PI * 6371 / 180;
        private float khoangCach(float x1, float y1, float x2, float y2)
        {
            return (float)(Math.Sqrt(((x1 - x2) * (x1 - x2) + (y1 - y2) * (y1 - y2))) * R);           
        }
        #endregion
    }
}
