namespace Taxi.GUI.BaoCao
{
    partial class frmBC_1_3_ChiTietCuocGoiDen_LogVung
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Janus.Windows.GridEX.GridEXLayout gridEXLayout3 = new Janus.Windows.GridEX.GridEXLayout();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmBC_1_3_ChiTietCuocGoiDen_LogVung));
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.calTuNgay = new Janus.Windows.CalendarCombo.CalendarCombo();
            this.calDenNgay = new Janus.Windows.CalendarCombo.CalendarCombo();
            this.label3 = new System.Windows.Forms.Label();
            this.btnExportExcel = new Janus.Windows.EditControls.UIButton();
            this.btnRefresh = new Janus.Windows.EditControls.UIButton();
            this.gridEXPrintDocument1 = new Janus.Windows.GridEX.GridEXPrintDocument();
            this.gridDienThoai = new Janus.Windows.GridEX.GridEX();
            this.gridEXExporter1 = new Janus.Windows.GridEX.Export.GridEXExporter(this.components);
            this.saveFileDialog1 = new System.Windows.Forms.SaveFileDialog();
            this.pageSetupDialog1 = new System.Windows.Forms.PageSetupDialog();
            this.printPreviewDialog1 = new System.Windows.Forms.PrintPreviewDialog();
            this.ilButtons = new System.Windows.Forms.ImageList(this.components);
            this.player1 = new Alvas.Audio.Player();
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.label4 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel2 = new System.Windows.Forms.Panel();
            ((System.ComponentModel.ISupportInitialize)(this.gridDienThoai)).BeginInit();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(282, 10);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(469, 24);
            this.label1.TabIndex = 0;
            this.label1.Text = "BÁO CÁO CUỘC GỌI CÓ CHUYỂN VÙNG NHIỀU";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(319, 44);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(46, 13);
            this.label2.TabIndex = 1;
            this.label2.Text = "Từ ngày";
            // 
            // calTuNgay
            // 
            this.calTuNgay.CustomFormat = "HH:mm:ss dd/MM/yyyy";
            this.calTuNgay.DateFormat = Janus.Windows.CalendarCombo.DateFormat.Custom;
            // 
            // 
            // 
            this.calTuNgay.DropDownCalendar.FirstMonth = new System.DateTime(2008, 10, 1, 0, 0, 0, 0);
            this.calTuNgay.DropDownCalendar.Name = "";
            this.calTuNgay.Location = new System.Drawing.Point(371, 42);
            this.calTuNgay.Name = "calTuNgay";
            this.calTuNgay.Size = new System.Drawing.Size(141, 20);
            this.calTuNgay.TabIndex = 0;
            this.calTuNgay.ValueChanged += new System.EventHandler(this.calTuNgay_ValueChanged);
            // 
            // calDenNgay
            // 
            this.calDenNgay.CustomFormat = "HH:mm:ss dd/MM/yyyy";
            this.calDenNgay.DateFormat = Janus.Windows.CalendarCombo.DateFormat.Custom;
            // 
            // 
            // 
            this.calDenNgay.DropDownCalendar.FirstMonth = new System.DateTime(2008, 10, 1, 0, 0, 0, 0);
            this.calDenNgay.DropDownCalendar.Name = "";
            this.calDenNgay.Location = new System.Drawing.Point(574, 42);
            this.calDenNgay.Name = "calDenNgay";
            this.calDenNgay.Size = new System.Drawing.Size(141, 20);
            this.calDenNgay.TabIndex = 1;
            this.calDenNgay.ValueChanged += new System.EventHandler(this.calDenNgay_ValueChanged);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(521, 46);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(53, 13);
            this.label3.TabIndex = 3;
            this.label3.Text = "Đến ngày";
            // 
            // btnExportExcel
            // 
            this.btnExportExcel.FlatBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.btnExportExcel.Image = global::TaxiOperation_DieuHanhChinh.Properties.Resources.Excel;
            this.btnExportExcel.Location = new System.Drawing.Point(503, 83);
            this.btnExportExcel.Name = "btnExportExcel";
            this.btnExportExcel.Size = new System.Drawing.Size(84, 26);
            this.btnExportExcel.TabIndex = 21;
            this.btnExportExcel.Text = "Xuất &Excel";
            this.btnExportExcel.Click += new System.EventHandler(this.btnExportExcel_Click);
            // 
            // btnRefresh
            // 
            this.btnRefresh.Image = global::TaxiOperation_DieuHanhChinh.Properties.Resources.view_refresh;
            this.btnRefresh.Location = new System.Drawing.Point(417, 83);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.Size = new System.Drawing.Size(78, 26);
            this.btnRefresh.TabIndex = 20;
            this.btnRefresh.Text = "&Làm mới";
            this.btnRefresh.Click += new System.EventHandler(this.btnRefresh_Click);
            // 
            // gridEXPrintDocument1
            // 
            this.gridEXPrintDocument1.GridEX = this.gridDienThoai;
            // 
            // gridDienThoai
            // 
            this.gridDienThoai.AllowColumnDrag = false;
            this.gridDienThoai.AllowEdit = Janus.Windows.GridEX.InheritableBoolean.False;
            this.gridDienThoai.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridDienThoai.EnterKeyBehavior = Janus.Windows.GridEX.EnterKeyBehavior.None;
            this.gridDienThoai.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F);
            this.gridDienThoai.GroupByBoxVisible = false;
            this.gridDienThoai.HeaderFormatStyle.TextAlignment = Janus.Windows.GridEX.TextAlignment.Center;
            gridEXLayout3.IsCurrentLayout = true;
            gridEXLayout3.Key = "1";
            gridEXLayout3.LayoutString = resources.GetString("gridEXLayout3.LayoutString");
            this.gridDienThoai.Layouts.AddRange(new Janus.Windows.GridEX.GridEXLayout[] {
            gridEXLayout3});
            this.gridDienThoai.Location = new System.Drawing.Point(0, 0);
            this.gridDienThoai.Margin = new System.Windows.Forms.Padding(2);
            this.gridDienThoai.Name = "gridDienThoai";
            this.gridDienThoai.PreviewRowFormatStyle.Font = new System.Drawing.Font("Tahoma", 9F);
            this.gridDienThoai.RowFormatStyle.Appearance = Janus.Windows.GridEX.Appearance.RaisedLight;
            this.gridDienThoai.RowFormatStyle.Font = new System.Drawing.Font("Tahoma", 9F);
            this.gridDienThoai.RowFormatStyle.FontSize = 9F;
            this.gridDienThoai.RowFormatStyle.TextAlignment = Janus.Windows.GridEX.TextAlignment.Empty;
            this.gridDienThoai.RowHeaderContent = Janus.Windows.GridEX.RowHeaderContent.RowIndex;
            this.gridDienThoai.RowHeaderFormatStyle.Font = new System.Drawing.Font("Tahoma", 7F);
            this.gridDienThoai.RowHeaderFormatStyle.FontSize = 10F;
            this.gridDienThoai.RowHeaderFormatStyle.TextAlignment = Janus.Windows.GridEX.TextAlignment.Center;
            this.gridDienThoai.RowHeaders = Janus.Windows.GridEX.InheritableBoolean.True;
            this.gridDienThoai.SaveSettings = false;
            this.gridDienThoai.ScrollBars = Janus.Windows.GridEX.ScrollBars.Both;
            this.gridDienThoai.SettingsKey = "gridDienThoai";
            this.gridDienThoai.Size = new System.Drawing.Size(1032, 473);
            this.gridDienThoai.TabIndex = 22;
            this.gridDienThoai.TabKeyBehavior = Janus.Windows.GridEX.TabKeyBehavior.ControlNavigation;
            this.gridDienThoai.TableSpacing = 8;
            this.gridDienThoai.VisualStyle = Janus.Windows.GridEX.VisualStyle.Office2003;
            this.gridDienThoai.DoubleClick += new System.EventHandler(this.gridDienThoai_DoubleClick);
            // 
            // gridEXExporter1
            // 
            this.gridEXExporter1.GridEX = this.gridDienThoai;
            // 
            // pageSetupDialog1
            // 
            this.pageSetupDialog1.Document = this.gridEXPrintDocument1;
            // 
            // printPreviewDialog1
            // 
            this.printPreviewDialog1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.printPreviewDialog1.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.printPreviewDialog1.ClientSize = new System.Drawing.Size(400, 300);
            this.printPreviewDialog1.Document = this.gridEXPrintDocument1;
            this.printPreviewDialog1.Enabled = true;
            this.printPreviewDialog1.Icon = ((System.Drawing.Icon)(resources.GetObject("printPreviewDialog1.Icon")));
            this.printPreviewDialog1.Name = "printPreviewDialog1";
            this.printPreviewDialog1.Visible = false;
            // 
            // ilButtons
            // 
            this.ilButtons.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("ilButtons.ImageStream")));
            this.ilButtons.TransparentColor = System.Drawing.Color.Silver;
            this.ilButtons.Images.SetKeyName(0, "");
            this.ilButtons.Images.SetKeyName(1, "");
            this.ilButtons.Images.SetKeyName(2, "");
            this.ilButtons.Images.SetKeyName(3, "");
            this.ilButtons.Images.SetKeyName(4, "");
            this.ilButtons.Images.SetKeyName(5, "");
            this.ilButtons.Images.SetKeyName(6, "");
            this.ilButtons.Images.SetKeyName(7, "");
            this.ilButtons.Images.SetKeyName(8, "");
            this.ilButtons.Images.SetKeyName(9, "");
            this.ilButtons.Images.SetKeyName(10, "");
            this.ilButtons.Images.SetKeyName(11, "");
            this.ilButtons.Images.SetKeyName(12, "");
            this.ilButtons.Images.SetKeyName(13, "");
            this.ilButtons.Images.SetKeyName(14, "");
            this.ilButtons.Images.SetKeyName(15, "");
            this.ilButtons.Images.SetKeyName(16, "");
            this.ilButtons.Images.SetKeyName(17, "");
            this.ilButtons.Images.SetKeyName(18, "");
            this.ilButtons.Images.SetKeyName(19, "");
            this.ilButtons.Images.SetKeyName(20, "");
            this.ilButtons.Images.SetKeyName(21, "");
            this.ilButtons.Images.SetKeyName(22, "");
            this.ilButtons.Images.SetKeyName(23, "");
            this.ilButtons.Images.SetKeyName(24, "");
            this.ilButtons.Images.SetKeyName(25, "");
            this.ilButtons.Images.SetKeyName(26, "");
            this.ilButtons.Images.SetKeyName(27, "");
            this.ilButtons.Images.SetKeyName(28, "");
            this.ilButtons.Images.SetKeyName(29, "");
            this.ilButtons.Images.SetKeyName(30, "");
            this.ilButtons.Images.SetKeyName(31, "");
            this.ilButtons.Images.SetKeyName(32, "");
            this.ilButtons.Images.SetKeyName(33, "");
            this.ilButtons.Images.SetKeyName(34, "");
            this.ilButtons.Images.SetKeyName(35, "");
            this.ilButtons.Images.SetKeyName(36, "");
            this.ilButtons.Images.SetKeyName(37, "");
            this.ilButtons.Images.SetKeyName(38, "");
            this.ilButtons.Images.SetKeyName(39, "");
            this.ilButtons.Images.SetKeyName(40, "");
            this.ilButtons.Images.SetKeyName(41, "");
            this.ilButtons.Images.SetKeyName(42, "");
            this.ilButtons.Images.SetKeyName(43, "");
            this.ilButtons.Images.SetKeyName(44, "");
            this.ilButtons.Images.SetKeyName(45, "");
            this.ilButtons.Images.SetKeyName(46, "");
            this.ilButtons.Images.SetKeyName(47, "");
            this.ilButtons.Images.SetKeyName(48, "");
            this.ilButtons.Images.SetKeyName(49, "");
            this.ilButtons.Images.SetKeyName(50, "");
            this.ilButtons.Images.SetKeyName(51, "");
            this.ilButtons.Images.SetKeyName(52, "");
            this.ilButtons.Images.SetKeyName(53, "");
            this.ilButtons.Images.SetKeyName(54, "");
            this.ilButtons.Images.SetKeyName(55, "");
            this.ilButtons.Images.SetKeyName(56, "");
            this.ilButtons.Images.SetKeyName(57, "");
            this.ilButtons.Images.SetKeyName(58, "");
            this.ilButtons.Images.SetKeyName(59, "");
            this.ilButtons.Images.SetKeyName(60, "");
            this.ilButtons.Images.SetKeyName(61, "");
            this.ilButtons.Images.SetKeyName(62, "");
            this.ilButtons.Images.SetKeyName(63, "");
            this.ilButtons.Images.SetKeyName(64, "");
            this.ilButtons.Images.SetKeyName(65, "");
            this.ilButtons.Images.SetKeyName(66, "");
            this.ilButtons.Images.SetKeyName(67, "");
            this.ilButtons.Images.SetKeyName(68, "");
            this.ilButtons.Images.SetKeyName(69, "");
            this.ilButtons.Images.SetKeyName(70, "");
            this.ilButtons.Images.SetKeyName(71, "");
            this.ilButtons.Images.SetKeyName(72, "");
            this.ilButtons.Images.SetKeyName(73, "");
            this.ilButtons.Images.SetKeyName(74, "");
            this.ilButtons.Images.SetKeyName(75, "");
            this.ilButtons.Images.SetKeyName(76, "");
            this.ilButtons.Images.SetKeyName(77, "");
            this.ilButtons.Images.SetKeyName(78, "");
            this.ilButtons.Images.SetKeyName(79, "");
            this.ilButtons.Images.SetKeyName(80, "");
            this.ilButtons.Images.SetKeyName(81, "");
            this.ilButtons.Images.SetKeyName(82, "");
            this.ilButtons.Images.SetKeyName(83, "");
            this.ilButtons.Images.SetKeyName(84, "");
            this.ilButtons.Images.SetKeyName(85, "");
            this.ilButtons.Images.SetKeyName(86, "");
            this.ilButtons.Images.SetKeyName(87, "");
            this.ilButtons.Images.SetKeyName(88, "");
            this.ilButtons.Images.SetKeyName(89, "");
            this.ilButtons.Images.SetKeyName(90, "");
            this.ilButtons.Images.SetKeyName(91, "");
            this.ilButtons.Images.SetKeyName(92, "");
            this.ilButtons.Images.SetKeyName(93, "");
            this.ilButtons.Images.SetKeyName(94, "");
            this.ilButtons.Images.SetKeyName(95, "");
            this.ilButtons.Images.SetKeyName(96, "");
            this.ilButtons.Images.SetKeyName(97, "");
            this.ilButtons.Images.SetKeyName(98, "");
            this.ilButtons.Images.SetKeyName(99, "");
            this.ilButtons.Images.SetKeyName(100, "");
            this.ilButtons.Images.SetKeyName(101, "");
            this.ilButtons.Images.SetKeyName(102, "");
            this.ilButtons.Images.SetKeyName(103, "");
            this.ilButtons.Images.SetKeyName(104, "");
            this.ilButtons.Images.SetKeyName(105, "");
            this.ilButtons.Images.SetKeyName(106, "");
            this.ilButtons.Images.SetKeyName(107, "");
            this.ilButtons.Images.SetKeyName(108, "");
            this.ilButtons.Images.SetKeyName(109, "");
            this.ilButtons.Images.SetKeyName(110, "");
            this.ilButtons.Images.SetKeyName(111, "");
            this.ilButtons.Images.SetKeyName(112, "");
            this.ilButtons.Images.SetKeyName(113, "");
            this.ilButtons.Images.SetKeyName(114, "");
            this.ilButtons.Images.SetKeyName(115, "");
            this.ilButtons.Images.SetKeyName(116, "");
            this.ilButtons.Images.SetKeyName(117, "");
            this.ilButtons.Images.SetKeyName(118, "");
            this.ilButtons.Images.SetKeyName(119, "");
            this.ilButtons.Images.SetKeyName(120, "");
            this.ilButtons.Images.SetKeyName(121, "");
            this.ilButtons.Images.SetKeyName(122, "");
            this.ilButtons.Images.SetKeyName(123, "");
            this.ilButtons.Images.SetKeyName(124, "");
            this.ilButtons.Images.SetKeyName(125, "");
            this.ilButtons.Images.SetKeyName(126, "");
            this.ilButtons.Images.SetKeyName(127, "");
            this.ilButtons.Images.SetKeyName(128, "");
            this.ilButtons.Images.SetKeyName(129, "");
            this.ilButtons.Images.SetKeyName(130, "");
            this.ilButtons.Images.SetKeyName(131, "");
            this.ilButtons.Images.SetKeyName(132, "");
            this.ilButtons.Images.SetKeyName(133, "");
            this.ilButtons.Images.SetKeyName(134, "");
            this.ilButtons.Images.SetKeyName(135, "");
            this.ilButtons.Images.SetKeyName(136, "");
            this.ilButtons.Images.SetKeyName(137, "");
            this.ilButtons.Images.SetKeyName(138, "");
            this.ilButtons.Images.SetKeyName(139, "");
            this.ilButtons.Images.SetKeyName(140, "");
            this.ilButtons.Images.SetKeyName(141, "");
            this.ilButtons.Images.SetKeyName(142, "");
            this.ilButtons.Images.SetKeyName(143, "");
            this.ilButtons.Images.SetKeyName(144, "");
            this.ilButtons.Images.SetKeyName(145, "");
            this.ilButtons.Images.SetKeyName(146, "");
            this.ilButtons.Images.SetKeyName(147, "");
            this.ilButtons.Images.SetKeyName(148, "");
            this.ilButtons.Images.SetKeyName(149, "");
            this.ilButtons.Images.SetKeyName(150, "");
            this.ilButtons.Images.SetKeyName(151, "");
            this.ilButtons.Images.SetKeyName(152, "");
            this.ilButtons.Images.SetKeyName(153, "");
            this.ilButtons.Images.SetKeyName(154, "");
            this.ilButtons.Images.SetKeyName(155, "");
            this.ilButtons.Images.SetKeyName(156, "");
            this.ilButtons.Images.SetKeyName(157, "");
            this.ilButtons.Images.SetKeyName(158, "");
            this.ilButtons.Images.SetKeyName(159, "");
            this.ilButtons.Images.SetKeyName(160, "");
            this.ilButtons.Images.SetKeyName(161, "");
            this.ilButtons.Images.SetKeyName(162, "");
            this.ilButtons.Images.SetKeyName(163, "");
            this.ilButtons.Images.SetKeyName(164, "");
            this.ilButtons.Images.SetKeyName(165, "");
            this.ilButtons.Images.SetKeyName(166, "");
            this.ilButtons.Images.SetKeyName(167, "");
            this.ilButtons.Images.SetKeyName(168, "");
            this.ilButtons.Images.SetKeyName(169, "");
            this.ilButtons.Images.SetKeyName(170, "");
            this.ilButtons.Images.SetKeyName(171, "");
            this.ilButtons.Images.SetKeyName(172, "");
            this.ilButtons.Images.SetKeyName(173, "");
            this.ilButtons.Images.SetKeyName(174, "");
            this.ilButtons.Images.SetKeyName(175, "");
            this.ilButtons.Images.SetKeyName(176, "");
            this.ilButtons.Images.SetKeyName(177, "");
            this.ilButtons.Images.SetKeyName(178, "");
            this.ilButtons.Images.SetKeyName(179, "");
            this.ilButtons.Images.SetKeyName(180, "");
            this.ilButtons.Images.SetKeyName(181, "");
            this.ilButtons.Images.SetKeyName(182, "");
            this.ilButtons.Images.SetKeyName(183, "");
            this.ilButtons.Images.SetKeyName(184, "");
            this.ilButtons.Images.SetKeyName(185, "");
            this.ilButtons.Images.SetKeyName(186, "");
            this.ilButtons.Images.SetKeyName(187, "");
            this.ilButtons.Images.SetKeyName(188, "");
            this.ilButtons.Images.SetKeyName(189, "");
            this.ilButtons.Images.SetKeyName(190, "");
            this.ilButtons.Images.SetKeyName(191, "");
            this.ilButtons.Images.SetKeyName(192, "");
            this.ilButtons.Images.SetKeyName(193, "");
            this.ilButtons.Images.SetKeyName(194, "");
            this.ilButtons.Images.SetKeyName(195, "");
            this.ilButtons.Images.SetKeyName(196, "");
            this.ilButtons.Images.SetKeyName(197, "");
            this.ilButtons.Images.SetKeyName(198, "");
            this.ilButtons.Images.SetKeyName(199, "");
            this.ilButtons.Images.SetKeyName(200, "");
            this.ilButtons.Images.SetKeyName(201, "");
            this.ilButtons.Images.SetKeyName(202, "");
            this.ilButtons.Images.SetKeyName(203, "");
            this.ilButtons.Images.SetKeyName(204, "");
            this.ilButtons.Images.SetKeyName(205, "");
            this.ilButtons.Images.SetKeyName(206, "");
            this.ilButtons.Images.SetKeyName(207, "");
            this.ilButtons.Images.SetKeyName(208, "");
            this.ilButtons.Images.SetKeyName(209, "");
            this.ilButtons.Images.SetKeyName(210, "");
            this.ilButtons.Images.SetKeyName(211, "");
            this.ilButtons.Images.SetKeyName(212, "");
            this.ilButtons.Images.SetKeyName(213, "");
            this.ilButtons.Images.SetKeyName(214, "");
            this.ilButtons.Images.SetKeyName(215, "");
            this.ilButtons.Images.SetKeyName(216, "");
            this.ilButtons.Images.SetKeyName(217, "");
            this.ilButtons.Images.SetKeyName(218, "");
            this.ilButtons.Images.SetKeyName(219, "");
            this.ilButtons.Images.SetKeyName(220, "");
            this.ilButtons.Images.SetKeyName(221, "");
            this.ilButtons.Images.SetKeyName(222, "");
            this.ilButtons.Images.SetKeyName(223, "");
            this.ilButtons.Images.SetKeyName(224, "");
            this.ilButtons.Images.SetKeyName(225, "");
            this.ilButtons.Images.SetKeyName(226, "");
            this.ilButtons.Images.SetKeyName(227, "");
            this.ilButtons.Images.SetKeyName(228, "");
            this.ilButtons.Images.SetKeyName(229, "");
            this.ilButtons.Images.SetKeyName(230, "");
            this.ilButtons.Images.SetKeyName(231, "");
            this.ilButtons.Images.SetKeyName(232, "");
            this.ilButtons.Images.SetKeyName(233, "");
            this.ilButtons.Images.SetKeyName(234, "");
            this.ilButtons.Images.SetKeyName(235, "");
            this.ilButtons.Images.SetKeyName(236, "");
            this.ilButtons.Images.SetKeyName(237, "");
            this.ilButtons.Images.SetKeyName(238, "");
            this.ilButtons.Images.SetKeyName(239, "");
            this.ilButtons.Images.SetKeyName(240, "");
            this.ilButtons.Images.SetKeyName(241, "");
            this.ilButtons.Images.SetKeyName(242, "");
            this.ilButtons.Images.SetKeyName(243, "");
            this.ilButtons.Images.SetKeyName(244, "");
            this.ilButtons.Images.SetKeyName(245, "");
            this.ilButtons.Images.SetKeyName(246, "");
            this.ilButtons.Images.SetKeyName(247, "");
            this.ilButtons.Images.SetKeyName(248, "");
            this.ilButtons.Images.SetKeyName(249, "");
            this.ilButtons.Images.SetKeyName(250, "");
            this.ilButtons.Images.SetKeyName(251, "");
            this.ilButtons.Images.SetKeyName(252, "");
            this.ilButtons.Images.SetKeyName(253, "");
            this.ilButtons.Images.SetKeyName(254, "");
            this.ilButtons.Images.SetKeyName(255, "");
            this.ilButtons.Images.SetKeyName(256, "");
            this.ilButtons.Images.SetKeyName(257, "");
            this.ilButtons.Images.SetKeyName(258, "");
            this.ilButtons.Images.SetKeyName(259, "");
            this.ilButtons.Images.SetKeyName(260, "");
            this.ilButtons.Images.SetKeyName(261, "");
            this.ilButtons.Images.SetKeyName(262, "");
            this.ilButtons.Images.SetKeyName(263, "");
            this.ilButtons.Images.SetKeyName(264, "");
            this.ilButtons.Images.SetKeyName(265, "");
            this.ilButtons.Images.SetKeyName(266, "");
            this.ilButtons.Images.SetKeyName(267, "");
            this.ilButtons.Images.SetKeyName(268, "");
            this.ilButtons.Images.SetKeyName(269, "");
            this.ilButtons.Images.SetKeyName(270, "");
            this.ilButtons.Images.SetKeyName(271, "");
            this.ilButtons.Images.SetKeyName(272, "");
            this.ilButtons.Images.SetKeyName(273, "");
            this.ilButtons.Images.SetKeyName(274, "");
            this.ilButtons.Images.SetKeyName(275, "");
            this.ilButtons.Images.SetKeyName(276, "");
            this.ilButtons.Images.SetKeyName(277, "");
            this.ilButtons.Images.SetKeyName(278, "");
            this.ilButtons.Images.SetKeyName(279, "");
            this.ilButtons.Images.SetKeyName(280, "");
            this.ilButtons.Images.SetKeyName(281, "");
            this.ilButtons.Images.SetKeyName(282, "");
            this.ilButtons.Images.SetKeyName(283, "");
            this.ilButtons.Images.SetKeyName(284, "");
            this.ilButtons.Images.SetKeyName(285, "");
            this.ilButtons.Images.SetKeyName(286, "");
            this.ilButtons.Images.SetKeyName(287, "");
            this.ilButtons.Images.SetKeyName(288, "");
            this.ilButtons.Images.SetKeyName(289, "");
            this.ilButtons.Images.SetKeyName(290, "");
            this.ilButtons.Images.SetKeyName(291, "");
            this.ilButtons.Images.SetKeyName(292, "");
            this.ilButtons.Images.SetKeyName(293, "");
            this.ilButtons.Images.SetKeyName(294, "");
            this.ilButtons.Images.SetKeyName(295, "");
            this.ilButtons.Images.SetKeyName(296, "");
            this.ilButtons.Images.SetKeyName(297, "");
            this.ilButtons.Images.SetKeyName(298, "");
            this.ilButtons.Images.SetKeyName(299, "");
            this.ilButtons.Images.SetKeyName(300, "");
            this.ilButtons.Images.SetKeyName(301, "");
            this.ilButtons.Images.SetKeyName(302, "");
            this.ilButtons.Images.SetKeyName(303, "");
            this.ilButtons.Images.SetKeyName(304, "");
            this.ilButtons.Images.SetKeyName(305, "");
            this.ilButtons.Images.SetKeyName(306, "");
            this.ilButtons.Images.SetKeyName(307, "");
            this.ilButtons.Images.SetKeyName(308, "");
            this.ilButtons.Images.SetKeyName(309, "");
            this.ilButtons.Images.SetKeyName(310, "");
            this.ilButtons.Images.SetKeyName(311, "");
            this.ilButtons.Images.SetKeyName(312, "");
            this.ilButtons.Images.SetKeyName(313, "");
            this.ilButtons.Images.SetKeyName(314, "");
            this.ilButtons.Images.SetKeyName(315, "");
            this.ilButtons.Images.SetKeyName(316, "");
            this.ilButtons.Images.SetKeyName(317, "");
            this.ilButtons.Images.SetKeyName(318, "");
            this.ilButtons.Images.SetKeyName(319, "");
            this.ilButtons.Images.SetKeyName(320, "");
            this.ilButtons.Images.SetKeyName(321, "");
            this.ilButtons.Images.SetKeyName(322, "");
            this.ilButtons.Images.SetKeyName(323, "");
            this.ilButtons.Images.SetKeyName(324, "");
            this.ilButtons.Images.SetKeyName(325, "");
            this.ilButtons.Images.SetKeyName(326, "");
            this.ilButtons.Images.SetKeyName(327, "");
            this.ilButtons.Images.SetKeyName(328, "");
            this.ilButtons.Images.SetKeyName(329, "");
            this.ilButtons.Images.SetKeyName(330, "");
            this.ilButtons.Images.SetKeyName(331, "");
            this.ilButtons.Images.SetKeyName(332, "");
            this.ilButtons.Images.SetKeyName(333, "");
            this.ilButtons.Images.SetKeyName(334, "");
            this.ilButtons.Images.SetKeyName(335, "");
            this.ilButtons.Images.SetKeyName(336, "");
            this.ilButtons.Images.SetKeyName(337, "");
            this.ilButtons.Images.SetKeyName(338, "");
            this.ilButtons.Images.SetKeyName(339, "");
            this.ilButtons.Images.SetKeyName(340, "");
            this.ilButtons.Images.SetKeyName(341, "");
            this.ilButtons.Images.SetKeyName(342, "");
            this.ilButtons.Images.SetKeyName(343, "");
            this.ilButtons.Images.SetKeyName(344, "");
            this.ilButtons.Images.SetKeyName(345, "");
            this.ilButtons.Images.SetKeyName(346, "");
            this.ilButtons.Images.SetKeyName(347, "");
            this.ilButtons.Images.SetKeyName(348, "");
            this.ilButtons.Images.SetKeyName(349, "");
            this.ilButtons.Images.SetKeyName(350, "");
            this.ilButtons.Images.SetKeyName(351, "");
            this.ilButtons.Images.SetKeyName(352, "");
            this.ilButtons.Images.SetKeyName(353, "");
            this.ilButtons.Images.SetKeyName(354, "");
            this.ilButtons.Images.SetKeyName(355, "");
            this.ilButtons.Images.SetKeyName(356, "");
            this.ilButtons.Images.SetKeyName(357, "");
            this.ilButtons.Images.SetKeyName(358, "");
            this.ilButtons.Images.SetKeyName(359, "");
            this.ilButtons.Images.SetKeyName(360, "");
            this.ilButtons.Images.SetKeyName(361, "");
            this.ilButtons.Images.SetKeyName(362, "");
            this.ilButtons.Images.SetKeyName(363, "");
            this.ilButtons.Images.SetKeyName(364, "");
            this.ilButtons.Images.SetKeyName(365, "");
            this.ilButtons.Images.SetKeyName(366, "");
            this.ilButtons.Images.SetKeyName(367, "");
            this.ilButtons.Images.SetKeyName(368, "");
            this.ilButtons.Images.SetKeyName(369, "");
            this.ilButtons.Images.SetKeyName(370, "");
            this.ilButtons.Images.SetKeyName(371, "");
            this.ilButtons.Images.SetKeyName(372, "");
            this.ilButtons.Images.SetKeyName(373, "");
            this.ilButtons.Images.SetKeyName(374, "");
            this.ilButtons.Images.SetKeyName(375, "");
            this.ilButtons.Images.SetKeyName(376, "");
            this.ilButtons.Images.SetKeyName(377, "");
            this.ilButtons.Images.SetKeyName(378, "");
            this.ilButtons.Images.SetKeyName(379, "");
            this.ilButtons.Images.SetKeyName(380, "");
            this.ilButtons.Images.SetKeyName(381, "");
            this.ilButtons.Images.SetKeyName(382, "");
            this.ilButtons.Images.SetKeyName(383, "");
            this.ilButtons.Images.SetKeyName(384, "");
            this.ilButtons.Images.SetKeyName(385, "");
            this.ilButtons.Images.SetKeyName(386, "");
            this.ilButtons.Images.SetKeyName(387, "");
            this.ilButtons.Images.SetKeyName(388, "");
            this.ilButtons.Images.SetKeyName(389, "");
            this.ilButtons.Images.SetKeyName(390, "");
            this.ilButtons.Images.SetKeyName(391, "");
            this.ilButtons.Images.SetKeyName(392, "");
            this.ilButtons.Images.SetKeyName(393, "");
            this.ilButtons.Images.SetKeyName(394, "");
            this.ilButtons.Images.SetKeyName(395, "");
            this.ilButtons.Images.SetKeyName(396, "");
            this.ilButtons.Images.SetKeyName(397, "");
            this.ilButtons.Images.SetKeyName(398, "");
            this.ilButtons.Images.SetKeyName(399, "");
            this.ilButtons.Images.SetKeyName(400, "");
            this.ilButtons.Images.SetKeyName(401, "");
            this.ilButtons.Images.SetKeyName(402, "");
            this.ilButtons.Images.SetKeyName(403, "");
            this.ilButtons.Images.SetKeyName(404, "");
            this.ilButtons.Images.SetKeyName(405, "");
            this.ilButtons.Images.SetKeyName(406, "");
            this.ilButtons.Images.SetKeyName(407, "");
            this.ilButtons.Images.SetKeyName(408, "");
            this.ilButtons.Images.SetKeyName(409, "");
            this.ilButtons.Images.SetKeyName(410, "");
            this.ilButtons.Images.SetKeyName(411, "");
            this.ilButtons.Images.SetKeyName(412, "");
            this.ilButtons.Images.SetKeyName(413, "");
            this.ilButtons.Images.SetKeyName(414, "");
            this.ilButtons.Images.SetKeyName(415, "");
            this.ilButtons.Images.SetKeyName(416, "");
            this.ilButtons.Images.SetKeyName(417, "");
            this.ilButtons.Images.SetKeyName(418, "");
            this.ilButtons.Images.SetKeyName(419, "");
            this.ilButtons.Images.SetKeyName(420, "");
            this.ilButtons.Images.SetKeyName(421, "");
            this.ilButtons.Images.SetKeyName(422, "");
            this.ilButtons.Images.SetKeyName(423, "");
            this.ilButtons.Images.SetKeyName(424, "");
            this.ilButtons.Images.SetKeyName(425, "");
            this.ilButtons.Images.SetKeyName(426, "");
            this.ilButtons.Images.SetKeyName(427, "");
            this.ilButtons.Images.SetKeyName(428, "");
            this.ilButtons.Images.SetKeyName(429, "");
            this.ilButtons.Images.SetKeyName(430, "");
            this.ilButtons.Images.SetKeyName(431, "");
            this.ilButtons.Images.SetKeyName(432, "");
            this.ilButtons.Images.SetKeyName(433, "");
            this.ilButtons.Images.SetKeyName(434, "");
            this.ilButtons.Images.SetKeyName(435, "");
            this.ilButtons.Images.SetKeyName(436, "");
            this.ilButtons.Images.SetKeyName(437, "");
            this.ilButtons.Images.SetKeyName(438, "");
            this.ilButtons.Images.SetKeyName(439, "");
            this.ilButtons.Images.SetKeyName(440, "");
            this.ilButtons.Images.SetKeyName(441, "");
            this.ilButtons.Images.SetKeyName(442, "");
            this.ilButtons.Images.SetKeyName(443, "");
            this.ilButtons.Images.SetKeyName(444, "");
            this.ilButtons.Images.SetKeyName(445, "");
            this.ilButtons.Images.SetKeyName(446, "");
            this.ilButtons.Images.SetKeyName(447, "");
            this.ilButtons.Images.SetKeyName(448, "");
            this.ilButtons.Images.SetKeyName(449, "");
            this.ilButtons.Images.SetKeyName(450, "");
            this.ilButtons.Images.SetKeyName(451, "");
            this.ilButtons.Images.SetKeyName(452, "");
            this.ilButtons.Images.SetKeyName(453, "");
            this.ilButtons.Images.SetKeyName(454, "");
            this.ilButtons.Images.SetKeyName(455, "");
            this.ilButtons.Images.SetKeyName(456, "");
            this.ilButtons.Images.SetKeyName(457, "");
            this.ilButtons.Images.SetKeyName(458, "");
            this.ilButtons.Images.SetKeyName(459, "");
            this.ilButtons.Images.SetKeyName(460, "");
            this.ilButtons.Images.SetKeyName(461, "");
            this.ilButtons.Images.SetKeyName(462, "");
            this.ilButtons.Images.SetKeyName(463, "");
            this.ilButtons.Images.SetKeyName(464, "");
            this.ilButtons.Images.SetKeyName(465, "");
            this.ilButtons.Images.SetKeyName(466, "");
            this.ilButtons.Images.SetKeyName(467, "");
            this.ilButtons.Images.SetKeyName(468, "");
            this.ilButtons.Images.SetKeyName(469, "");
            this.ilButtons.Images.SetKeyName(470, "");
            this.ilButtons.Images.SetKeyName(471, "");
            this.ilButtons.Images.SetKeyName(472, "");
            this.ilButtons.Images.SetKeyName(473, "");
            this.ilButtons.Images.SetKeyName(474, "");
            this.ilButtons.Images.SetKeyName(475, "");
            this.ilButtons.Images.SetKeyName(476, "");
            this.ilButtons.Images.SetKeyName(477, "");
            this.ilButtons.Images.SetKeyName(478, "");
            this.ilButtons.Images.SetKeyName(479, "");
            this.ilButtons.Images.SetKeyName(480, "");
            this.ilButtons.Images.SetKeyName(481, "");
            this.ilButtons.Images.SetKeyName(482, "");
            this.ilButtons.Images.SetKeyName(483, "");
            this.ilButtons.Images.SetKeyName(484, "");
            this.ilButtons.Images.SetKeyName(485, "");
            this.ilButtons.Images.SetKeyName(486, "");
            this.ilButtons.Images.SetKeyName(487, "");
            this.ilButtons.Images.SetKeyName(488, "");
            this.ilButtons.Images.SetKeyName(489, "");
            this.ilButtons.Images.SetKeyName(490, "");
            this.ilButtons.Images.SetKeyName(491, "");
            this.ilButtons.Images.SetKeyName(492, "");
            this.ilButtons.Images.SetKeyName(493, "");
            this.ilButtons.Images.SetKeyName(494, "");
            this.ilButtons.Images.SetKeyName(495, "");
            this.ilButtons.Images.SetKeyName(496, "");
            this.ilButtons.Images.SetKeyName(497, "");
            this.ilButtons.Images.SetKeyName(498, "");
            this.ilButtons.Images.SetKeyName(499, "");
            this.ilButtons.Images.SetKeyName(500, "");
            this.ilButtons.Images.SetKeyName(501, "");
            this.ilButtons.Images.SetKeyName(502, "");
            this.ilButtons.Images.SetKeyName(503, "");
            this.ilButtons.Images.SetKeyName(504, "");
            this.ilButtons.Images.SetKeyName(505, "");
            this.ilButtons.Images.SetKeyName(506, "");
            this.ilButtons.Images.SetKeyName(507, "");
            this.ilButtons.Images.SetKeyName(508, "");
            this.ilButtons.Images.SetKeyName(509, "");
            this.ilButtons.Images.SetKeyName(510, "");
            this.ilButtons.Images.SetKeyName(511, "");
            this.ilButtons.Images.SetKeyName(512, "");
            this.ilButtons.Images.SetKeyName(513, "");
            this.ilButtons.Images.SetKeyName(514, "");
            this.ilButtons.Images.SetKeyName(515, "");
            this.ilButtons.Images.SetKeyName(516, "");
            this.ilButtons.Images.SetKeyName(517, "");
            this.ilButtons.Images.SetKeyName(518, "");
            this.ilButtons.Images.SetKeyName(519, "");
            this.ilButtons.Images.SetKeyName(520, "");
            this.ilButtons.Images.SetKeyName(521, "");
            this.ilButtons.Images.SetKeyName(522, "");
            this.ilButtons.Images.SetKeyName(523, "");
            this.ilButtons.Images.SetKeyName(524, "");
            this.ilButtons.Images.SetKeyName(525, "");
            this.ilButtons.Images.SetKeyName(526, "");
            this.ilButtons.Images.SetKeyName(527, "");
            this.ilButtons.Images.SetKeyName(528, "");
            this.ilButtons.Images.SetKeyName(529, "");
            this.ilButtons.Images.SetKeyName(530, "");
            this.ilButtons.Images.SetKeyName(531, "");
            this.ilButtons.Images.SetKeyName(532, "");
            this.ilButtons.Images.SetKeyName(533, "");
            this.ilButtons.Images.SetKeyName(534, "");
            this.ilButtons.Images.SetKeyName(535, "");
            this.ilButtons.Images.SetKeyName(536, "");
            this.ilButtons.Images.SetKeyName(537, "");
            this.ilButtons.Images.SetKeyName(538, "");
            this.ilButtons.Images.SetKeyName(539, "");
            this.ilButtons.Images.SetKeyName(540, "");
            this.ilButtons.Images.SetKeyName(541, "");
            this.ilButtons.Images.SetKeyName(542, "");
            this.ilButtons.Images.SetKeyName(543, "");
            this.ilButtons.Images.SetKeyName(544, "");
            this.ilButtons.Images.SetKeyName(545, "");
            this.ilButtons.Images.SetKeyName(546, "");
            this.ilButtons.Images.SetKeyName(547, "");
            this.ilButtons.Images.SetKeyName(548, "");
            this.ilButtons.Images.SetKeyName(549, "");
            this.ilButtons.Images.SetKeyName(550, "");
            this.ilButtons.Images.SetKeyName(551, "");
            this.ilButtons.Images.SetKeyName(552, "");
            this.ilButtons.Images.SetKeyName(553, "");
            this.ilButtons.Images.SetKeyName(554, "");
            this.ilButtons.Images.SetKeyName(555, "");
            this.ilButtons.Images.SetKeyName(556, "");
            this.ilButtons.Images.SetKeyName(557, "");
            this.ilButtons.Images.SetKeyName(558, "");
            this.ilButtons.Images.SetKeyName(559, "");
            this.ilButtons.Images.SetKeyName(560, "");
            this.ilButtons.Images.SetKeyName(561, "");
            this.ilButtons.Images.SetKeyName(562, "");
            this.ilButtons.Images.SetKeyName(563, "");
            this.ilButtons.Images.SetKeyName(564, "");
            this.ilButtons.Images.SetKeyName(565, "");
            this.ilButtons.Images.SetKeyName(566, "");
            this.ilButtons.Images.SetKeyName(567, "");
            this.ilButtons.Images.SetKeyName(568, "");
            this.ilButtons.Images.SetKeyName(569, "");
            this.ilButtons.Images.SetKeyName(570, "");
            this.ilButtons.Images.SetKeyName(571, "");
            this.ilButtons.Images.SetKeyName(572, "");
            this.ilButtons.Images.SetKeyName(573, "");
            this.ilButtons.Images.SetKeyName(574, "");
            this.ilButtons.Images.SetKeyName(575, "");
            this.ilButtons.Images.SetKeyName(576, "");
            this.ilButtons.Images.SetKeyName(577, "");
            this.ilButtons.Images.SetKeyName(578, "");
            this.ilButtons.Images.SetKeyName(579, "");
            this.ilButtons.Images.SetKeyName(580, "");
            this.ilButtons.Images.SetKeyName(581, "");
            this.ilButtons.Images.SetKeyName(582, "");
            this.ilButtons.Images.SetKeyName(583, "");
            this.ilButtons.Images.SetKeyName(584, "");
            this.ilButtons.Images.SetKeyName(585, "");
            this.ilButtons.Images.SetKeyName(586, "");
            this.ilButtons.Images.SetKeyName(587, "");
            this.ilButtons.Images.SetKeyName(588, "");
            this.ilButtons.Images.SetKeyName(589, "");
            this.ilButtons.Images.SetKeyName(590, "");
            this.ilButtons.Images.SetKeyName(591, "");
            this.ilButtons.Images.SetKeyName(592, "");
            this.ilButtons.Images.SetKeyName(593, "");
            this.ilButtons.Images.SetKeyName(594, "");
            this.ilButtons.Images.SetKeyName(595, "");
            this.ilButtons.Images.SetKeyName(596, "");
            this.ilButtons.Images.SetKeyName(597, "");
            this.ilButtons.Images.SetKeyName(598, "");
            this.ilButtons.Images.SetKeyName(599, "");
            this.ilButtons.Images.SetKeyName(600, "");
            this.ilButtons.Images.SetKeyName(601, "");
            this.ilButtons.Images.SetKeyName(602, "");
            this.ilButtons.Images.SetKeyName(603, "");
            this.ilButtons.Images.SetKeyName(604, "");
            this.ilButtons.Images.SetKeyName(605, "");
            this.ilButtons.Images.SetKeyName(606, "");
            this.ilButtons.Images.SetKeyName(607, "");
            this.ilButtons.Images.SetKeyName(608, "");
            this.ilButtons.Images.SetKeyName(609, "");
            this.ilButtons.Images.SetKeyName(610, "");
            this.ilButtons.Images.SetKeyName(611, "");
            this.ilButtons.Images.SetKeyName(612, "");
            this.ilButtons.Images.SetKeyName(613, "");
            this.ilButtons.Images.SetKeyName(614, "");
            this.ilButtons.Images.SetKeyName(615, "");
            this.ilButtons.Images.SetKeyName(616, "");
            this.ilButtons.Images.SetKeyName(617, "");
            this.ilButtons.Images.SetKeyName(618, "");
            this.ilButtons.Images.SetKeyName(619, "");
            this.ilButtons.Images.SetKeyName(620, "");
            this.ilButtons.Images.SetKeyName(621, "");
            this.ilButtons.Images.SetKeyName(622, "");
            this.ilButtons.Images.SetKeyName(623, "");
            this.ilButtons.Images.SetKeyName(624, "");
            this.ilButtons.Images.SetKeyName(625, "");
            this.ilButtons.Images.SetKeyName(626, "");
            this.ilButtons.Images.SetKeyName(627, "");
            this.ilButtons.Images.SetKeyName(628, "");
            this.ilButtons.Images.SetKeyName(629, "");
            this.ilButtons.Images.SetKeyName(630, "");
            this.ilButtons.Images.SetKeyName(631, "");
            this.ilButtons.Images.SetKeyName(632, "");
            this.ilButtons.Images.SetKeyName(633, "");
            this.ilButtons.Images.SetKeyName(634, "");
            this.ilButtons.Images.SetKeyName(635, "");
            this.ilButtons.Images.SetKeyName(636, "");
            this.ilButtons.Images.SetKeyName(637, "");
            this.ilButtons.Images.SetKeyName(638, "");
            this.ilButtons.Images.SetKeyName(639, "");
            this.ilButtons.Images.SetKeyName(640, "");
            this.ilButtons.Images.SetKeyName(641, "");
            this.ilButtons.Images.SetKeyName(642, "");
            this.ilButtons.Images.SetKeyName(643, "");
            this.ilButtons.Images.SetKeyName(644, "");
            this.ilButtons.Images.SetKeyName(645, "");
            this.ilButtons.Images.SetKeyName(646, "");
            this.ilButtons.Images.SetKeyName(647, "");
            this.ilButtons.Images.SetKeyName(648, "");
            this.ilButtons.Images.SetKeyName(649, "");
            this.ilButtons.Images.SetKeyName(650, "");
            this.ilButtons.Images.SetKeyName(651, "");
            this.ilButtons.Images.SetKeyName(652, "");
            this.ilButtons.Images.SetKeyName(653, "");
            this.ilButtons.Images.SetKeyName(654, "");
            this.ilButtons.Images.SetKeyName(655, "");
            this.ilButtons.Images.SetKeyName(656, "");
            this.ilButtons.Images.SetKeyName(657, "");
            this.ilButtons.Images.SetKeyName(658, "");
            this.ilButtons.Images.SetKeyName(659, "");
            this.ilButtons.Images.SetKeyName(660, "");
            this.ilButtons.Images.SetKeyName(661, "");
            this.ilButtons.Images.SetKeyName(662, "");
            this.ilButtons.Images.SetKeyName(663, "");
            this.ilButtons.Images.SetKeyName(664, "");
            this.ilButtons.Images.SetKeyName(665, "");
            this.ilButtons.Images.SetKeyName(666, "");
            this.ilButtons.Images.SetKeyName(667, "");
            this.ilButtons.Images.SetKeyName(668, "");
            this.ilButtons.Images.SetKeyName(669, "");
            this.ilButtons.Images.SetKeyName(670, "");
            this.ilButtons.Images.SetKeyName(671, "");
            this.ilButtons.Images.SetKeyName(672, "");
            this.ilButtons.Images.SetKeyName(673, "");
            this.ilButtons.Images.SetKeyName(674, "");
            this.ilButtons.Images.SetKeyName(675, "");
            this.ilButtons.Images.SetKeyName(676, "");
            this.ilButtons.Images.SetKeyName(677, "");
            this.ilButtons.Images.SetKeyName(678, "");
            this.ilButtons.Images.SetKeyName(679, "");
            this.ilButtons.Images.SetKeyName(680, "");
            this.ilButtons.Images.SetKeyName(681, "");
            this.ilButtons.Images.SetKeyName(682, "");
            this.ilButtons.Images.SetKeyName(683, "");
            this.ilButtons.Images.SetKeyName(684, "");
            this.ilButtons.Images.SetKeyName(685, "");
            this.ilButtons.Images.SetKeyName(686, "");
            this.ilButtons.Images.SetKeyName(687, "");
            this.ilButtons.Images.SetKeyName(688, "");
            this.ilButtons.Images.SetKeyName(689, "");
            this.ilButtons.Images.SetKeyName(690, "");
            this.ilButtons.Images.SetKeyName(691, "");
            this.ilButtons.Images.SetKeyName(692, "");
            this.ilButtons.Images.SetKeyName(693, "");
            this.ilButtons.Images.SetKeyName(694, "");
            this.ilButtons.Images.SetKeyName(695, "");
            this.ilButtons.Images.SetKeyName(696, "");
            this.ilButtons.Images.SetKeyName(697, "");
            this.ilButtons.Images.SetKeyName(698, "");
            this.ilButtons.Images.SetKeyName(699, "");
            this.ilButtons.Images.SetKeyName(700, "");
            this.ilButtons.Images.SetKeyName(701, "");
            this.ilButtons.Images.SetKeyName(702, "");
            this.ilButtons.Images.SetKeyName(703, "");
            this.ilButtons.Images.SetKeyName(704, "");
            this.ilButtons.Images.SetKeyName(705, "");
            this.ilButtons.Images.SetKeyName(706, "");
            this.ilButtons.Images.SetKeyName(707, "");
            this.ilButtons.Images.SetKeyName(708, "");
            this.ilButtons.Images.SetKeyName(709, "");
            this.ilButtons.Images.SetKeyName(710, "");
            this.ilButtons.Images.SetKeyName(711, "");
            this.ilButtons.Images.SetKeyName(712, "");
            this.ilButtons.Images.SetKeyName(713, "");
            this.ilButtons.Images.SetKeyName(714, "");
            this.ilButtons.Images.SetKeyName(715, "");
            this.ilButtons.Images.SetKeyName(716, "");
            this.ilButtons.Images.SetKeyName(717, "");
            this.ilButtons.Images.SetKeyName(718, "");
            this.ilButtons.Images.SetKeyName(719, "");
            this.ilButtons.Images.SetKeyName(720, "");
            this.ilButtons.Images.SetKeyName(721, "");
            this.ilButtons.Images.SetKeyName(722, "");
            this.ilButtons.Images.SetKeyName(723, "");
            this.ilButtons.Images.SetKeyName(724, "");
            this.ilButtons.Images.SetKeyName(725, "");
            this.ilButtons.Images.SetKeyName(726, "");
            this.ilButtons.Images.SetKeyName(727, "");
            this.ilButtons.Images.SetKeyName(728, "");
            this.ilButtons.Images.SetKeyName(729, "");
            this.ilButtons.Images.SetKeyName(730, "");
            this.ilButtons.Images.SetKeyName(731, "");
            this.ilButtons.Images.SetKeyName(732, "");
            this.ilButtons.Images.SetKeyName(733, "");
            this.ilButtons.Images.SetKeyName(734, "");
            this.ilButtons.Images.SetKeyName(735, "");
            this.ilButtons.Images.SetKeyName(736, "");
            this.ilButtons.Images.SetKeyName(737, "");
            this.ilButtons.Images.SetKeyName(738, "");
            this.ilButtons.Images.SetKeyName(739, "");
            this.ilButtons.Images.SetKeyName(740, "");
            this.ilButtons.Images.SetKeyName(741, "");
            this.ilButtons.Images.SetKeyName(742, "");
            this.ilButtons.Images.SetKeyName(743, "");
            this.ilButtons.Images.SetKeyName(744, "");
            this.ilButtons.Images.SetKeyName(745, "");
            this.ilButtons.Images.SetKeyName(746, "");
            this.ilButtons.Images.SetKeyName(747, "");
            this.ilButtons.Images.SetKeyName(748, "");
            this.ilButtons.Images.SetKeyName(749, "");
            this.ilButtons.Images.SetKeyName(750, "");
            this.ilButtons.Images.SetKeyName(751, "");
            this.ilButtons.Images.SetKeyName(752, "");
            this.ilButtons.Images.SetKeyName(753, "");
            this.ilButtons.Images.SetKeyName(754, "");
            this.ilButtons.Images.SetKeyName(755, "");
            this.ilButtons.Images.SetKeyName(756, "");
            this.ilButtons.Images.SetKeyName(757, "");
            this.ilButtons.Images.SetKeyName(758, "");
            this.ilButtons.Images.SetKeyName(759, "");
            this.ilButtons.Images.SetKeyName(760, "");
            this.ilButtons.Images.SetKeyName(761, "");
            this.ilButtons.Images.SetKeyName(762, "");
            this.ilButtons.Images.SetKeyName(763, "");
            this.ilButtons.Images.SetKeyName(764, "");
            this.ilButtons.Images.SetKeyName(765, "");
            this.ilButtons.Images.SetKeyName(766, "");
            this.ilButtons.Images.SetKeyName(767, "");
            this.ilButtons.Images.SetKeyName(768, "");
            this.ilButtons.Images.SetKeyName(769, "");
            this.ilButtons.Images.SetKeyName(770, "");
            this.ilButtons.Images.SetKeyName(771, "");
            this.ilButtons.Images.SetKeyName(772, "");
            this.ilButtons.Images.SetKeyName(773, "");
            this.ilButtons.Images.SetKeyName(774, "");
            this.ilButtons.Images.SetKeyName(775, "");
            this.ilButtons.Images.SetKeyName(776, "");
            this.ilButtons.Images.SetKeyName(777, "");
            this.ilButtons.Images.SetKeyName(778, "");
            this.ilButtons.Images.SetKeyName(779, "");
            this.ilButtons.Images.SetKeyName(780, "");
            this.ilButtons.Images.SetKeyName(781, "");
            this.ilButtons.Images.SetKeyName(782, "");
            this.ilButtons.Images.SetKeyName(783, "");
            this.ilButtons.Images.SetKeyName(784, "");
            this.ilButtons.Images.SetKeyName(785, "");
            this.ilButtons.Images.SetKeyName(786, "");
            this.ilButtons.Images.SetKeyName(787, "");
            this.ilButtons.Images.SetKeyName(788, "");
            this.ilButtons.Images.SetKeyName(789, "");
            this.ilButtons.Images.SetKeyName(790, "");
            this.ilButtons.Images.SetKeyName(791, "");
            this.ilButtons.Images.SetKeyName(792, "");
            this.ilButtons.Images.SetKeyName(793, "");
            this.ilButtons.Images.SetKeyName(794, "");
            this.ilButtons.Images.SetKeyName(795, "");
            this.ilButtons.Images.SetKeyName(796, "");
            this.ilButtons.Images.SetKeyName(797, "");
            this.ilButtons.Images.SetKeyName(798, "");
            this.ilButtons.Images.SetKeyName(799, "");
            this.ilButtons.Images.SetKeyName(800, "");
            this.ilButtons.Images.SetKeyName(801, "");
            this.ilButtons.Images.SetKeyName(802, "");
            this.ilButtons.Images.SetKeyName(803, "");
            this.ilButtons.Images.SetKeyName(804, "");
            this.ilButtons.Images.SetKeyName(805, "");
            this.ilButtons.Images.SetKeyName(806, "");
            this.ilButtons.Images.SetKeyName(807, "");
            this.ilButtons.Images.SetKeyName(808, "");
            this.ilButtons.Images.SetKeyName(809, "");
            this.ilButtons.Images.SetKeyName(810, "");
            this.ilButtons.Images.SetKeyName(811, "");
            this.ilButtons.Images.SetKeyName(812, "");
            this.ilButtons.Images.SetKeyName(813, "");
            this.ilButtons.Images.SetKeyName(814, "");
            this.ilButtons.Images.SetKeyName(815, "");
            this.ilButtons.Images.SetKeyName(816, "");
            this.ilButtons.Images.SetKeyName(817, "");
            this.ilButtons.Images.SetKeyName(818, "");
            this.ilButtons.Images.SetKeyName(819, "");
            this.ilButtons.Images.SetKeyName(820, "");
            this.ilButtons.Images.SetKeyName(821, "");
            this.ilButtons.Images.SetKeyName(822, "");
            this.ilButtons.Images.SetKeyName(823, "");
            this.ilButtons.Images.SetKeyName(824, "");
            this.ilButtons.Images.SetKeyName(825, "");
            this.ilButtons.Images.SetKeyName(826, "");
            this.ilButtons.Images.SetKeyName(827, "");
            this.ilButtons.Images.SetKeyName(828, "");
            this.ilButtons.Images.SetKeyName(829, "");
            this.ilButtons.Images.SetKeyName(830, "");
            this.ilButtons.Images.SetKeyName(831, "");
            this.ilButtons.Images.SetKeyName(832, "");
            this.ilButtons.Images.SetKeyName(833, "");
            this.ilButtons.Images.SetKeyName(834, "");
            this.ilButtons.Images.SetKeyName(835, "");
            // 
            // player1
            // 
            this.player1.FileName = "";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.Blue;
            this.label4.Location = new System.Drawing.Point(289, 67);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(466, 13);
            this.label4.TabIndex = 23;
            this.label4.Text = "Chỉ lấy những có có nhiều hơn một lần chuyển vùng. DoubleClick vào dòng để xem ch" +
                "i tiết cuốc.";
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.label4);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Controls.Add(this.calTuNgay);
            this.panel1.Controls.Add(this.btnExportExcel);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Controls.Add(this.btnRefresh);
            this.panel1.Controls.Add(this.calDenNgay);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1032, 117);
            this.panel1.TabIndex = 24;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.gridDienThoai);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel2.Location = new System.Drawing.Point(0, 117);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(1032, 473);
            this.panel2.TabIndex = 25;
            // 
            // frmBC_1_3_ChiTietCuocGoiDen_LogVung
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1032, 590);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "frmBC_1_3_ChiTietCuocGoiDen_LogVung";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "1.3 BC cuộc gọi có chuyển vùng nhiều";
            this.Load += new System.EventHandler(this.frmBaoCaoBieuMau3_Load);
            ((System.ComponentModel.ISupportInitialize)(this.gridDienThoai)).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private Janus.Windows.CalendarCombo.CalendarCombo calTuNgay;
        private Janus.Windows.CalendarCombo.CalendarCombo calDenNgay;
        private System.Windows.Forms.Label label3;
        private Janus.Windows.EditControls.UIButton btnExportExcel;
        private Janus.Windows.EditControls.UIButton btnRefresh;
        private Janus.Windows.GridEX.GridEXPrintDocument gridEXPrintDocument1;
        private Janus.Windows.GridEX.Export.GridEXExporter gridEXExporter1;
        private System.Windows.Forms.SaveFileDialog saveFileDialog1;
        private System.Windows.Forms.PageSetupDialog pageSetupDialog1;
        private System.Windows.Forms.PrintPreviewDialog printPreviewDialog1;
        private Janus.Windows.GridEX.GridEX gridDienThoai;
        private System.Windows.Forms.ImageList ilButtons;
        private Alvas.Audio.Player player1;
        private System.Windows.Forms.Timer timer1;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
       
    }
}