//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormTestServices.Services_DatXe_ThanhCong_V2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap")]
    public interface TaxiOperation_ServicesSoap {
        
        // CODEGEN: Generating message contract since message BookingTaxiRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookingTaxi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiResponse BookingTaxi(FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookingTaxi", ReplyAction="*")]
        System.Threading.Tasks.Task<FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiResponse> BookingTaxiAsync(FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiRequest request);
        
        // CODEGEN: Generating message contract since message BookingTaxi_V2Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookingTaxi_V2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Response BookingTaxi_V2(FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookingTaxi_V2", ReplyAction="*")]
        System.Threading.Tasks.Task<FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Response> BookingTaxi_V2Async(FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Request request);
        
        // CODEGEN: Generating message contract since message CancelBooking_V2Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelBooking_V2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Response CancelBooking_V2(FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelBooking_V2", ReplyAction="*")]
        System.Threading.Tasks.Task<FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Response> CancelBooking_V2Async(FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookingTaxi", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BookingTaxiRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public FormTestServices.Services_DatXe_ThanhCong_V2.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CustName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Addr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string VehType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int Qty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.DateTime Time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string GhiChu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int brand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public short src;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string dmn;
        
        public BookingTaxiRequest() {
        }
        
        public BookingTaxiRequest(FormTestServices.Services_DatXe_ThanhCong_V2.Authentication Authentication, string CustName, string Phone, string Addr, string VehType, int Qty, System.DateTime Time, string GhiChu, int brand, short src, string dmn) {
            this.Authentication = Authentication;
            this.CustName = CustName;
            this.Phone = Phone;
            this.Addr = Addr;
            this.VehType = VehType;
            this.Qty = Qty;
            this.Time = Time;
            this.GhiChu = GhiChu;
            this.brand = brand;
            this.src = src;
            this.dmn = dmn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookingTaxiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BookingTaxiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string BookingTaxiResult;
        
        public BookingTaxiResponse() {
        }
        
        public BookingTaxiResponse(string BookingTaxiResult) {
            this.BookingTaxiResult = BookingTaxiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookingTaxi_V2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BookingTaxi_V2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public FormTestServices.Services_DatXe_ThanhCong_V2.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CustName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Addr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string VehType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int Qty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.DateTime Time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int brand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public short src;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string dmn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string lat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string lng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string senderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string extension1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string extension2;
        
        public BookingTaxi_V2Request() {
        }
        
        public BookingTaxi_V2Request(
                    FormTestServices.Services_DatXe_ThanhCong_V2.Authentication Authentication, 
                    string CustName, 
                    string Phone, 
                    string Addr, 
                    string VehType, 
                    int Qty, 
                    System.DateTime Time, 
                    string description, 
                    int brand, 
                    short src, 
                    string dmn, 
                    string lat, 
                    string lng, 
                    string senderID, 
                    string extension1, 
                    string extension2) {
            this.Authentication = Authentication;
            this.CustName = CustName;
            this.Phone = Phone;
            this.Addr = Addr;
            this.VehType = VehType;
            this.Qty = Qty;
            this.Time = Time;
            this.description = description;
            this.brand = brand;
            this.src = src;
            this.dmn = dmn;
            this.lat = lat;
            this.lng = lng;
            this.senderID = senderID;
            this.extension1 = extension1;
            this.extension2 = extension2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookingTaxi_V2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BookingTaxi_V2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string BookingTaxi_V2Result;
        
        public BookingTaxi_V2Response() {
        }
        
        public BookingTaxi_V2Response(string BookingTaxi_V2Result) {
            this.BookingTaxi_V2Result = BookingTaxi_V2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelBooking_V2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelBooking_V2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public FormTestServices.Services_DatXe_ThanhCong_V2.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string dmn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int brand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string tickedID;
        
        public CancelBooking_V2Request() {
        }
        
        public CancelBooking_V2Request(FormTestServices.Services_DatXe_ThanhCong_V2.Authentication Authentication, string dmn, int brand, string tickedID) {
            this.Authentication = Authentication;
            this.dmn = dmn;
            this.brand = brand;
            this.tickedID = tickedID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelBooking_V2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelBooking_V2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CancelBooking_V2Result;
        
        public CancelBooking_V2Response() {
        }
        
        public CancelBooking_V2Response(string CancelBooking_V2Result) {
            this.CancelBooking_V2Result = CancelBooking_V2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TaxiOperation_ServicesSoapChannel : FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaxiOperation_ServicesSoapClient : System.ServiceModel.ClientBase<FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap>, FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap {
        
        public TaxiOperation_ServicesSoapClient() {
        }
        
        public TaxiOperation_ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaxiOperation_ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxiOperation_ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxiOperation_ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiResponse FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap.BookingTaxi(FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiRequest request) {
            return base.Channel.BookingTaxi(request);
        }
        
        public string BookingTaxi(FormTestServices.Services_DatXe_ThanhCong_V2.Authentication Authentication, string CustName, string Phone, string Addr, string VehType, int Qty, System.DateTime Time, string GhiChu, int brand, short src, string dmn) {
            FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiRequest inValue = new FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiRequest();
            inValue.Authentication = Authentication;
            inValue.CustName = CustName;
            inValue.Phone = Phone;
            inValue.Addr = Addr;
            inValue.VehType = VehType;
            inValue.Qty = Qty;
            inValue.Time = Time;
            inValue.GhiChu = GhiChu;
            inValue.brand = brand;
            inValue.src = src;
            inValue.dmn = dmn;
            FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiResponse retVal = ((FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap)(this)).BookingTaxi(inValue);
            return retVal.BookingTaxiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiResponse> FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap.BookingTaxiAsync(FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiRequest request) {
            return base.Channel.BookingTaxiAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiResponse> BookingTaxiAsync(FormTestServices.Services_DatXe_ThanhCong_V2.Authentication Authentication, string CustName, string Phone, string Addr, string VehType, int Qty, System.DateTime Time, string GhiChu, int brand, short src, string dmn) {
            FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiRequest inValue = new FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxiRequest();
            inValue.Authentication = Authentication;
            inValue.CustName = CustName;
            inValue.Phone = Phone;
            inValue.Addr = Addr;
            inValue.VehType = VehType;
            inValue.Qty = Qty;
            inValue.Time = Time;
            inValue.GhiChu = GhiChu;
            inValue.brand = brand;
            inValue.src = src;
            inValue.dmn = dmn;
            return ((FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap)(this)).BookingTaxiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Response FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap.BookingTaxi_V2(FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Request request) {
            return base.Channel.BookingTaxi_V2(request);
        }
        
        public string BookingTaxi_V2(
                    FormTestServices.Services_DatXe_ThanhCong_V2.Authentication Authentication, 
                    string CustName, 
                    string Phone, 
                    string Addr, 
                    string VehType, 
                    int Qty, 
                    System.DateTime Time, 
                    string description, 
                    int brand, 
                    short src, 
                    string dmn, 
                    string lat, 
                    string lng, 
                    string senderID, 
                    string extension1, 
                    string extension2) {
            FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Request inValue = new FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Request();
            inValue.Authentication = Authentication;
            inValue.CustName = CustName;
            inValue.Phone = Phone;
            inValue.Addr = Addr;
            inValue.VehType = VehType;
            inValue.Qty = Qty;
            inValue.Time = Time;
            inValue.description = description;
            inValue.brand = brand;
            inValue.src = src;
            inValue.dmn = dmn;
            inValue.lat = lat;
            inValue.lng = lng;
            inValue.senderID = senderID;
            inValue.extension1 = extension1;
            inValue.extension2 = extension2;
            FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Response retVal = ((FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap)(this)).BookingTaxi_V2(inValue);
            return retVal.BookingTaxi_V2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Response> FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap.BookingTaxi_V2Async(FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Request request) {
            return base.Channel.BookingTaxi_V2Async(request);
        }
        
        public System.Threading.Tasks.Task<FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Response> BookingTaxi_V2Async(
                    FormTestServices.Services_DatXe_ThanhCong_V2.Authentication Authentication, 
                    string CustName, 
                    string Phone, 
                    string Addr, 
                    string VehType, 
                    int Qty, 
                    System.DateTime Time, 
                    string description, 
                    int brand, 
                    short src, 
                    string dmn, 
                    string lat, 
                    string lng, 
                    string senderID, 
                    string extension1, 
                    string extension2) {
            FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Request inValue = new FormTestServices.Services_DatXe_ThanhCong_V2.BookingTaxi_V2Request();
            inValue.Authentication = Authentication;
            inValue.CustName = CustName;
            inValue.Phone = Phone;
            inValue.Addr = Addr;
            inValue.VehType = VehType;
            inValue.Qty = Qty;
            inValue.Time = Time;
            inValue.description = description;
            inValue.brand = brand;
            inValue.src = src;
            inValue.dmn = dmn;
            inValue.lat = lat;
            inValue.lng = lng;
            inValue.senderID = senderID;
            inValue.extension1 = extension1;
            inValue.extension2 = extension2;
            return ((FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap)(this)).BookingTaxi_V2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Response FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap.CancelBooking_V2(FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Request request) {
            return base.Channel.CancelBooking_V2(request);
        }
        
        public string CancelBooking_V2(FormTestServices.Services_DatXe_ThanhCong_V2.Authentication Authentication, string dmn, int brand, string tickedID) {
            FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Request inValue = new FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Request();
            inValue.Authentication = Authentication;
            inValue.dmn = dmn;
            inValue.brand = brand;
            inValue.tickedID = tickedID;
            FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Response retVal = ((FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap)(this)).CancelBooking_V2(inValue);
            return retVal.CancelBooking_V2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Response> FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap.CancelBooking_V2Async(FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Request request) {
            return base.Channel.CancelBooking_V2Async(request);
        }
        
        public System.Threading.Tasks.Task<FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Response> CancelBooking_V2Async(FormTestServices.Services_DatXe_ThanhCong_V2.Authentication Authentication, string dmn, int brand, string tickedID) {
            FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Request inValue = new FormTestServices.Services_DatXe_ThanhCong_V2.CancelBooking_V2Request();
            inValue.Authentication = Authentication;
            inValue.dmn = dmn;
            inValue.brand = brand;
            inValue.tickedID = tickedID;
            return ((FormTestServices.Services_DatXe_ThanhCong_V2.TaxiOperation_ServicesSoap)(this)).CancelBooking_V2Async(inValue);
        }
    }
}
