//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi.Services.WCFServiceGEO {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationHeader", Namespace="http://schemas.datacontract.org/2004/07/WCF_ServicesLibrary")]
    [System.SerializableAttribute()]
    public partial class AuthenticationHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassWord {
            get {
                return this.PassWordField;
            }
            set {
                if ((object.ReferenceEquals(this.PassWordField, value) != true)) {
                    this.PassWordField = value;
                    this.RaisePropertyChanged("PassWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceResponse", Namespace="http://schemas.datacontract.org/2004/07/WCF_ServicesGEO.Common")]
    [System.SerializableAttribute()]
    public partial class PriceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolylineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((this.DistanceField.Equals(value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxPrice {
            get {
                return this.MaxPriceField;
            }
            set {
                if ((this.MaxPriceField.Equals(value) != true)) {
                    this.MaxPriceField = value;
                    this.RaisePropertyChanged("MaxPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Polyline {
            get {
                return this.PolylineField;
            }
            set {
                if ((object.ReferenceEquals(this.PolylineField, value) != true)) {
                    this.PolylineField = value;
                    this.RaisePropertyChanged("Polyline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceGEO.IServicesOnline")]
    public interface IServicesOnline {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesOnline/GetAddressByGeo", ReplyAction="http://tempuri.org/IServicesOnline/GetAddressByGeoResponse")]
        string GetAddressByGeo(out string building, Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, float lng, float lat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesOnline/GetGeobyAddressBA", ReplyAction="http://tempuri.org/IServicesOnline/GetGeobyAddressBAResponse")]
        string GetGeobyAddressBA(Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, string address, string TenTinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesOnline/GetGeobyAddressBA_Full", ReplyAction="http://tempuri.org/IServicesOnline/GetGeobyAddressBA_FullResponse")]
        string GetGeobyAddressBA_Full(Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesOnline/GetGeobyAddressBA_HN_First", ReplyAction="http://tempuri.org/IServicesOnline/GetGeobyAddressBA_HN_FirstResponse")]
        string GetGeobyAddressBA_HN_First(Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, string address, string TenTinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesOnline/GetAddressByGeo_Google", ReplyAction="http://tempuri.org/IServicesOnline/GetAddressByGeo_GoogleResponse")]
        string GetAddressByGeo_Google(Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, float lng, float lat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesOnline/GetAddressByGeo_Google_WithBuilding", ReplyAction="http://tempuri.org/IServicesOnline/GetAddressByGeo_Google_WithBuildingResponse")]
        string GetAddressByGeo_Google_WithBuilding(out string building, Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, float lng, float lat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesOnline/GetGeoByAddress_Google", ReplyAction="http://tempuri.org/IServicesOnline/GetGeoByAddress_GoogleResponse")]
        string GetGeoByAddress_Google(Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, string address, string TenTinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesOnline/GetGeoByAddress_GoogleV2", ReplyAction="http://tempuri.org/IServicesOnline/GetGeoByAddress_GoogleV2Response")]
        string GetGeoByAddress_GoogleV2(Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesOnline/GetPrice_FromTwoLocation", ReplyAction="http://tempuri.org/IServicesOnline/GetPrice_FromTwoLocationResponse")]
        Taxi.Services.WCFServiceGEO.PriceResponse GetPrice_FromTwoLocation(float fromLat, float fromLng, float toLat, float toLng, int compid, int carType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesOnlineChannel : Taxi.Services.WCFServiceGEO.IServicesOnline, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesOnlineClient : System.ServiceModel.ClientBase<Taxi.Services.WCFServiceGEO.IServicesOnline>, Taxi.Services.WCFServiceGEO.IServicesOnline {
        
        public ServicesOnlineClient() {
        }
        
        public ServicesOnlineClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesOnlineClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesOnlineClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesOnlineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAddressByGeo(out string building, Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, float lng, float lat) {
            return base.Channel.GetAddressByGeo(out building, authenticate, lng, lat);
        }
        
        public string GetGeobyAddressBA(Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, string address, string TenTinh) {
            return base.Channel.GetGeobyAddressBA(authenticate, address, TenTinh);
        }
        
        public string GetGeobyAddressBA_Full(Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, string address) {
            return base.Channel.GetGeobyAddressBA_Full(authenticate, address);
        }
        
        public string GetGeobyAddressBA_HN_First(Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, string address, string TenTinh) {
            return base.Channel.GetGeobyAddressBA_HN_First(authenticate, address, TenTinh);
        }
        
        public string GetAddressByGeo_Google(Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, float lng, float lat) {
            return base.Channel.GetAddressByGeo_Google(authenticate, lng, lat);
        }
        
        public string GetAddressByGeo_Google_WithBuilding(out string building, Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, float lng, float lat) {
            return base.Channel.GetAddressByGeo_Google_WithBuilding(out building, authenticate, lng, lat);
        }
        
        public string GetGeoByAddress_Google(Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, string address, string TenTinh) {
            return base.Channel.GetGeoByAddress_Google(authenticate, address, TenTinh);
        }
        
        public string GetGeoByAddress_GoogleV2(Taxi.Services.WCFServiceGEO.AuthenticationHeader authenticate, string address) {
            return base.Channel.GetGeoByAddress_GoogleV2(authenticate, address);
        }
        
        public Taxi.Services.WCFServiceGEO.PriceResponse GetPrice_FromTwoLocation(float fromLat, float fromLng, float toLat, float toLng, int compid, int carType) {
            return base.Channel.GetPrice_FromTwoLocation(fromLat, fromLng, toLat, toLng, compid, carType);
        }
    }
}
